wellcomecollection/storage-service

- terraform/modules/queue/main.tf
- terraform/stack/messaging.tf
stop removing '-' in sqs names, instead normalise '-' to '_'.
> SQS queue names

- terraform/ecr.tf
- terraform/stack/main.tf
- terraform/stack/messaging.tf
In order that we can place ECR repos for a project within the same account as the storage service and allow publication from the platform account.
> Add ECR repos and policy to publish from platform

- bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/models/DisplayBagInfo.scala
- bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/BagsApiFeatureTest.scala
- bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/models/DisplayBagInfoTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/bag/BagInfoParser.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/models/bagit/BagInfo.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/bag/BagInfoParserTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/BagIt.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/RandomThings.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/BagInfoGenerators.scala
Make the `SourceOrganisation` entry in bag-info.txt optional
---
Ported from https://github.com/wellcometrust/platform/pull/3427 using `git format-patch` and `git am`.
> BagInfo make SourceOrganisation optional

- archivist/src/test/scala/uk/ac/wellcome/platform/archive/archivist/ArchivistFeatureTest.scala
- archivist/src/test/scala/uk/ac/wellcome/platform/archive/archivist/TroubleshootArchivistLocalBagFileTest.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/BagReplicatorFeatureTest.scala
- bags/src/test/scala/uk/ac/wellcome/platform/archive/registrar/async/RegistrarFeatureTest.scala
- bags/universal/conf/application.conf.template
- bags_api/src/main/resources/application.conf
- bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/BagsApiFeatureTest.scala
- ingests/src/test/scala/uk/ac/wellcome/platform/archive/progress_async/ProgressAsyncFeatureTest.scala
- ingests_api/src/main/resources/application.conf
- ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/IngestsApiFeatureTest.scala
- notifier/src/test/scala/uk/ac/wellcome/platform/archive/notifier/NotifierFeatureTest.scala
I suspect this is required for https://github.com/wellcometrust/platform/issues/3423.
>  Add a metrics namespace to the bags and ingests APIs

- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/storage/BagStorage.scala
- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/storage/S3PrefixCopier.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/fixtures/S3CopierFixtures.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/storage/BagStorageTest.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/storage/S3CopierTest.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/storage/S3PrefixCopierTest.scala
The BagStorage class in the replicator contained a lot of logic for copying objects around in S3, but most of it wasn’t BagLocation-specific.
This patch adds an intermediate class “S3PrefixCopier”, which does the actual work of copying around S3 directories, and BagStorage becomes a thin wrapper that calls that class.
There are new tests for the S3Copier code, which we can now access directly rather than through an intermediary.
Notably, this includes a test for the case where the bag contains more than 1000 objects – which currently fails, because you can’t get more than 1000 objects from a single ListObject call. I considered fixing that in this patch, but that will need more thought. Simply loading all the objects into memory will crash on a big bag; the alternative is something with …
> Split an S3PrefixCopier out of BagStorage; improve the testing of this code

- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/storage/BagStorage.scala
- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/storage/ObjectCopier.scala
- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/storage/S3Copier.scala
- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/storage/S3PrefixCopier.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/storage/S3CopierTest.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/storage/S3PrefixCopierTest.scala
I found a paginator in the V1 API, and so I wrote some super-simple code that blocks when copying every single object. Includes a test that it works for lots of objects, and that if an individual object fails, we fail the entire copy.
I’ve also added a new `ObjectCopier` trait, because making this abstract opens the door to copying from S3 to elsewhere later (e.g. Azure).
Resolves https://github.com/wellcometrust/platform/issues/3450
> Copy the entire contents of a bag in the replicator, not just the first 1000 objects

- archivist/src/main/scala/uk/ac/wellcome/platform/archive/archivist/bag/ArchiveJobCreator.scala
- archivist/src/test/scala/uk/ac/wellcome/platform/archive/archivist/ArchivistFeatureTest.scala
- archivist/src/test/scala/uk/ac/wellcome/platform/archive/archivist/bag/ArchiveJobCreatorTest.scala
- archivist/src/test/scala/uk/ac/wellcome/platform/archive/archivist/flow/ArchiveZipFileFlowTest.scala
- archivist/src/test/scala/uk/ac/wellcome/platform/archive/archivist/generators/ArchiveJobGenerators.scala
- archivist/src/test/scala/uk/ac/wellcome/platform/archive/archivist/models/UploadLocationBuilderTest.scala
- bag_replicator/src/main/resources/application.conf
- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/config/BagReplicatorConfig.scala
- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/config/ReplicatorDestinationConfig.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/BagReplicatorFeatureTest.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/fixtures/BagReplicatorFixtures.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/storage/BagStorageTest.scala
- bags/src/test/scala/uk/ac/wellcome/platform/archive/bags/async/RegistrarFeatureTest.scala
- bags/src/test/scala/uk/ac/wellcome/platform/archive/bags/async/factories/StorageManifestFactoryTest.scala
- bags/src/test/scala/uk/ac/wellcome/platform/archive/bags/async/fixtures/RegistrarFixtures.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/models/bagit/BagLocation.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/BagLocationFixtures.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/models/bagit/BagLocationTest.scala
Make the storagePrefix optional in BagLocation, so that it can match DLCS for access copies.
> Optional storage prefix

- bags/src/main/scala/uk/ac/wellcome/platform/archive/bags/async/services/StorageManifestService.scala
- bags/src/test/scala/uk/ac/wellcome/platform/archive/bags/async/services/StorageManifestServiceTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/bag/BagDigestFileCreator.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/bag/BagInfoParser.scala
A first bit of refactoring for making the Bags app Akka-free.
@kenoir – I think this contains the majority of model changes, and can be merged separately. The rest of the app needs more work, and I messed up the first go, but this bit is a neat standalone bit we can get in now.
> Split out a StorageManifestService in the bags app

- common/src/main/scala/uk/ac/wellcome/platform/archive/common/models/bagit/ChecksumVerifier.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/models/bagit/ChecksumVerifierTest.scala
Log errors instead of throwing exceptions, return an option when there is nothing to do.
If there are no exceptions we can predictably close the stream when done.
> Scalaify ChecksumVerifier

- terraform/main_colbert.tf
- terraform/main_stewart.tf
- terraform/modules/queue/main.tf
- terraform/modules/queue/variables.tf
- terraform/stack/main.tf
- terraform/stack/messaging.tf
- terraform/stack/variables.tf
Plus this wires up the bag verifier to the archivist output, not the “bags” topic.
> Tidy up the queues module; rename some locals to make it easier to see how queues flow

- archivist/src/main/scala/uk/ac/wellcome/platform/archive/archivist/bag/ArchiveJobCreator.scala
- archivist/src/main/scala/uk/ac/wellcome/platform/archive/archivist/bag/ZippedBagFile.scala
- archivist/src/test/scala/uk/ac/wellcome/platform/archive/archivist/ArchivistFeatureTest.scala
- archivist/src/test/scala/uk/ac/wellcome/platform/archive/archivist/bag/ZippedBagFileTest.scala
- archivist/src/test/scala/uk/ac/wellcome/platform/archive/archivist/flow/ArchiveZipFileFlowTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/BagInfoLocator.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/S3BagFile.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/BagInfoLocatorTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/S3BagFileTest.scala
This patch puts the code for detecting the bag-info.txt in a list of filenames in a pure, in-memory class, and then we can call it for either ZIP files in the archivist or S3 objects more generally.
> Add code for locating the root of a bag in an S3 location

- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/Unpacker.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/fixtures/CompressFixture.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/UnpackerTest.scala
The unpacker should ignore "./" at the beginning of entry paths and not attempt to create directories in S3.
> Fix directory handling in unpacker

- bagger/src/aws.py
- bagger/src/bagger.py
- bagger/src/files.py
- bagger/src/mets.py
- bagger/src/storage.py
* Records details under __warnings key in error bucket
* Continues processing, so accommodates errors in some files when renumbering AMD identifiers
* Includes a retry operation when fetching missing files from Preservica via DDS
> Treat AMD mismatch and missing ALTOs as warnings, and continue

- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/Unpacker.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/UnpackerTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/RandomThings.scala
A somewhat speculative fix for https://github.com/wellcometrust/platform/issues/3480.
You can’t upload more than 5GB in a single PutObject request to S3 – after that, you’re meant to switch to MultipartUpload. We weren’t doing that, hence why the really big uploads failed.
The Java SDK docs suggest we should be using TransferManager instead: https://docs.aws.amazon.com/AmazonS3/latest/dev/usingHLmpuJava.html
I’m struggling to test it because I can’t reproduce the error with our S3 Docker image (it seems to accept arbitrarily large file uploads with a single PutObject call, or at least bigger than I can create during a test run), but it doesn't break any existing tests. Worth a try?
> Use a TransferManager to upload objects in the unpacker

- terraform/stack/main.tf
Because the bagger is running at the limit of its network interfaces, it can't deploy new task definitions – the old ones never go away, and it can't start new ones.
This frees up a single slot for the bagger to start a new task definition, so it can gradually update itself without needing us to go in and stop all the existing tasks.
> Give the bagger room to deploy new tasks

- terraform/stack/locals.tf
It's using the old namespace "bags" which is a bit confusing, this PR changes it to "bag_register".
> Bag register submitting metrics in wrong namespace

- bagger/src/mets.py
Follows https://github.com/wellcometrust/platform/issues/3302
An IndexError isn’t especially helpful, and there might be others lurking we’ve missed – this small change means we can distinguish between this error and another one we haven’t seen yet.
> Give a more descriptive error if we can't find a title in the METS

- terraform/main_colbert.tf
- terraform/stack/api/main.tf
- terraform/stack/api/services/bags.tf
- terraform/stack/api/services/ingests.tf
- terraform/stack/api/variables.tf
- terraform/stack/main.tf
In order to prevent performance issues.
> API via NLB task count must equal AZ count

- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/config/builders/UnpackerConfigBuilder.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/config/builders/UnpackerConfigBuilderTest.scala
- terraform/stack/main.tf
Parse the unpacker config `unpacker.buffer.size` even if it is an integer wrapped in a String.  This looks to be the way Typesafe Config behaves when replacing environment variables.
Consider moving this more genrally to the EnrichConfig builders.
> Unpacker config

- bagger/src/aws.py
- bagger/src/files.py
files.py uses an aws bucket but had lost the ability to acquire one.
> Allow files module to get an s3 bucket

- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/S3Uploader.scala
Because otherwise the ResetException will still occur when trying to do multipart uploads.
> Also set the multipart upload threshold to the buffer size

- terraform/config.tf
- terraform/critical/variables.tf
- terraform/locals.tf
- terraform/main_critical.tf
- terraform/modules/service/worker/variables.tf
- terraform/stack/api/main.tf
- terraform/stack/api/variables.tf
- terraform/stack/main.tf
- terraform/stack/variables.tf
We should use `${local.ingests_api_service_name}`, but we were actually using `${local.ingests_service_name}`.
One way to detect this is to look for unused locals (which would show us we’d defined this but never used it) – script is in [alexwlchan/junkdrawer#87f5769](https://github.com/alexwlchan/junkdrawer/blob/87f57690969895c0756b9f13ab118a4de9b3b8e8/terraform/find_unused_locals_and_vars.py), cleaning up other unused vars/locals is in this PR.
Hopefully the last piece of https://github.com/wellcometrust/platform/issues/3423.
> Fix the metrics namespace for the ingests API

- terraform/critical/s3.tf
- terraform/stack/main.tf
In order that we don't store unnecessary objects.
> Add expiry policies to temp storage buckets

- terraform/stack/iam_role_policy.tf
- terraform/stack/locals.tf
- terraform/stack/main.tf
- terraform/stack/messaging.tf
Closes wellcometrust/platform#3520. This adds a new verification after unpacking succeeds but before we replicate the bag. The new event list looks as follows:
```json
"events": [
{
"createdDate": "2019-04-08T11:06:12.903439Z",
"description": "Unpacking succeeded",
"type": "IngestEvent"
},
{
"createdDate": "2019-04-08T11:06:13.406794Z",
"description": "Verification succeeded",
"type": "IngestEvent"
},
{
"createdDate": "2019-04-08T11:06:16.357395Z",
"description": "Replicating succeeded",
"type": "IngestEvent"
},
{
"createdDate": "2019-04-08T11:06:17.474Z",
"description": "Verification succeeded",
"type": "IngestEvent"
},
{
"createdDate": "2019-04-08T11:06:22.412378Z",
"description": "Register succeeded (completed)",
"type": "IngestEvent"
}
],
```
> Verify all bags before replicating them to our storage

- bagger/src/mappings.py
- bagger/src/tech_md.py
- terraform/main_colbert.tf
- terraform/main_stewart.tf
This adds a couple of new PRONOM mappings that the bagger doesn't recognise (based on the errors in the dashboard), and makes the error a bit more descriptive when it occurs.
For wellcometrust/platform#3322.
> Add a couple of new PRONOM mappings to the bagger

- bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/models/AuditSummary.scala
- bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/services/BagAuditor.scala
- bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/services/BagAuditorWorker.scala
- bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/models/RegistrationSummary.scala
- bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorker.scala
- bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/services/Register.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/BagRegisterFeatureTest.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorkerTest.scala
- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/models/ReplicationSummary.scala
- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicator.scala
- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorker.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/models/VerificationSummary.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierWorker.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/Verifier.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixtures/BagVerifierFixtures.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/models/VerificationSummaryTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/VerifierTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/PipelinePayload.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestService.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/BagLocationFixtures.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestServiceTest.scala
- notifier/src/main/scala/uk/ac/wellcome/platform/archive/notifier/services/CallbackUrlService.scala
- notifier/src/main/scala/uk/ac/wellcome/platform/archive/notifier/services/NotifierWorker.scala
- notifier/src/test/scala/uk/ac/wellcome/platform/archive/notifier/services/CallbackUrlServiceTest.scala
This patch doesn't change the external interfaces of any of the apps, but it does add the initial `ObjectLocationPayload` case class and do a bunch of refactoring internally so the change to the external interfaces should be a smaller patch.
> Prepare for payloads!

- bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/models/AuditSummary.scala
- bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/services/BagAuditor.scala
- bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/services/BagAuditorWorker.scala
- bag_auditor/src/test/scala/uk/ac/wellcome/platform/storage/bagauditor/BagAuditorFeatureTest.scala
- bag_auditor/src/test/scala/uk/ac/wellcome/platform/storage/bagauditor/services/BagAuditorTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/PipelinePayload.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/BagLocationFixtures.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/PayloadGenerators.scala
- project/Dependencies.scala
For wellcometrust/platform#2777
These payloads are backwards-compatible, so the verifier/replicator will ignore the extra information for now.
> Auditor: Include the external identifier and bag version in the payload it sends

- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicator.scala
- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/DestinationBuilder.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/fixtures/BagReplicatorFixtures.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorkerTest.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/DestinationBuilderTest.scala
Refactoring in anticipation of wellcometrust/platform#2777
Our tests checked that the replicator had indeed copied files to the stated destination, but made no attempt to check the destination was sensible! I’m about to change this logic for the new payloads, so let’s get some proper tests around it.
> Improve the replicator tests around destination building

- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicator.scala
- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorker.scala
- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/DestinationBuilder.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/BagReplicatorFeatureTest.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorkerTest.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/DestinationBuilderTest.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierWorker.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/VerifierFeatureTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/VerifierWorkerTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/PayloadGenerators.scala
Another step towards wellcometrust/platform#2777!
The verifier passes through the result transparently.
The replicator is a bigger change – we tweak the way we construct the destination, add a `v1`/`v2`/`vN` suffix to paths, and get to simplify some of its internal code!
> Use the new payloads in the bag verifier and bag replicator

- common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/parsers/FetchContents.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/parsers/FetchContentsTest.scala
In #198 we'd quite happily let such a fetch.txt through, which is obviously wrong. This throws an exception instead.
> Handle the case where a fetch.txt isn't correctly formatted

- bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/Main.scala
- bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/models/BetterAudit.scala
- bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/models/BetterAuditSummary.scala
- bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/services/BagAuditor.scala
- bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/services/BagAuditorWorker.scala
- bag_auditor/src/test/scala/uk/ac/wellcome/platform/storage/bagauditor/BagAuditorFeatureTest.scala
- bag_auditor/src/test/scala/uk/ac/wellcome/platform/storage/bagauditor/fixtures/BagAuditorFixtures.scala
- bag_auditor/src/test/scala/uk/ac/wellcome/platform/storage/bagauditor/services/BagAuditorTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/parsers/BagInfoParser.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/config/builders/IngestUpdaterBuilder.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/ingests/services/IngestUpdater.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestService.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/OperationFixtures.scala
A standalone piece spun out of #205 to make it smaller and so easier to review, and I took the models from #204 to avoid icky merge conflicts later.
You now get the following messages from the auditor:
```json
{
"createdDate": "2019-05-15T16:26:47.885084Z",
"description": "Auditing bag started",
"type": "IngestEvent"
},
{
"createdDate": "2019-05-15T16:26:48.823683Z",
"description": "Detected bag root as wellcomecollection-storage-staging-ingests/unpacked/alex-testing/6ddaad8a-03ff-4cab-af67-e758a214ae5f",
"type": "IngestEvent"
},
{
"createdDate": "2019-05-15T16:26:48.823692Z",
"description": "Detected bag identifier as b1000290x",
"type": "IngestEvent"
},
{
"createdDate": "2019-05-15T16:26:48.823697Z",
"description": "Assigned bag version 2",
"type": "IngestEvent"
},
{
"createdDate": …
```
> Send more information about the audit results

- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixtures/VerifyFixtures.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/S3ObjectVerifierTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/models/BagFetch.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/models/BagLocation.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/services/BagVerifiable.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/S3ObjectVerifier.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/S3StreamableInstances.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/verify/VerifiableLocation.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/models/BagFetchTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/services/BagVerifiableTest.scala
The fetch file tells us the length of the object it points to, but right now we don't check it anywhere.
This patch modifies the VerifiableLocation to carry the length specified by the fetch entry (if any), and the S3ObjectVerifier to check the length matches (if present).
You can’t get the length from a plain `S3ObjectInputStream`, so I’m wrapping it in our own class `S3ObjectStream`, which includes the Content-Length from the S3 headers.
Along the way, I discovered that those sizes can be large than Int.MaxValue, so I swapped it out for Long and added a test that we can parse fetch entries that point to files with large sizes.
Closes wellcometrust/platform#3638.
> Check the length of entries referenced in fetch files

- bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/services/BagAuditorWorker.scala
- bag_auditor/src/test/scala/uk/ac/wellcome/platform/storage/bagauditor/BagAuditorFeatureTest.scala
- bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorker.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/BagRegisterFeatureTest.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorkerTest.scala
- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorker.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/BagReplicatorFeatureTest.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorkerTest.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierWorker.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/BagVerifierFeatureTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierWorkerTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/PipelinePayload.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/PayloadGenerators.scala
Closes wellcometrust/platform#3658.
The verifier only cares that it gets a payload with an ingest ID and a root location; it doesn't care about whether it has a version, external identifier, ingest date, etc… So the new `BagRootPayload` trait has everything the verifier cares about, and nothing more.
This opens the door to verifying before we assign a version.
> Make the verifier be more agnostic about the payload type

- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/BagUnpackerWorker.scala
- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/Unpacker.scala
- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/storage/Archive.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/fixtures/BagUnpackerFixtures.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/UnpackerTest.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/storage/ArchiveTest.scala
There's a whole pile of `Future.fromTry { ... }` having to wrap a single Future that doesn't need to be a Future, so ditch it all.
> Expunge the use of Future from the unpacker

- api/ingests_api/src/main/scala/uk/ac/wellcome/platform/storage/ingests/api/IngestStarter.scala
- api/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/IngestStarterTest.scala
- api/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/IngestsApiFeatureTest.scala
- bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/services/BagAuditorWorker.scala
- bag_auditor/src/test/scala/uk/ac/wellcome/platform/storage/bagauditor/BagAuditorFeatureTest.scala
- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/BagUnpackerWorker.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/UnpackerFeatureTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierWorkerTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/PipelineContext.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/PipelinePayload.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/SourceLocationPayloadTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/UnpackedBagLocationPayloadTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/UnpackedBagPayloadTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/PayloadGenerators.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/operation/services/OutgoingPublisherTest.scala
Allows us to pass around much more consistent information.
Closes https://github.com/wellcometrust/platform/issues/3656, closes #222
> Add a context to PipelinePayload

- api/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/IngestsApiFeatureTest.scala
For wellcometrust/platform#2777
It turns out the ingests API has accepted `"ingestType": {"id": "update", …}` for a while, but we didn't have any tests to exercise that functionality or check it did the right thing. Now we do!
> Add tests that POST /ingests accepts an ingestType of "update"

- bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/Main.scala
- bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/models/Audit.scala
- bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/models/AuditError.scala
- bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/models/AuditSuccess.scala
- bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/models/AuditSummary.scala
- bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/services/BagAuditor.scala
- bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/services/BagAuditorWorker.scala
- bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/services/UserFacingMessages.scala
- bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/versioning/VersionPicker.scala
- bag_auditor/src/test/scala/uk/ac/wellcome/platform/storage/bagauditor/BagAuditorFeatureTest.scala
- bag_auditor/src/test/scala/uk/ac/wellcome/platform/storage/bagauditor/fixtures/VersionPickerFixtures.scala
- bag_auditor/src/test/scala/uk/ac/wellcome/platform/storage/bagauditor/services/BagAuditorTest.scala
- bag_auditor/src/test/scala/uk/ac/wellcome/platform/storage/bagauditor/versioning/VersionPickerTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/versioning/IngestVersionManager.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/versioning/IngestVersionManagerError.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/PayloadGenerators.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/ingests/fixtures/IngestUpdateAssertions.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/versioning/IngestVersionManagerTest.scala
Closes wellcometrust/platform#3657, and possibly wellcometrust/platform#3499?
It includes some new user-facing messages in the ingests response:
> Unable to find an external identifier
>
> This bag has never been ingested before, but was sent with ingestType update
>
> This bag has already been ingested, but was sent with ingestType create
>
> Another version of this bag was ingested at ${e.stored}, which is newer than the current ingest ${e.request}
I discovered wellcometrust/platform#3693 while working on this.
> Bag auditor checks ingest type before assigning a version

- bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/services/BagAuditor.scala
- bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/services/UserFacingMessages.scala
- bag_auditor/src/test/scala/uk/ac/wellcome/platform/storage/bagauditor/BagAuditorFeatureTest.scala
- bag_auditor/src/test/scala/uk/ac/wellcome/platform/storage/bagauditor/services/BagAuditorTest.scala
Closes https://github.com/wellcometrust/platform/issues/3695
Along the way, I discovered that the bag auditor was still doing bag root detection, even though it's not supposed to. Ditch that!
> Distinguish between “there’s no bag-info.txt” and “the bag-info.txt has the wrong contents”

- api/ingests_api/src/main/scala/uk/ac/wellcome/platform/storage/ingests/api/IngestStarter.scala
- api/ingests_api/src/main/scala/uk/ac/wellcome/platform/storage/ingests/api/Router.scala
- api/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/IngestStarterTest.scala
- api/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/IngestsApiFeatureTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/HttpFixtures.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/DisplayBag.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/DisplayIngest.scala
- display/src/test/scala/uk/ac/wellcome/platform/archive/display/DisplayIngestTest.scala
- notifier/src/test/scala/uk/ac/wellcome/platform/archive/notifier/NotifierFeatureTest.scala
Closes wellcometrust/platform#3702
Rather than asking for a flat string "externalIdentifier", the ingests API now looks for a "Bag" object.
Along the way, I tidied up the tests for the ingests API to make them easier to follow and reduce the boilerplate. We have more tests, less code!
I also found a couple of places where the RFC doesn't match the API – see wellcometrust/platform#3704.
> Change the ingests API to reflect the RFC

- api/bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/Router.scala
- api/bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/BagsApiFeatureTest.scala
- api/bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/fixtures/BagsApiFixture.scala
- bag_auditor/src/test/scala/uk/ac/wellcome/platform/storage/bagauditor/BagAuditorFeatureTest.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/BagRegisterFeatureTest.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/fixtures/BagRegisterFixtures.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorkerTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestDao.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/StorageManifestVHSFixture.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/PayloadGenerators.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestDaoTest.scala
For wellcometrust/platform#3625.
Previously this class would store a manifest at version 0; now it inspects the manifest to see the version it contains and uses that to put it in VHS.
> Store multiple versions of a storage manifest

- bagger/src/storage_api.py
So far this is the only change needed to Python migration tools, as they aren't consuming ingests or bag API responses.
> change format of POST to /ingest

- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/Main.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifier.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixtures/BagVerifierFixtures.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/S3ObjectVerifier.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/verify/Verification.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/verify/Verifier.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/verify/memory/MemoryVerifier.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/verify/s3/S3ObjectVerifier.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/VerifyFixtures.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/S3ObjectVerifierTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/verify/VerifierTestCases.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/verify/memory/MemoryVerifierTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/verify/s3/S3ObjectVerifierTest.scala
Most of this logic has nothing to do with S3 – we can pull it into a type class, test it thoroughly and take another step towards Docker-free tests.
> Replace S3ObjectVerifier with a Verifier type class and two implementations

- terraform/endpoints.tf
- terraform/main_colbert.tf
- terraform/main_letterman.tf
- terraform/outputs.tf
- terraform/stack/api/domain/main.tf
- terraform/stack/api/domain/ouputs.tf
- terraform/stack/api/domain/variables.tf
- terraform/stack/api/gateway.tf
- terraform/stack/api/outputs.tf
- terraform/stack/outputs.tf
Closes https://github.com/wellcometrust/platform/issues/3723, which makes it easier to set up DNS if you've changed something
Plus now uses "prod"/"staging" instead of "stewart/colbert/letterman".
> Tidy up the Terraform

- bag_unpacker/docker-compose.yml
- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/Unpacker.scala
- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/s3/S3Unpacker.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/UnpackerFeatureTest.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/UnpackerTestCases.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/s3/S3UnpackerTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/PayloadGenerators.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/operation/services/OutgoingPublisherTest.scala
This adds two new error messages to the unpacker:
* If we go to unpack a bag from S3 and discover it's in a bucket we can't read, we send the message
> Unpacking failed - Access denied while trying to read s3://bucket/archive.tar.gz
* If we go to unpack a bag and discover it's not in tar.gz format, we send the message
> Unpacking failed - Error trying to unpack the archive at bucket/archive.tar.gz - is it the correct format?
This is one of the things @jtweed flagged in testing. We need to be a bit more consistent about when we use S3 URIs in user-facing messages, but that's a separate patch.
> Improve the user-facing error messages from the unpacker

- bag_root_finder/src/main/scala/uk/ac/wellcome/platform/storage/bag_root_finder/services/BagRootFinder.scala
- bag_root_finder/src/main/scala/uk/ac/wellcome/platform/storage/bag_root_finder/services/BagRootFinderWorker.scala
- bag_root_finder/src/test/scala/uk/ac/wellcome/platform/storage/bag_root_finder/BagRootFinderFeatureTest.scala
The existence of the unpacked location is an internal detail of the storage service, and shouldn't be exposed to users -- just say "we couldn't find the bag root".
Closes https://github.com/wellcometrust/platform/issues/3708
> Don't expose information about the unpacked location

- bag_root_finder/src/main/scala/uk/ac/wellcome/platform/storage/bag_root_finder/models/RootFinderSummary.scala
- bag_root_finder/src/main/scala/uk/ac/wellcome/platform/storage/bag_root_finder/services/BagRootFinder.scala
- bag_root_finder/src/main/scala/uk/ac/wellcome/platform/storage/bag_root_finder/services/BagRootFinderWorker.scala
A quick refactoring spotted while working on #258 – we pass around internal info we don’t need.
> Pass around less information inside the bag root finder

- api/bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/fixtures/BagsApiFixture.scala
- api/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/IngestStarterTest.scala
- api/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/fixtures/IngestsApiFixture.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/UnpackerFeatureTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/services/BagReader.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/config/builders/StorageManifestDaoBuilder.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/verify/Verifier.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/StorageManifestVHSFixture.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/verify/s3/S3ObjectVerifierTest.scala
- ingests_common/src/main/scala/uk/ac/wellcome/platform/archive/common/ingests/tracker/memory/MemoryIngestTracker.scala
- ingests_common/src/test/scala/uk/ac/wellcome/platform/archive/common/ingests/tracker/fixtures/IngestTrackerFixtures.scala
- ingests_common/src/test/scala/uk/ac/wellcome/platform/archive/common/ingests/tracker/memory/MemoryIngestTrackerTest.scala
- project/Dependencies.scala
The key thing this gets us is that S3StreamStore is now exposing the underlying S3 exception, so we can send better messages in the unpacker.
> Bump the scala-storage lib

- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/s3/S3Unpacker.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/UnpackerFeatureTest.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/UnpackerTestCases.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/s3/S3UnpackerTest.scala
New messages:
* Not all strings are valid S3 bucket names (e.g. bucket names must be lowercase), so if the SDK complains we pass that up to the user:
> Unpacking failed - BUKKIT is not a valid S3 bucket name
* If you tell us to look in a bucket that flat out doesn't exist, previously we'd send a slightly generic "Could not read archive", now we send
> Unpacking failed - There is no S3 bucket mygreatbukkit
* And now if the bucket exists, but the key doesn't, we send:
> Unpacking failed - There is no archive at s3://mygreatbukkit/archive.tar.gz
Previously we wouldn't add the `s3://` prefix; now we're consistent.
Closes https://github.com/wellcometrust/platform/issues/3735.
We can give a better error if the source bucket is in a different region …
> Improve the unpacker user-facing messages some more

- api/bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/Router.scala
- api/bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/models/DisplayResultList.scala
- api/bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/BagsApiFeatureTest.scala
- api/bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/fixtures/BagsApiFixture.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/http/HttpMetrics.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestDao.scala
Following the model defined in https://github.com/wellcometrust/platform/pull/3733, for https://github.com/wellcometrust/platform/issues/3731
This is missing a couple of pieces:
* The manifests don't have URLs on them; you have to know what to do with the version
* There's no `"latest": true` flag yet
Both are small frills that can be tackled in a separate PR (or dropped).
Plus better test coverage of the bags API. (Tests for internal server errors are back, and they're logging better info to boot.)
> Add a minimal /versions endpoint to the bags API

- common/src/main/scala/uk/ac/wellcome/platform/archive/common/ingests/services/IngestStates.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/ingests/services/IngestStatesTest.scala
- ingests_common/src/main/scala/uk/ac/wellcome/platform/archive/common/ingests/tracker/IngestTracker.scala
Closes https://github.com/wellcometrust/platform/issues/3698
I also pulled the logic for doing the ingest updates out of the IngestTracker, and into a standalone IngestStates object.
> When an ingest enters the pipeline, set the status to "processing"

- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifier.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/BagVerifierFeatureTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/verify/Checksum.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/verify/Verifier.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/ChecksumTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/verify/VerifierTestCases.scala
Improvements:
* If the bag is malformed (e.g. no bag-info.txt), we'll expose those error messages directly. For example:
> Verifying failed - Error loading manifest-sha256.txt: no such file!
* All the verifier failures are now logged internally, for example:
> Errors verifying nqekgiix/M8TijdiT/QDxbEBoa:
> http://localhost:33333/nqekgiix/M8TijdiT/QDxbEBoa/data/dir0/1.txt: Checksum values do not match! Expected: sha256:badDigest, saw: sha256:5aee3da76d46986f296ba30c62e64fe1bd4df115194a823fda540cc68ea9d9e8
Also, that including "expected"/"saw" in the error message is new, to help with diagnostics.
* The user-facing message now tells you if there were verification failures:
> Verifying failed - There was 1 error verifying the bag
> Verifying failed - There were 5 errors verifying the bag …
> Improve the errors from the bag verifier

- bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/services/BagAuditor.scala
- bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/services/BagAuditorWorker.scala
- bag_auditor/src/test/scala/uk/ac/wellcome/platform/storage/bagauditor/BagAuditorFeatureTest.scala
- bag_auditor/src/test/scala/uk/ac/wellcome/platform/storage/bagauditor/services/BagAuditorTest.scala
- bag_root_finder/src/main/scala/uk/ac/wellcome/platform/storage/bag_root_finder/services/BagRootFinderWorker.scala
- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/Unpacker.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/UnpackerFeatureTest.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/UnpackerTestCases.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/ingests/services/IngestUpdater.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/operation/services/OutgoingPublisher.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/models/IngestStepResult.scala
I have a weird problem: ingest 0046a6ac-1736-4648-aafd-d2a8234310a1 reports "Unpacking succeeded", but there's no sign of it in the unpacker bucket!
I wondered if I'd mucked up the packaging somehow, and it wasn't finding anything – this PR modifies the unpacker so it now says:
> Unpacking succeeded - Unpacked 1234 bytes from 5678 files
It turns out that's not the issue here, as testified by the logs:
> 09:35:38.566 [main-actor-system-akka.actor.default-dispatcher-10] INFO u.a.w.p.a.c.s.m.IngestStepWorker$$anon$1 - Successful: id=0046a6ac-1736-4648-aafd-d2a8234310a1, src=wellcomecollection-storage-staging-bagger-drop/b21000633-with-payload-oxum.tar.gz, dst=ObjectLocationPrefix(wellcomecollection-storage-staging-ingests,unpacked/alex-testing/0046a6ac-1736-4648-aafd-d2a8234310a1), files=14, …
> Unpacker includes a list of how many files/bytes it's unpacked

- terraform/stack/iam_role_policy.tf
Tentative fix for wellcometrust/platform#3744.
> Grant the pre-replication verifier perms to the replicator bucket

- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/BagRegisterFeatureTest.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/fixtures/BagRegisterFixtures.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorkerTest.scala
- bag_root_finder/src/test/scala/uk/ac/wellcome/platform/storage/bag_root_finder/BagRootFinderFeatureTest.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifier.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/BagVerifierFeatureTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierWorkerTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/verify/Verification.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/verify/VerifiedLocation.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/verify/Verifier.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/models/BagInfoTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/services/BagReaderTestCases.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/S3BagLocationFixtures.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/StorageRandomThings.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/BagInfoGenerators.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/PayloadOxumGenerators.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/verify/VerifierTestCases.scala
For https://github.com/wellcometrust/platform/issues/3745, https://github.com/wellcometrust/platform/issues/3765
I wanted to add the verifier check that every file in S3 is referred to by a manifest (https://github.com/wellcometrust/platform/issues/3688, because I think it's the root of https://github.com/wellcometrust/platform/issues/3743), but I discovered I had to do some verifier refactoring first.
The core of BagVerifier is now a lot simpler, and you can see which checks we're doing more easily:
```scala
val internalResult =
for {
bag <- getBag(root, startTime = startTime)
_ <- verifyExternalIdentifier(
bag = bag,
externalIdentifier = externalIdentifier,
root = root,
startTime = startTime
)
_ <- verifyPayloadOxumFileCount(bag)
result <- verifyChecksums(
root = root,
bag = bag, …
```
> Refactor the verifier for more checks, and check the first half of Payload-Oxum

- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/Main.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifier.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixtures/BagVerifierFixtures.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/verify/Verification.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/verify/VerifiedLocation.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/verify/Verifier.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/verify/VerifierTestCases.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/verify/s3/S3ObjectVerifierTest.scala
Closes https://github.com/wellcometrust/platform/issues/3688, and will probably shed light on https://github.com/wellcometrust/platform/issues/3743
If you verify a bag and there are files that the manifest doesn't expect, you get an error:
> Bag contains a file which is not referenced in the manifest: /unreferencedfile.txt
>
> Bag contains 3 files which are not referenced in the manifest: /unreferencedfile_1.txt, /unreferencedfile_2.txt, /unreferencedfile_3.txt
Internally, we log the complete object location.
(My theory for https://github.com/wellcometrust/platform/issues/3743 is that when you create a tar archive with macOS, it's creating some extra files with extended attribute data, and thus breaking the S3 console. Those files aren't referenced in the manifests, so the verifier will …
> Check for unreferenced files in the bag

- api/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/IngestsApiFeatureTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/ingests/models/Ingest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/IngestGenerators.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/ingests/fixtures/TimeTestFixture.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/ingests/models/IngestTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestServiceTest.scala
- display/src/test/scala/uk/ac/wellcome/platform/archive/display/DisplayIngestTest.scala
- ingests_common/src/test/scala/uk/ac/wellcome/platform/archive/common/ingests/tracker/fixtures/IngestTrackerFixtures.scala
- notifier/src/test/scala/uk/ac/wellcome/platform/archive/notifier/NotifierFeatureTest.scala
- notifier/src/test/scala/uk/ac/wellcome/platform/archive/notifier/services/PrepareNotificationServiceTest.scala
Closes https://github.com/wellcometrust/platform/issues/3773. Spun out as a separate piece from #280.
Rather than setting the last modified date explicitly, we compute it from the latest IngestEvent date.
> Set the last modified date on an ingest

- bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/services/BagAuditorWorker.scala
- bag_auditor/src/test/scala/uk/ac/wellcome/platform/storage/bagauditor/BagAuditorFeatureTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/ingests/models/Ingest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/ingests/models/IngestUpdate.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/ingests/services/IngestStates.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/ingests/services/IngestUpdater.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/IngestGenerators.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/ingests/fixtures/IngestUpdateAssertions.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/ingests/services/IngestStatesTest.scala
First part of https://github.com/wellcometrust/platform/issues/3770, spun out of #280.
This adds `version` to the internal `Ingest` model, and a new update type `IngestVersionUpdate` that passes the version from the bag auditor to the ingests monitor.
> Track the ingest version internally

- build.sbt
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/IngestGenerators.scala
- notifier/src/main/scala/uk/ac/wellcome/platform/archive/notifier/services/CallbackUrlService.scala
- notifier/src/test/scala/uk/ac/wellcome/platform/archive/notifier/NotifierFeatureTest.scala
- notifier/src/test/scala/uk/ac/wellcome/platform/archive/notifier/services/CallbackUrlServiceTest.scala
- project/Dependencies.scala
Spotted while working on https://github.com/wellcometrust/platform/issues/3770, pulled out of #280.
The notifier should now send the same output as the ingests service – no nulls for missing entries! Plus stricter tests for the exact JSON output we expect.
Assumes #282, so that will need to be merged first.
> Don't send nulls in the notifier callbacks

- common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/services/BagMatcher.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/services/BagMatcherTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/services/BagVerifiableTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestServiceTest.scala
Previously:
> Fetch entry refers to a path that isn't in the bag: BagFetchEntry(s3://wellcomecollection-storage-archive/digitised/b12956156/v1/data/objects/RAMC_262_10_0008.jp2,None,data/objects/RAMC_262_10_0008.jp2)
Now:
> Fetch entry refers to a path that isn't in the bag manifest: data/objects/RAMC_262_10_0008.jp2
This confused at least one person (see [discussion in #intranda](https://wellcome.slack.com/archives/C6LLC2V8Q/p1564407567008800)), so make the message clearer about the fact that it’s the bag *manifest* where the file is missing, not the bag itself.
> Improve the verifier message for dangling fetch entries

- api/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/IngestsApiFeatureTest.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/DisplayBag.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/DisplayBagInfo.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/DisplayIngest.scala
- notifier/src/test/scala/uk/ac/wellcome/platform/archive/notifier/NotifierFeatureTest.scala
- notifier/src/test/scala/uk/ac/wellcome/platform/archive/notifier/services/CallbackUrlServiceTest.scala
If we've stored an internal version on the `Ingest`, expose it externally in the ingests API and the callbacks.
Plus a small tidy up in the ingests API tests.
Closes #280. Closes https://github.com/wellcometrust/platform/issues/3770.
> Send a version in callback requests

- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifier.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/BagBuilderBase.scala
Currently it gives a less than helpful message:
> Bag contains a file which is not referenced in the manifest: myfile.jpg
Now it explains it a bit better:
> Files referred to in the fetch.txt also appear in the bag: myfile.jpg
A concrete file or a remote location – pick one!
Closes wellcometrust/platform#3776, replaces #288.
> Supply a better message if a user sends a fetch.txt entry *and* a file

- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifier.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierTest.scala
Previously it'd say something like:
> There was 1 error verifying the bag
Now it says:
> Unable to verify one file in the bag: fetch.txt
This makes it easier for end-users to debug issues with their bags, especially in manual testing.
> Include the name of bad files in the verifier output

- api/bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/models/DisplayFile.scala
- bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/Main.scala
- bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/services/Register.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/fixtures/BagRegisterFixtures.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/models/StorageManifest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/SizeFinder.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestService.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/BagFileGenerators.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/StorageManifestGenerators.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/SizeFinderTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestServiceTest.scala
- display/src/test/scala/uk/ac/wellcome/platform/archive/display/fixtures/DisplayJsonHelpers.scala
Closes https://github.com/wellcometrust/platform/issues/3790
The bag register will now read all the sizes of objects in a bag (either from the fetch.txt or from S3), and then include those in the StorageManifest it saves to S3.
> Collect the sizes in StorageManifestService

- makefiles/functions.Makefile
Longer term, we should really do this better:
* Make is getting really creaky; I'd rather push it into a series of versioned and tested Python scripts
* Maybe the Travis user should use roles? But they're not an SSO user, so it's less pressing
Anyway, this should unblock the Travis publishing. 🤞
> Fix publishing from Travis

- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/SizeFinder.scala
This quickly exhausts the pool of available HTTP connections, and causes the register to fail.
Closes https://github.com/wellcometrust/platform/issues/3800
> Don't open an InputStream just to get the size of an object

- terraform/stack/dynamo.tf
- terraform/stack/iam_role_policy.tf
- terraform/stack/locals.tf
- terraform/stack/main.tf
- terraform/stack/messaging.tf
- terraform/stack/release_uris.tf
Plus the message you get for the event is now:
"Starting assigning bag version" or "Succeeded assigning bag version".
Closes https://github.com/wellcometrust/platform/issues/3689
> Rename "bag_auditor" to "bag_versioner" in the infra

- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/Main.scala
- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicator.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/fixtures/BagReplicatorFixtures.scala
- ingests_common/src/test/scala/uk/ac/wellcome/platform/archive/common/ingests/tracker/dynamo/DynamoIngestTrackerTest.scala
- project/Dependencies.scala
This means we don't leave InputStreams open in the replicator, which means drops lots of warnings in the tests and means the replicator might start getting "HTTP connection pool exhausted" errors if under load.
Closes https://github.com/wellcometrust/platform/issues/3742
> Make sure we close S3InputStreams correctly in the replicator

- bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/services/Register.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorkerTest.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/RegisterTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestService.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestServiceTest.scala
Closes https://github.com/wellcometrust/platform/issues/3778
Now, if you send a bag with a `fetch.txt` that points to an object in the wrong bucket/storage space/external identifier, you get a more helpful error:
> Register failed - Fetch entry for data/objects/RAMC_262_10_0008.jp2 refers to a file in the wrong namespace: wrong-bukkit
This has been the source of most of my register failures over the last few days, and I don't want to keep looking at the CloudWatch logs!
> If the fetch.txt in a bag register update is wrong, tell the user

- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/Unpacker.scala
- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/memory/MemoryUnpacker.scala
- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/s3/S3Unpacker.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/BagUnpackerWorkerTest.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/UnpackerTestCases.scala
Now, when we send an error message about a location, we'll give a bit
more context about where we were looking.
e.g. rather than saying
> Error trying to unpack the archive at bukkit/key.tar.gz
the user-facing message would say something like:
> Error trying to unpack the archive at mem://bukkit/key.tar.gz
> Error trying to unpack the archive at s3://bukkit/key.tar.gz
> Error trying to unpack the archive at azure://bukkit/key.tar.gz
Tiny fix I spotted after retrying Helen's failed ingest from yesterday; in most places we add the `s3://` prefix but in the archive errors we don't.
> Add formatting helpers for the ObjectLocation in the unpacker

- bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/models/RegistrationSummary.scala
- bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorker.scala
- bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/services/Register.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/RegisterTest.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/models/VerificationSummary.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifier.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierWorker.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/services/BagReader.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestService.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/services/BagReaderTestCases.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestServiceTest.scala
Spun out of #322 as a small, manageable piece – just the BagReader class, plus some of the verifier and bag register. More bits will follow.
> Start disambiguating between ObjectLocation and ObjectLocationPrefix

- common/src/main/scala/uk/ac/wellcome/platform/archive/common/http/WellcomeExceptionHandler.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/http/WellcomeHttpApp.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/http/WellcomeRejectionHandler.scala
Make the `WellcomeHttpApp` code a bit clearer, by some simple refactoring and extraction of exception/rejection handling.
> Split rejection/exception handlers, clarify http app flow

- api/bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/models/ResponseDisplayBag.scala
- api/bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/BagsApiFeatureTest.scala
- api/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/IngestsApiFeatureTest.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/BagRegisterFeatureTest.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorkerTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/ingests/models/Ingest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/ingests/models/SourceLocation.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/ingests/models/StorageProvider.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/models/BetterStorageLocation.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/models/StorageLocation.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/models/StorageManifest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestService.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/SourceLocationPayloadTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/IngestGenerators.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/StorageManifestGenerators.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestServiceTest.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/DisplayIngest.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/DisplayLocation.scala
- display/src/test/scala/uk/ac/wellcome/platform/archive/display/DisplayIngestTest.scala
- display/src/test/scala/uk/ac/wellcome/platform/archive/display/fixtures/DisplayJsonHelpers.scala
- replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/models/ReplicaResult.scala
- replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregator.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/ReplicaAggregatorFeatureTest.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorTest.scala
Closes https://github.com/wellcometrust/platform/issues/3833 by changing the API output to the new format.
Additionally:
* Some refactoring so that StorageManifest supports multiple locations (this will break all the existing manifests)
* Create a new type `SourceLocation` which replaces the old `StorageLocation`, and rename `BetterStorageLocation` to plain `StorageLocation`
> Change the StorageManifest model to support multiple locations

- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/BagRegisterFeatureTest.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorkerTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/models/StorageLocation.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestService.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/StorageManifestGenerators.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestServiceTest.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/DisplayLocation.scala
- display/src/test/scala/uk/ac/wellcome/platform/archive/display/fixtures/DisplayJsonHelpers.scala
- replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/models/ReplicaResult.scala
- replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregator.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/ReplicaAggregatorFeatureTest.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorTest.scala
Because these don't refer to an object in S3, just a directory under which you can find a pile of objects.
> Use ObjectLocationPrefix instead of ObjectLocation in StorageLocation

- replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/Main.scala
- replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/models/AggregatorInternalRecord.scala
- replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/models/KnownReplicas.scala
- replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/models/ReplicaResult.scala
- replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/models/ReplicationAggregationSummary.scala
- replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregator.scala
- replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorWorker.scala
- replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaCounter.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/fixtures/ReplicaAggregatorFixtures.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/generators/StorageLocationGenerators.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/models/AggregatorInternalRecordTest.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorTest.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorWorkerTest.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaCounterTest.scala
This patch adds a new class `ReplicaCounter`, which counts the number of replicas to see how many there actually are vs. how many it expects.
If there are enough, it sends a ReplicationCompleteSummary and the payload is forwarded to the register; if not, it marks it as incomplete and just sends an ingests update.
Part of https://github.com/wellcometrust/platform/issues/3836
> Aggregator: are these enough replicas?

- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestService.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/StorageRandomThings.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/StorageLocationGenerators.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestServiceTest.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/models/AggregatorInternalRecordTest.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorTest.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaCounterTest.scala
The API for StorageManifestService is now:
```scala
def createManifest(
bag: Bag,
location: PrimaryStorageLocation,
replicas: Seq[SecondaryStorageLocation],
space: StorageSpace,
version: BagVersion
): Try[StorageManifest]
```
and if you pass any replicas, their path is correctly checked and updated to the non-versioned value (e.g. if the path is `digitised/b1234/v1`, the *bag path* is `digitised/b1234`, so all file paths including fetch entries can be relative to this path).
Plus EVEN MOAR TESTS.
Part of https://github.com/wellcometrust/platform/issues/3845
I haven’t applied this to the register yet, because this was fiddly enough on its own – the old API still exists and has the same behaviour, and I’ll swap it out in a separate patch (plus bag register tests!).
> StorageManifestService can store replicas correctly

- .travis.yml
There is such build contention in Travis, let's save ten minutes of build time a pop on two tasks that almost never change.
> Comment out two tasks in the Travis build matrix

- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/s3/S3UnpackerTest.scala
If it happened to create a valid S3 bucket name, the exception message wouldn't match, and the test would fail.
It’s just failed on master: https://travis-ci.org/wellcometrust/storage-service/jobs/574958614
> Stop this bag unpacker test from being flaky

- replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/models/AggregatorInternalRecord.scala
- replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorWorker.scala
- replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaCounter.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/ReplicaAggregatorFeatureTest.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorWorkerTest.scala
Because the aggregator runs multiple times, it now includes a bit of context in the ingests monitor message, e.g.
> Aggregating replicas succeeded - 1 of 3 replicas complete
or
> Aggregating replicas succeeded - all replicas complete
Spun out as a separate piece from https://github.com/wellcometrust/storage-service/pull/352
> Include more context in the aggregator messages

- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorker.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorkerTest.scala
If you lock around the ingest ID, the Glacier and IA replications can't run simultaneously, and there's a 5-hour timeout on the queue. >.<
If you're writing to different destinations, it's fine to run replications concurrently. Desirable, even!
Discovered in #352.
> Lock the replicator around the destination, not the ingest ID

- api/bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/Main.scala
- api/bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/fixtures/BagsApiFixture.scala
- api/ingests_api/src/main/scala/uk/ac/wellcome/platform/storage/ingests/api/Main.scala
- api/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/fixtures/IngestsApiFixture.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/http/WellcomeHttpApp.scala
Log request/response cycle in API apps.
**Note:** this is not an access log and does not follow the [Common Log Format](https://en.wikipedia.org/wiki/Common_Log_Format), it instead uses the Akka HTTP `logRequestResult` default which is much more verbose, e.g.
```
[INFO] [08/23/2019 10:23:41.525] [default-akka.actor.default-dispatcher-3] [akka.actor.ActorSystemImpl(default)] BagsApiFixture/8204df7a-b0f2-49fa-8c67-536fd4d47da4: Response for
Request : HttpRequest(HttpMethod(GET),http://localhost:1234/bags/FSb2L4jQ/O84bmz6a?version=v2,List(Host: localhost:1234, User-Agent: akka-http/10.1.5, Timeout-Access: <function1>),HttpEntity.Strict(none/none,ByteString()),HttpProtocol(HTTP/1.1))
Response: Complete(HttpResponse(200 OK,List(),HttpEntity.Strict(application/json,{"@context":"http://api.wellco …
```
> Ensure API logs are written for requests

- terraform/modules/queue/variables.tf
- terraform/modules/stack/replicator_verifier_pair/messaging.tf
This means we won't lose messages if a task gets scaled away midway through processing a message.
> Bump the max receive count on the verifier queues

- bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/services/Register.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/models/StorageManifest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestService.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/StorageManifestGenerators.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestServiceTest.scala
- scripts/ss_report_stats.py
So we can identify to which ingest a manifest relates.
More specifically this will allow us to identify duplicate messages received by the register.
**Note:** This will require us to truncate what the storage service knows about already as it changes the internal model.
> Add IngestId to StorageManifest

- scripts/.gitignore
- scripts/compare_uat_and_prod.py
Walk the entire IIIF manifest, checking that every value is either identical, or points to equivalent data (“equivalent” for images = “visually similar”).
DLCS is having a bit of trouble right now because we've knocked out the storage service from underneath it (oops), so a bunch of HTTP requests 500 out right now.
Output is something like:
```
[label]: [Report 1964] / != [Report 1964]
Error trying to retrieve https://dlcs.io/iiif-img/wellcome/5/b30145004_0001.jp2
[sequences][0][canvases][0][images][0][resource][service][@id]: https://dlcs.io/iiif-img/wellcome/5/b30145004_0001.jp2 != https://dlcs.io/iiif-img/wellcome/1/a968db42-c1b9-45ba-91ed-5f89126a084a
Error trying to retrieve https://dlcs.io/thumbs/wellcome/5/b30145004_0001.jp2
[sequences][0][canvases][0][thumbnail][service][@id]: …
```
> First pass at script to compare UAT and prod

- api/bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/BagsApi.scala
- api/bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/BagsApiFeatureTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/models/StorageManifest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/S3Uploader.scala
In order to properly respond to requests for storage manifests exceeding the 10MB API Gateway limit we need to utilise the upcoming large response logic (https://github.com/wellcometrust/storage-service/pull/382). 
For that we will need a unique ETag in order to allow proper caching (in S3 of large responses).
For https://github.com/wellcometrust/platform/issues/3937
> Add ETag to Bag API responses

- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/LargeResponses.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/LargeResponsesTest.scala
Allows routes providing responses in excess of a given byte length to store those responses in S3 and provide redirection to a signed S3 URL.
For wellcometrust/platform#3937
> Adds LargeResponses trait

- project/Dependencies.scala
Incorporate RetryableError when VersionAlreadyExistsError to eliminate errors when aggregating replicas in the replica_aggregator.
See https://github.com/wellcometrust/scala-storage/blob/master/CHANGELOG.md
> Update scala-storage to 7.24.3

- terraform/modules/stack/messaging.tf
If we deploy a new version of a service, ECS stops any instances of the old service.  This means we lose any work that was in-flight.
If the SQS queue has retries >1, the message will eventually be retried (albeit after a delay, from the queue visibility timeout).  If we don't have retries, the message will get dropped and not retried, and the ingest will be eternally processing.
> Always have at least 3 retries on every queue

- bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/Main.scala
- bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/services/Register.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorkerTest.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifier.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/models/UnreferencedFiles.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/SizeFinder.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestService.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/TagManifestFileFinder.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/StorageRandomThings.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestServiceTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/TagManifestFileFinderTest.scala
Code fix for https://github.com/wellcometrust/platform/issues/4012
This will ensure that all new bags we register get a `tagmanifest-sha256.txt` entry in the `tagManifest` field of the storage service manifest, where previously they didn't.
Backfilling old bags will be handled separately.
(Too many manifests!)
> Include tagmanifest-sha256.txt in the storage manifests created in the bag register

- terraform/modules/critical/s3_replica_glacier.tf
This is cheaper, with the downsides that it's slower to retrieve and the minimum storage time is longer.  Neither of these are an issue for us!
This change is already applied.
Closes https://github.com/wellcometrust/platform/issues/4013
> Use DEEP_ARCHIVE storage class for the Glacier replica

- .travis/run_job.py
- python_client/CHANGELOG.md
- python_client/src/wellcome_storage_service/downloader.py
- python_client/src/wellcome_storage_service/version.py
- python_client/tests/cassettes/test_downloading_compressed_bag.json
- python_client/tests/test_downloader.py
Closes https://github.com/wellcometrust/platform/issues/4007, closes https://github.com/wellcometrust/platform/issues/4008
I don't think we need to create directory entries explicitly; I think `tarfile.addfile()` does it implicitly. We'll find out when we deploy it!
For https://github.com/wellcometrust/platform/issues/4004
> Compress a downloaded bag under a single directory, add modified dates

- python_client/CHANGELOG.md
- python_client/src/wellcome_storage_service/downloader.py
- python_client/src/wellcome_storage_service/version.py
- python_client/tests/cassettes/test_downloading_compressed_bag_gets_dir_entries.json
- python_client/tests/test_downloader.py
For https://github.com/wellcometrust/platform/issues/4004
I hadn't realised lsar was being used inside Archivematica, or I'd have paid more attention to this the first time round – handily we can simplify this code *and* get directory entries for free.
> Ensure a compressed bag download includes directory entries

- .travis/run_job.py
- Makefile
- nginx/Dockerfile
- nginx/Makefile
- nginx/nginx.conf
- terraform/infra/ecr.tf
- terraform/modules/queue/main.tf
- terraform/modules/resource/main.tf
- terraform/modules/resource/outputs.tf
- terraform/modules/service/api/main.tf
- terraform/modules/service/scaling_worker/main.tf
- terraform/modules/service/worker/main.tf
- terraform/modules/stack/images.tf
- terraform/modules/stack/locals.tf
- terraform/modules/topic/main.tf
- terraform/modules/topic/outputs.tf
- terraform/stack_prod/locals.tf
The storage service was pulling in an nginx image from the catalogue account, so when the permissions on that ECR repo changed, we could no longer start tasks using that image.
The bags API fell over this morning (out-of-memory from requesting a really big bag), so this PR brings a copy of the nginx image into this repo, and uses this in the tasks.
> Use nginx defined in the storage service

- replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorWorker.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorWorkerTest.scala
This is caused by a subtle mismatch between the behaviour of the VersionedStore type class and the aggregator.
When the VersionedStore sees a retryable error in update() or upsert(), it wraps the underlying error as:
new UpdateWriteError(err) with RetryableError
But the aggregator code was pattern matching on a different expression:
case UpdateWriteError(err: RetryableError)
These aren't the same thing, and the mismatch meant these errors were still slipping through.  This should fix this source of flakiness in the replica aggregator.
See: https://github.com/wellcometrust/scala-storage/blob/95626ad8570a322421fcfd58e98bd50ed8016798/storage/src/main/scala/uk/ac/wellcome/storage/store/VersionedStore.scala#L41-L44
Closes https://github.com/wellcometrust/platform/issues/4074
> Fix an aggregator bug that meant retryable errors were being ignored

- python_client/src/wellcome_storage_service/downloader.py
- python_client/tests/cassettes/test_downloading_compressed_bag_with_custom_directory.json
- python_client/tests/test_downloader.py
If omitted, the external identifier string is used as a top level directory name, as is the current behaviour.
Fixes https://github.com/wellcometrust/platform/issues/4071
> Allow top level dir to be specified for compressed bag download

- api/ingests_api/src/main/scala/uk/ac/wellcome/platform/storage/ingests/api/IngestsApi.scala
- api/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/IngestsApiFeatureTest.scala
Supporting slashes adds a bunch of edge cases and weirdnesses that we'd need to check (e.g. around S3 paths and URL path components). If we had time to test it thoroughly, we could do it, but for now reject any ingest that tries to use "a/b" or "b/c" as a space or external ID.
---
Prompted by thinking about Archivematica, where the Calm IDs do contain slashes (but there's no way we want to pass those through).
The Archivematica side should never be sending them; to be on the safe side the storage service will reject them if it does.
> Don't allow slashes in the storage service

- api/bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/BagsApiFeatureTest.scala
Arose from an experiment for https://github.com/wellcometrust/platform/issues/4088
This doesn't change any behaviour, just simplifies some of the test code, and makes it easier to add more tests later. At some point we'll be adding support for external identifiers with slashes, at which case we'll need more tests!
> Simplify the bags API tests

- api/bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/BagsApi.scala
- api/bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/LookupBagApiTest.scala
- api/bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/LookupBagVersionsApiTest.scala
Part of https://github.com/wellcometrust/platform/issues/4088
This works whether or not you URL encode the slash. Example:
```
GET /bags/space-id/alfa/bravo
GET /bags/space-id/alfa%2Fbravo
GET /bags/space-id/alfa/bravo/versions
GET /bags/space-id/alfa%2Fbravo/versions
```
If you're feeling perverse and your ID is `alfa/versions`, it also (mostly) works:
```
GET /bags/space-id/alfa%2Fversions
GET /bags/space-id/alfa/versions/versions
GET /bags/space-id/alfa%2Fversions/versions
```
Do not do this. It is silly.
> Add tests and support for looking up external IDs with slashes

- terraform/modules/service/scaling_worker/main.tf
- terraform/modules/stack/main.tf
- terraform/modules/stack/variables.tf
- terraform/stack_prod/main.tf
- terraform/stack_staging/main.tf
Most of the time the storage service isn't doing anything, but we have Fargate instances running anyway. This is just burning money – allowing it to scale to 0 will save us ~$1200/month.
Applying this config showed up a bug in autoscaling setup – despite it being configured in Terraform, the notifier and ingests monitor both had broken autoscaling, so they'd never run anything except 1 instance.
Closes https://github.com/wellcometrust/platform/issues/4014. I did try writing a script to automate warming the pipeline, but let's see if we need it first.
> Allow the storage service to scale to 0 when not running

- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/DestinationBuilder.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/DestinationBuilderTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/models/ExternalIdentifier.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/models/StorageSpace.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/models/ExternalIdentifierTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/LargeResponsesTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/models/StorageSpaceTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestServiceTest.scala
- ingests_common/src/test/scala/uk/ac/wellcome/platform/archive/common/ingests/tracker/dynamo/DynamoIngestTrackerTest.scala
If you try to create a:
* Storage space with a slash (e.g. `alfa/bravo`)
* An empty storage space `StorageSpace("")`
* An empty external identifier `ExternalIdentifier("")`
You hit these new runtime assertions. In practice, you should never hit these unless you're doing something very silly – but for https://github.com/wellcometrust/platform/issues/4088 in particular, we're going to have to assume spaces can't contain slashes, and it's better to encode that in the type system than assuming it won't happen.
This allows us to unambiguously distinguish the storage space/external identifier in a bag ID.
e.g. if you look at bag ID `alfa/bravo/charlie`, the space is `alfa` and the external ID is `bravo/Charlie`.
> Improve validation of StorageSpace and ExternalIdentifier

- api/ingests_api/src/main/scala/uk/ac/wellcome/platform/storage/ingests/api/responses/CreateIngest.scala
- api/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/CreateIngestApiTest.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/DisplayBagInfo.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/DisplayIngest.scala
- display/src/test/scala/uk/ac/wellcome/platform/archive/display/DisplayIngestTest.scala
Also add tests around validation for non-empty space/external ID. The new runtime assertions would have caught these, but with less nice error reporting back to the user.
For https://github.com/wellcometrust/platform/issues/4088
> Allow sending slashes in the external identifier

- api/bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/LookupBagApiTest.scala
- api/bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/LookupBagVersionsApiTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/models/ExternalIdentifier.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/models/ExternalIdentifierTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/models/StorageSpaceTest.scala
Since we're now doing validation of these strings, cover a couple of edge cases that would cause annoyance if you put them in the storage service.  In particular:
*   Don't allow slashes in a place that would cause double slashes in the S3 key (because that causes weirdness in the S3 Console, which is how a lot of people will browse the storage)
*   Don't allow an identifier to end with `/versions` (because that conflicts with the bags API endpoint)
*   Don't allow an identifier to include `/v1`, `/v2`, `/v3`, ... (because that makes the S3 bucket harder to navigate)
The storage service itself will cope fine with any of these things, but they'll cause confusion for the humans who have to use it!
If we find we actually need identifiers that look like this, we can consider removing them, …
> Add more restrictions on external identifier and storage space

- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/s3/S3Replicator.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/s3/S3ReplicatorTest.scala
- project/Dependencies.scala
Right now we store everything as Standard, which is unnecessarily expensive. The Glacier replica will get life-cycled out of Standard-IA to Glacier-DeepArchive eventually; the warm replica will remain IA.
For https://github.com/wellcometrust/platform/issues/4096
> Store the replicas as Standard-IA

- terraform/modules/critical/s3_replica_primary.tf
This migrates the existing warm replica to Standard-IA, for https://github.com/wellcometrust/platform/issues/4096
At some point, when all the existing objects are Standard-IA, we can come back and remove this rule.
> Get S3 to lifecycle objects to Standard-IA

- bag_unpacker/src/main/resources/application.conf
- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/builders/BagLocationBuilder.scala
- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/config/builders/UnpackerWorkerConfigBuilder.scala
- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/config/models/BagUnpackerWorkerConfig.scala
We don't use it at all – we write unpacked bags into a dedicated bucket, so prefixing all the paths with "unpacked" doesn't add much. This patch will unpack into the root of the bucket.
Additionally, we didn't have any tests that check we were appending that prefix!
> Remove the destination prefix from the bag unpacker

- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/Unpacker.scala
Debugging via Twitter: https://twitter.com/alexwlchan/status/1220075920284946444
I joked about seeing a message from this particular bug on Twitter, then went to have another look at the code.  Spotted it instantly, where previously it was totally invisible.
Closes #3947.
> Fix an overflow bug when reporting the # of bytes unpacked

- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/models/UnpackSummary.scala
- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/Unpacker.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/UnpackerFeatureTest.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/BagUnpackerWorkerTest.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/UnpackerTestCases.scala
Saying "unpacked 5 MB" is more pleasant than saying "unpacked 5000000 bytes". This message is only for human consumption and you can get the exact byte sizes from the storage manifest, so might as well make it friendly.
A quick improvement spotted while working on #432.
> Write a human-readable file size in the bag unpacker messages

- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/Unpacker.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/UnpackerTestCases.scala
```
Before:  Unpacked 7 GB from 49684 files
After:   Unpacked 7 GB from 49,684 files
```
Just to make it a bit easier for humans to read.
> Format the file count in unpacker messages with a comma

- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestDao.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestDaoTestCases.scala
This is a more efficient lookup than calling listVersions() or getLatest(), because it only has to look in the DynamoDB table, and it doesn't serialise the full storage manifest out of S3.
This is preliminary work for a change to the bags API to allow us to get cached responses from an S3 bucket, rather than fetching a complete response every time.
Another piece spun out of #436.
> Allow getting the latest BagVersion from the storage manifest dao

- api/bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/BagsApi.scala
- api/bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/Main.scala
- api/bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/responses/LookupBag.scala
- api/bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/LookupBagApiTest.scala
- api/bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/fixtures/BagsApiFixture.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/S3ObjectExists.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/S3Uploader.scala
Tentative fix for https://github.com/wellcometrust/platform/issues/4024
Not being able to get some bags out of the API (Chemist & Druggist in particular) has been a source of issues while cleaning up the DDS file shares (because I can't see what's inside the bag!). This patch is an attempt to fix that.
When you request a bag, we check the large response cache, and if a response has already been stored, we pull it straight from the cache. I've added a new "getLatestVersion" method to the storage manifest dao, so we can also do this if you look up the latest version of the bag.
I had to do some fairly major rewiring of the bags API internals to make this work – in particular, the LookupBag trait now assumes you know what the version is already, and working out what the latest version is …
> Check the cache before returning a really large bag

- scripts/verify_digitised_bag_references.py
Output of https://github.com/wellcomecollection/platform/issues/4289
We can validate the METS/ALTO files in a bag have broadly correct references.
> Add a script for validating digitised bags

- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/s3/S3Unpacker.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/s3/S3UnpackerTest.scala
It might be that we have GetObject permission in that bucket, but it doesn't exist and S3 won't give us the more specific error.  This is an error that the user can fix themselves, but only if they know it might be permissions *or* a non-existent object.
The easy bit of https://github.com/wellcomecollection/platform/issues/4310
> Produce a more helpful error message upon "Access Denied"

- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/s3/S3StreamReader.scala
- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/s3/S3Unpacker.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/s3/S3StreamReaderTest.scala
- build.sbt
- project/Dependencies.scala
Because we were making a ranged GET request, S3 would report the content length of every file as 1.  That would cause the reader to read straight to the end, even if it was an enormous thing, and buffer the entire object in memory.
Using .abort() and not a ranged GET avoids this issue *and* means we don't get the warning about "not all bytes read from the stream".
Closes https://github.com/wellcomecollection/platform/issues/4326
> Fix OOM issues in the bag unpacker

- scripts/find_inflight_ingests.py
When I first wrote this code, I stuck in a tqdm progress meter because it took so long to run. But ugh, who wants to wait?
This patch rips out the progress meter because using concurrent.futures makes it go super speedy nimble quick. 6x faster on my machine, and fast enough not to care about progress.
> Use concurrent.futures to speed up finding inflight ingests

- terraform/modules/service/api/main.tf
- terraform/modules/service/api/variables.tf
- terraform/modules/service/scaling_worker/main.tf
- terraform/modules/service/scaling_worker/variables.tf
- terraform/modules/service/worker/main.tf
- terraform/modules/service/worker/variables.tf
- terraform/modules/stack/api/main.tf
- terraform/modules/stack/api/services/bags.tf
- terraform/modules/stack/api/services/ingests.tf
- terraform/modules/stack/api/services/variables.tf
- terraform/modules/stack/api/variables.tf
- terraform/modules/stack/main.tf
- terraform/modules/stack/variables.tf
- terraform/stack_prod/provider.tf
- terraform/stack_staging/main.tf
- terraform/stack_staging/provider.tf
This patch uses https://github.com/wellcomecollection/terraform-aws-ecs-service/pull/6 to use Fargate Spot in some of the storage service apps, specifically:
* the bag root finder
* the bag versioner
* the replica aggregator
* the bag register
* the notifier
* the ingests monitor
because all these tasks are SQS-backed and can be interrupted at short notice. The unpacker, verifier and replicator all stay as they are.
It also turns on spot for the APIs **in the staging service only**, on the basis that it's an easy cost win for something where we don't need 100% uptime.
Still needs to be rolled out to prod, which turns out to be a bit more delicate if we want to avoid downtime.
> Use Fargate Spot for the storage service

- notifier/src/main/scala/uk/ac/wellcome/platform/archive/notifier/services/PrepareNotificationService.scala
- notifier/src/test/scala/uk/ac/wellcome/platform/archive/notifier/NotifierFeatureTest.scala
- notifier/src/test/scala/uk/ac/wellcome/platform/archive/notifier/services/PrepareNotificationServiceTest.scala
It's the only message sent to the ingests monitor that has a full stop, and the inconsistency annoys me.
Closes https://github.com/wellcomecollection/platform/issues/4270
> Remove the full stop from the sentence "Callback fulfilled."

- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/s3/S3Replicator.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/s3/S3ReplicatorTest.scala
- terraform/modules/critical/s3_replica_primary.tf
Closes https://github.com/wellcomecollection/platform/issues/4096
I realised this was an issue when trying to work out why we had objects that hadn't been lifecycled to Standard-IA, and it's because S3 won't lifecycle objects that are below the Standard-IA billing threshold (128KB). Small files like the tag manifest and bag-info.txt are cheaper to store as Standard than Standard-IA.
Rather than write everything as Standard-IA, we write everything as Standard and let S3 lifecycle rules choose what's appropriate to cycle away to Standard-IA.
Any bags written since I did this original patch will have some objects that are Standard-IA which would be cheaper as Standard, but it's a small enough number that I don't think it's worth going and moving those objects back to Standard – but while I'm …
> Write new bags as Standard, let S3 lifecycle applicable objects to Standard-IA

- common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/models/UnreferencedFiles.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/TagManifestFileFinder.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/verify/Checksum.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/verify/Hasher.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/verify/HashingAlgorithm.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/verify/HasherTest.scala
This lays some early groundwork for https://github.com/wellcomecollection/platform/issues/4277, which I'd like to see done sooner rather than later
In particular, when we read a file out of S3, we create MD5/SHA1/SHA256/SHA512 checksums all in one go, rather than having to read it four times.
Right now we don't use the extra values anywhere, but later we can read the other manifests, and start comparing the checksums they contain from the values we get from S3.
> When we read a stream, hash it with all four BagIt checksum algorithms

- bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/Main.scala
Tiny fixup I spotted while staring at this code.
> Improve the variable naming in bag_register.Main

- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/fixtures/BagRegisterFixtures.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/ingests/models/Ingest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/ingests/services/IngestUpdater.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/ingests/services/IngestUpdaterTest.scala
- ingests/src/main/scala/uk/ac/wellcome/platform/archive/ingests/services/CallbackNotificationService.scala
- ingests/src/test/scala/uk/ac/wellcome/platform/archive/ingests/IngestsFeatureTest.scala
- ingests/src/test/scala/uk/ac/wellcome/platform/archive/ingests/services/CallbackNotificationServiceTest.scala
- ingests/src/test/scala/uk/ac/wellcome/platform/archive/ingests/services/IngestsWorkerServiceTest.scala
- ingests_common/src/main/scala/uk/ac/wellcome/platform/archive/common/ingests/tracker/IngestStates.scala
- ingests_common/src/test/scala/uk/ac/wellcome/platform/archive/common/ingests/tracker/IngestStatesTest.scala
- ingests_common/src/test/scala/uk/ac/wellcome/platform/archive/common/ingests/tracker/IngestTrackerTestCases.scala
Make the internal names better reflect how they're described externally; introduce an Ingest.Completed type so downstream code has a bit less coupling to what the exact statuses are.
> Slight rejigging of Ingest.Status types

- ingests/src/main/resources/application.conf
- ingests/src/main/scala/uk/ac/wellcome/platform/archive/ingests/Main.scala
- ingests/src/main/scala/uk/ac/wellcome/platform/archive/ingests/services/IngestsWorker.scala
- ingests/src/test/scala/uk/ac/wellcome/platform/archive/ingests/IngestsFeatureTest.scala
- ingests/src/test/scala/uk/ac/wellcome/platform/archive/ingests/fixtures/IngestsFixtures.scala
- ingests/src/test/scala/uk/ac/wellcome/platform/archive/ingests/services/IngestsWorkerServiceTest.scala
- terraform/modules/stack/main.tf
- terraform/modules/stack/messaging.tf
Follows https://github.com/wellcomecollection/storage-service/pull/473. First step of https://github.com/wellcomecollection/platform/issues/4417.
This patch modifies the ingests service to send the complete ingest to SNS every time it gets an update. It also includes the Terraform wiring, and a queue so we can see if it’s doing so successfully.
> The ingests monitor sends the full body of updated ingests

- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/UnpackerFeatureTest.scala
This caused a failure in a recent Travis run.  Because SQS sends messages at least once, sometimes it sends them twice, and then `getMessages()` returns two duplicate messages.  Adding `.distinct` should stop this test from being flaky.
See https://travis-ci.org/github/wellcomecollection/storage-service/jobs/672406335
> Allow for double-sending of messages in the bag unpacker tests

- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/StorageRandomThings.scala
- indexer/common/src/main/scala/uk/ac/wellcome/platform/archive/indexer/elasticsearch/Indexer.scala
- indexer/ingests_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/ingests/IngestIndexer.scala
- indexer/ingests_indexer/src/test/scala/uk/ac/wellcome/platform/archive/indexer/ingests/IngestIndexerTest.scala
We want we only put the newest version of an Ingest in Elasticsearch.
The Ingest model doesn't have a version, but it does have a modified date (the latest event it received), or the created date as a fallback. Use that field as the version in Elasticsearch to ensure updates are ordered correctly.
Useful links:
* The Ingest model. https://github.com/wellcomecollection/storage-service/blob/master/common/src/main/scala/uk/ac/wellcome/platform/archive/common/ingests/models/Ingest.scala
* The Indexer class in the catalogue that this code is based on: https://github.com/wellcomecollection/catalogue/blob/master/pipeline/ingestor/ingestor_common/src/main/scala/uk/ac/wellcome/platform/ingestor/common/Indexer.scala
Note: in the catalogue we index the internal model and then convert it to a display …
> Ensure ingest updates are ordered

- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/BagVerifierFeatureTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/verify/Checksum.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/BagBuilderBase.scala
This was an absolute pain to figure out -- a test that fails sometimes (and has been doing so since *October*), but with no apparent error or reason.
When I finally sat down to look at it more carefully, I found some suspicious clues:
-   I saw the bag starting to verify multiple times, and multiple "Verification started" ingest events being sent.
-   The bag seemed to complete verification successfully; there were no errors complaining about a bad checksum or anything.
-   The comment about payloads being received multiple times should have been more of a hint.
-   The exact assertion that was failing was around the size of the DLQ, not the queue.
So here's the issue:
The size of the bag is randomly chosen at test time, based on a couple of factors:
-   How many payload files are in the …
> Fix a flaky bag verifier test

- indexer/common/src/main/scala/uk/ac/wellcome/platform/archive/indexer/elasticsearch/Indexer.scala
- indexer/ingests_indexer/Dockerfile
- indexer/ingests_indexer/docker-compose.yml
- indexer/ingests_indexer/src/main/resources/application.conf
- indexer/ingests_indexer/src/main/resources/logback.xml
- indexer/ingests_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/ingests/IngestsIndexerWorker.scala
- indexer/ingests_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/ingests/Main.scala
- indexer/ingests_indexer/src/test/scala/uk/ac/wellcome/platform/archive/indexer/ingests/IngestIndexerTest.scala
- indexer/ingests_indexer/src/test/scala/uk/ac/wellcome/platform/archive/indexer/ingests/IngestsIndexerFeatureTest.scala
- indexer/ingests_indexer/src/test/scala/uk/ac/wellcome/platform/archive/indexer/ingests/IngestsIndexerWorkerTest.scala
- indexer/ingests_indexer/src/test/scala/uk/ac/wellcome/platform/archive/indexer/ingests/fixtures/IngestsIndexerFixtures.scala
This allows the ingests indexer to, well, actually index things. Read off an SQS queue and log; there's no onward message here.
> Add a worker for the ingests indexer

- api/bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/responses/LookupBag.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/StorageManifestGenerators.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/manifests/DisplayFile.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/manifests/DisplayFileManifest.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/manifests/DisplayStorageManifest.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/manifests/ResponseDisplayBagInfo.scala
- display/src/test/scala/uk/ac/wellcome/platform/archive/display/manifests/DisplayFileManifestTest.scala
- display/src/test/scala/uk/ac/wellcome/platform/archive/display/manifests/DisplayStorageManifestInfoTest.scala
- indexer/bag_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/bag/ManifestIndexer.scala
- indexer/bag_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/bag/ManifestsIndexConfig.scala
- indexer/bag_indexer/src/test/scala/uk/ac/wellcome/platform/archive/indexer/bag/ManifestIndexerTest.scala
- indexer/common/src/main/scala/uk/ac/wellcome/platform/archive/indexer/elasticsearch/IndexConfig.scala
- indexer/common/src/main/scala/uk/ac/wellcome/platform/archive/indexer/elasticsearch/Indexer.scala
- indexer/common/src/test/scala/uk/ac/wellcome/platform/archive/indexer/IndexerTestCases.scala
- indexer/ingests_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/ingests/IngestsIndexConfig.scala
- indexer/ingests_indexer/src/test/scala/uk/ac/wellcome/platform/archive/indexer/ingests/IngestIndexerTest.scala
Follows #483, the first half of https://github.com/wellcomecollection/platform/issues/4410
This adds code for indexing storage manifests as their display models (without any nested documents). I'll add code for indexing individual files in a separate PR, because I suspect that might need more thought.
> Add a mapping for indexing storage manifests

- api/bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/responses/LookupBag.scala
- api/ingests_api/src/main/scala/uk/ac/wellcome/platform/storage/ingests/api/IngestsApi.scala
- api/ingests_api/src/main/scala/uk/ac/wellcome/platform/storage/ingests/api/responses/CreateIngest.scala
- api/ingests_api/src/main/scala/uk/ac/wellcome/platform/storage/ingests/api/responses/LookupIngest.scala
- api/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/CreateIngestApiTest.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/bags/DisplayFile.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/bags/DisplayFileManifest.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/bags/DisplayStorageManifest.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/bags/ResponseDisplayBagInfo.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/ingests/DisplayBag.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/ingests/DisplayBagInfo.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/ingests/DisplayCallback.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/ingests/DisplayIngest.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/ingests/DisplayIngestEvent.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/ingests/DisplayIngestType.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/ingests/DisplayStatus.scala
- display/src/test/scala/uk/ac/wellcome/platform/archive/display/bags/DisplayFileManifestTest.scala
- display/src/test/scala/uk/ac/wellcome/platform/archive/display/bags/DisplayStorageManifestInfoTest.scala
- display/src/test/scala/uk/ac/wellcome/platform/archive/display/ingests/DisplayIngestTest.scala
- indexer/bag_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/bag/ManifestIndexer.scala
- indexer/bag_indexer/src/test/scala/uk/ac/wellcome/platform/archive/indexer/bag/ManifestIndexerTest.scala
- indexer/ingests_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/ingests/IngestIndexer.scala
- indexer/ingests_indexer/src/test/scala/uk/ac/wellcome/platform/archive/indexer/ingests/IngestIndexerTest.scala
- notifier/src/main/scala/uk/ac/wellcome/platform/archive/notifier/services/CallbackUrlService.scala
Particularly given some of the naming overlaps – e.g. there's a DisplayBagInfo for ingests (how you tell us the external identifier) and for bags (based on the bag-info.txt).
This should make the distinction a little clearer.
> Reorganise the display library to reflect the ingests/bags split

- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/Replicator.scala
- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/s3/S3Replicator.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/bags/BagReplicatorTest.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/s3/S3ReplicatorTest.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorkerTest.scala
- project/Dependencies.scala
This should avoid consistency bugs if we're replicating into a known-empty prefix.
Closes https://github.com/wellcomecollection/platform/issues/3897
> Use the new transfer checks in the bag replicator

- api/ingests_api/src/main/scala/uk/ac/wellcome/platform/storage/ingests/api/responses/CreateIngest.scala
- api/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/CreateIngestApiTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/ingests/models/StorageProvider.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/ingests/models/StorageProviderTest.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/DisplayProvider.scala
- display/src/test/scala/uk/ac/wellcome/platform/archive/display/DisplayProviderTest.scala
- display/src/test/scala/uk/ac/wellcome/platform/archive/display/ingests/DisplayIngestTest.scala
As part of https://github.com/wellcomecollection/platform/issues/4466, we may be changing how the storage providers are defined. (If not there, we'll definitely add some new ones for Azure.)
Right now storage providers are defined in two places: the internal model and the display model. They can get out of sync (and already had – witness the old error message on DisplayProvider), and we don't need the hierarchy to the same degree in the display model – make that a transparent case class, and simplify the code.
> Don't duplicate the StorageProvider hierarchy in DisplayProvider

- ingests_common/src/test/scala/uk/ac/wellcome/platform/archive/common/ingests/tracker/IngestStatesTest.scala
Tiny refactor ahead of maybe changing this behaviour.
Ensure we test the Processing -> Processing transition.
This shouldn't affect the ingests worker stuff; this behaviour is unaffected by any of those changes.
> Make the testing of IngestStates a bit tighter

- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierTest.scala
500 lines of mostly diff churn to refactor ahead of https://github.com/wellcomecollection/platform/issues/4513
A lot of this test code is repeated: set up the bucket, create the bag, get the verification result, see it's an instance of IngestFailed[_]. The "interesting" assertions are harder to see.  Pushing it into a couple of helper methods makes the tests easier to follow.
More practically, we need to modify how the verifier is called for https://github.com/wellcomecollection/platform/issues/4513; specifically to pass the bucket and storage space.  Having the test boilerplate in a helper means less diff churn elsewhere.
> Reduce the boilerplate in BagVerifierTest

- bag_verifier/src/main/resources/application.conf
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/Main.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifier.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierWorker.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/BagVerifierFeatureTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixtures/BagVerifierFixtures.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierWorkerTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/BagBuilderBase.scala
- terraform/modules/stack/main.tf
- terraform/modules/stack/replifier/main.tf
-   They should start with s3://.  We could make this configurable, but hard-coding it for now is sufficient.
-   If a fetch URI doesn't point to something in the primary storage bucket, we should reject it.
-   If a fetch URI doesn't point to a path that starts with {space}/{externalIdentifier}, we should reject it.
Closes https://github.com/wellcomecollection/platform/issues/4513
> Check the structure of fetch URIs in the bag verifier

- ingests_tracker/src/main/scala/uk/ac/wellcome/platform/storage/ingests_tracker/client/IngestTrackerClient.scala
- ingests_tracker/src/main/scala/uk/ac/wellcome/platform/storage/ingests_tracker/client/IngestTrackerError.scala
- ingests_tracker/src/test/scala/uk/ac/wellcome/platform/storage/ingests_tracker/client/IngestTrackerClientTest.scala
- ingests_worker/src/main/scala/uk/ac/wellcome/platform/storage/ingests_worker/services/IngestsWorkerService.scala
- ingests_worker/src/test/scala/uk/ac/wellcome/platform/storage/ingests_worker/fixtures/IngestsWorkerFixtures.scala
Follows https://github.com/wellcomecollection/storage-service/pull/509
Part of modifying the external-facing ingests API to use the ingests tracker (wellcomecollection/platform#4419).
> Add a createIngest() method to the ingest tracker client

- ingests_tracker/src/main/scala/uk/ac/wellcome/platform/storage/ingests_tracker/client/IngestTrackerClient.scala
- ingests_tracker/src/main/scala/uk/ac/wellcome/platform/storage/ingests_tracker/client/IngestTrackerError.scala
- ingests_tracker/src/test/scala/uk/ac/wellcome/platform/storage/ingests_tracker/client/IngestTrackerClientTest.scala
- ingests_worker/src/main/scala/uk/ac/wellcome/platform/storage/ingests_worker/services/IngestsWorkerService.scala
- ingests_worker/src/test/scala/uk/ac/wellcome/platform/storage/ingests_worker/fixtures/IngestsWorkerFixtures.scala
Part of modifying the external-facing ingests API to use the ingests tracker (https://github.com/wellcomecollection/platform/issues/4419).
I tweaked the test cases to make them more generic, and had to rename a few of the existing errors to distinguish between and update/get error.
> Add a getIngest() method to the ingest tracker API

- ingests/ingests_tracker/src/main/scala/uk/ac/wellcome/platform/storage/ingests_tracker/IngestsTrackerApi.scala
- ingests/ingests_tracker/src/main/scala/uk/ac/wellcome/platform/storage/ingests_tracker/Main.scala
- ingests/ingests_tracker/src/test/scala/uk/ac/wellcome/platform/storage/ingests_tracker/fixtures/IngestsTrackerApiFixture.scala
This will hopefully simplify creating IngestsTrackerApi a bit and remove the possibility of "scala.UninitializedFieldError: Uninitialized field" error.
> IngestsTrackerApi should be a class

- common/src/main/scala/uk/ac/wellcome/platform/archive/common/ingests/models/Ingest.scala
- ingests/ingests_tracker/src/main/scala/uk/ac/wellcome/platform/storage/ingests_tracker/tracker/IngestStates.scala
- ingests/ingests_tracker/src/test/scala/uk/ac/wellcome/platform/storage/ingests_tracker/client/IngestTrackerClientTest.scala
- ingests/ingests_tracker/src/test/scala/uk/ac/wellcome/platform/storage/ingests_tracker/tracker/IngestStatesTest.scala
- ingests/ingests_tracker/src/test/scala/uk/ac/wellcome/platform/storage/ingests_tracker/tracker/IngestTrackerTestCases.scala
This would allow us to retry ingests that have failed (for example, from the failed replication policy).
I've reordered some bits of the codebase to emphasise the strict waterfall that ingest states can follow.
Closes https://github.com/wellcomecollection/platform/issues/4512
> Allow moving an ingest from "failed" to "succeeded"

- indexer/ingests_indexer/src/main/resources/application.conf
- indexer/ingests_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/ingests/Main.scala
- terraform/modules/stack/main.tf
- terraform/modules/stack/variables.tf
- terraform/stack_prod/main.tf
- terraform/stack_staging/main.tf
This makes everything a bit simpler:
* We don't have to manage rollup jobs
* The same ingest doesn't appear multiple times in different indexes
* We only have ~280k ingests in prod; the size of the index is tiny by Elasticsearch standards
Closes https://github.com/wellcomecollection/platform/issues/4525
I'll go through and send all the existing ingests for reindexing once this is applied.
> Write all the ingests to a single index, not multiple indexes

- terraform/modules/service/api/main.tf
- terraform/modules/service/base/variables.tf
- terraform/modules/service/ingest/main.tf
- terraform/modules/service/worker/main.tf
- terraform/modules/service/worker/variables.tf
- terraform/modules/stack/api/variables.tf
- terraform/modules/stack/locals.tf
- terraform/modules/stack/main.tf
- terraform/modules/stack/replifier/main.tf
- terraform/modules/stack/replifier/variables.tf
- terraform/modules/stack/variables.tf
* Actually pass CPU, memory and Fargate spot definitions to underlying modules
* Remove unused Logstash variables
* Point the Glacier verifier at the right bucket
> Fix a variety of Terraform bugs

- api/bags_api/src/main/resources/logback.xml
- bag_register/src/main/resources/logback.xml
- bag_replicator/src/main/resources/logback.xml
- bag_root_finder/src/main/resources/logback.xml
- bag_unpacker/src/main/resources/logback.xml
- bag_verifier/src/main/resources/logback.xml
- bag_versioner/src/main/resources/logback.xml
- indexer/bag_indexer/src/main/resources/logback.xml
- indexer/ingests_indexer/src/main/resources/logback.xml
- ingests/ingests_api/src/main/resources/logback.xml
- ingests/ingests_tracker/src/main/resources/logback.xml
- ingests/ingests_worker/src/main/resources/logback.xml
- ingests/ingests_worker/src/test/resources/logback-test.xml
- notifier/src/main/resources/logback.xml
- replica_aggregator/src/main/resources/logback.xml
New AWS lib logs don't get caught by the old filter.
> Quieter logs

- .travis.yml
- Makefile
- s3_object_tagger/README.md
- s3_object_tagger/src/tag_chooser.py
- s3_object_tagger/src/test_tag_chooser.py
This PR just implements a rule for deciding what tags should be applied to an object, in a way that should be fairly extensible if we decide to add more rules in future.
A first step towards https://github.com/wellcomecollection/platform/issues/4488
> Build a minimal S3 object tagger

- common/src/main/scala/uk/ac/wellcome/platform/archive/common/ingests/models/StorageProvider.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/SourceLocationPayloadTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/IngestGenerators.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/PayloadGenerators.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/StorageLocationGenerators.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/StorageManifestGenerators.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/ingests/models/StorageProviderTest.scala
- display/src/test/scala/uk/ac/wellcome/platform/archive/display/DisplayProviderTest.scala
- display/src/test/scala/uk/ac/wellcome/platform/archive/display/ingests/DisplayIngestTest.scala
- ingests/ingests_api/src/main/scala/uk/ac/wellcome/platform/storage/ingests/api/responses/CreateIngest.scala
- ingests/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/CreateIngestApiTest.scala
- ingests/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/LookupIngestApiTest.scala
- notifier/src/test/scala/uk/ac/wellcome/platform/archive/notifier/NotifierFeatureTest.scala
- notifier/src/test/scala/uk/ac/wellcome/platform/archive/notifier/services/CallbackUrlServiceTest.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorTest.scala
- terraform/modules/stack/main.tf
This replaces the existing three storage providers (`aws-s3-standard`, `aws-s3-ia` and `aws-s3-glacier`) with two new ones (`amazon-s3` and `azure-blob-storage`).
The old storage providers continue to be accepted – e.g. if Goobi sends an ingest with `"provider": "aws-s3-standard"`, it gets handled correctly, with no change needed – but it simplifies what the storage service emits.
In particular, we'll no longer make claims about the S3 storage class of replicas that may or may not be true (for example, saying a bag is Standard IA when in fact some of the objects are Standard or Glacier). It's a precursor for the MXF work and the third replica.
Closes https://github.com/wellcomecollection/platform/issues/4466
> Simplify the storage providers we use

- bag_tracker/src/main/scala/uk/ac/wellcome/platform/archive/bag_tracker/BagTrackerApi.scala
- bag_tracker/src/main/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/BagTrackerClient.scala
- bag_tracker/src/main/scala/uk/ac/wellcome/platform/archive/bag_tracker/services/GetLatestBag.scala
- bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/BagTrackerClientTestCases.scala
- bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/GetLatestBagTestCases.scala
Now people who aren't picky about the version can look up a bag.
For https://github.com/wellcomecollection/platform/issues/4534
> Add a getLatest() bag method to the bag tracker

- bag_tracker/src/main/scala/uk/ac/wellcome/platform/archive/bag_tracker/BagTrackerApi.scala
- bag_tracker/src/main/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/BagTrackerClient.scala
- bag_tracker/src/main/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/BagTrackerError.scala
- bag_tracker/src/main/scala/uk/ac/wellcome/platform/archive/bag_tracker/services/CreateBag.scala
- bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/BagTrackerClientTestCases.scala
- bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/CreateBagTestCases.scala
So somebody can read bags from the database, but how do they get there? With the createBag() method!
This rounds out the set of methods that the bag tracker needs – next up is plumbing it through into other services.
For wellcomecollection/platform#4534
> Plumb in the createBag() method to the bag tracker

- indexer/reindex_bags_backlog.py
- terraform/modules/stack/iam_role_policy.tf
The ~api &~ indexer does not require write access to the VHS.
> Correct permissions for api/indexer

- bag_register/src/main/resources/application.conf
- bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/Main.scala
- bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/models/RegistrationSummary.scala
- bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorker.scala
- bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/services/Register.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/fixtures/BagRegisterFixtures.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorkerTest.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/RegisterTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/BagRegistrationNotification.scala
- terraform/modules/stack/main.tf
- terraform/modules/stack/messaging.tf
Part of https://github.com/wellcomecollection/platform/issues/4558
This modifies the bag register to send a smaller, simpler message to a new topic. The existing flows are unaffected.
> Send a simpler payload from the bag register

- indexer/bag_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/bags/BagsIndexConfig.scala
- indexer/bag_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/bags/models/IndexedStorageManifest.scala
- indexer/bag_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/bags/services/FileSuffix.scala
- indexer/bag_indexer/src/test/scala/uk/ac/wellcome/platform/archive/indexer/bag/services/FileSuffixTest.scala
Some mappings tweaks for the bag indexer: 
- Use storage provider id, instead of toString classname
- Files is a nested field
- Clarify file suffix extraction
> Mapping tweaks for bag indexer

- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/fixtures/BagRegisterFixtures.scala
- bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/responses/LookupBag.scala
- bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/responses/LookupBagVersions.scala
- bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/responses/ResponseBase.scala
- bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/fixtures/BagsApiFixture.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/models/BagVersion.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/models/BagVersionTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/StorageManifestDaoFixture.scala
- indexer/bag_indexer/src/test/scala/uk/ac/wellcome/platform/archive/indexer/bag/BagIndexerFeatureTest.scala
- indexer/bag_indexer/src/test/scala/uk/ac/wellcome/platform/archive/indexer/bag/BagIndexerWorkerTest.scala
- indexer/bag_indexer/src/test/scala/uk/ac/wellcome/platform/archive/indexer/bag/fixtures/BagIndexerFixtures.scala
- indexer/common/src/test/scala/uk/ac/wellcome/platform/archive/indexer/IndexerFeatureTestCases.scala
- indexer/common/src/test/scala/uk/ac/wellcome/platform/archive/indexer/IndexerWorkerTestCases.scala
- indexer/ingests_indexer/src/test/scala/uk/ac/wellcome/platform/archive/indexer/ingests/IngestsIndexerFeatureTest.scala
- indexer/ingests_indexer/src/test/scala/uk/ac/wellcome/platform/archive/indexer/ingests/IngestsIndexerWorkerTest.scala
- indexer/ingests_indexer/src/test/scala/uk/ac/wellcome/platform/archive/indexer/ingests/fixtures/IngestsIndexerFixtures.scala
* Reduce repetition in the indexer tests (for https://github.com/wellcomecollection/platform/issues/4558)
* Add a method to parse a BagVersion from a string (also for #4558, when the new tagger app reads the notification)
> Refactoring some internal classes

- terraform/modules/stack/main.tf
- terraform/modules/stack/messaging.tf
Use a dedicated queue for the bag_indexer, subscribed to the reindex script and bag_register ouput topics.
> Clarify bag_indexer messaging

- indexer/bag_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/bags/Main.scala
- indexer/common/src/main/scala/uk/ac/wellcome/platform/archive/indexer/elasticsearch/ElasticsearchIndexCreator.scala
The files attribute on bag docs can have up to ~970000 nested docs!
> Allow index settings and pass nested doc default

- indexer/reindex_bags_backlog.py
To debug remaining not indexed, confirm and republish specified ids using the `--ids` flag.
> Allow sending of specific bag_ids in bag reindex script

- indexer/reindex_bags_backlog.py
- terraform/modules/stack/messaging.tf
To stay in line with the messaging scheme elsewhere in the storage service.
> Use consistent messaging names for indexer

- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/SizeFinder.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestService.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/SizeFinderTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestServiceTest.scala
Another piece building on #581, part of wellcomecollection/platform#4562
This gives us the nicer types from scala-storage, so we can distinguish between "does not exist" and "unexpected error".  Having this distinction allows us to use these classes in the bag verifier, when we want to look up the size of an object that's been cycled to Glacier.
> Change SizeFinder to return an Either, not a Try

- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FileFixityResult.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityChecker.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityCheckerTestCases.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityCheckerTests.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/generators/FixityGenerators.scala
Spun out of https://github.com/wellcomecollection/storage-service/pull/581, part of https://github.com/wellcomecollection/platform/issues/4562
This is a refactoring of the bag verifier to make it easier to change for the storage tiering work. There are also some new tests for edge cases we weren't previously covering. Plus a bit more logging, because this is a bit of the codebase where detailed tracing in the tests is super useful.
No outward-facing behaviour change in this PR.
> More abstraction and testing in the bag verifier

- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/s3/S3ReplicatorTest.scala
This is mostly handled by the underlying scala-storage library and the PrefixTransfer class, but it's sufficiently important to the storage service to be worth testing twice.
For https://github.com/wellcomecollection/platform/issues/4562
> Add a test that the replicator doesn't copy tags

- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FileFixityResult.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityChecker.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/memory/MemoryFixityChecker.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/s3/S3FixityChecker.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityCheckerTestCases.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityCheckerTests.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/memory/MemoryFixityCheckerTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/s3/S3FixityCheckerTest.scala
- build.sbt
Closes https://github.com/wellcomecollection/storage-service/pull/581. For https://github.com/wellcomecollection/platform/issues/4562
Now it's been refactored, you can see how new methods `getExistingTags()`, `verifyChecksum()` and `writeFixityTags()` drop into the fixity checker.
> Bag verifier uses tags to cache verification results, but for realsies

- indexer/bag_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/bags/BagIndexer.scala
- indexer/common/src/main/scala/uk/ac/wellcome/platform/archive/indexer/elasticsearch/Indexer.scala
- indexer/common/src/main/scala/uk/ac/wellcome/platform/archive/indexer/elasticsearch/IndexerWorker.scala
- indexer/ingests_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/ingests/IngestIndexer.scala
If the document is large, it completely spams the logging and makes it hard to find the actual error.
Spotted by @kenoir as part of https://github.com/wellcomecollection/platform/issues/4571
> Don't log an entire document when it fails to index

- bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/BagsApi.scala
- bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/Main.scala
- bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/LookupBagApiTest.scala
- bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/fixtures/BagsApiFixture.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/LargeResponses.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/ObjectExists.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/S3Uploader.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/s3/S3ObjectExists.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/s3/S3Uploader.scala
- common/src/main/scala/uk/ac/wellcome/storage/Location.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/LargeResponsesTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/s3/S3ObjectExistsTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/s3/S3UploaderTest.scala
- common/src/test/scala/uk/ac/wellcome/storage/fixtures/NewS3Fixtures.scala
Part of wellcomecollection/platform#4596; follows #600
This patch:
* Disambiguates ObjectExists and S3ObjectExists (which could be upstreamed)
* Starts to introduce the Prefix/Location hierarchy
* Enforces S3-only in S3Uploader and LargeResponses
> Disambiguate more S3 locations

- bag_root_finder/src/main/scala/uk/ac/wellcome/platform/storage/bag_root_finder/services/BagRootFinder.scala
- bag_root_finder/src/main/scala/uk/ac/wellcome/platform/storage/bag_root_finder/services/S3BagLocator.scala
- bag_root_finder/src/test/scala/uk/ac/wellcome/platform/storage/bag_root_finder/services/S3BagLocatorTest.scala
- common/src/main/scala/uk/ac/wellcome/storage/Location.scala
- common/src/test/scala/uk/ac/wellcome/storage/fixtures/NewS3Fixtures.scala
The bag root finder is now using S3ObjectLocation internally; swapping the inter-app payloads is a bit more dicey and should be done separately.
Part of wellcomecollection/platform#4596
> Move S3BagLocator into the bag root finder; use new S3 Locations

- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/BagReplicatorFeatureTest.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/bags/BagReplicatorTest.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/fixtures/BagReplicatorFixtures.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorkerTest.scala
- bag_root_finder/src/test/resources/logback-test.xml
- bag_root_finder/src/test/scala/uk/ac/wellcome/platform/storage/bag_root_finder/BagRootFinderFeatureTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/BagVerifierFeatureTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierWorkerTest.scala
- bag_versioner/src/test/scala/uk/ac/wellcome/platform/storage/bag_versioner/BagVersionerFeatureTest.scala
- common/src/main/scala/uk/ac/wellcome/storage/Location.scala
- common/src/main/scala/uk/ac/wellcome/storage/store/s3/NewS3StreamStore.scala
- common/src/main/scala/uk/ac/wellcome/storage/store/s3/NewS3TypedStore.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/BagBuilder.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/BagBuilderBase.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/BetterBagBuilder.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/s3/S3BagBuilder.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/PayloadGenerators.scala
- common/src/test/scala/uk/ac/wellcome/storage/fixtures/NewS3Fixtures.scala
The BagBuilder code was a bit of a mess – a mix of being called as a mixin and as an object. This standardises it as a trait that gets mixed in like everything else, and enforces a Location/Prefix hierarchy.
Sorting out the in-memory versions is harder, because you have to fiddle with stores a bit – separate patch.
The big diff is because I've duplicated BagBuilderBase; a subsequent PR will remove one of the copies to bring the line count back down.
Part of wellcomecollection/platform#4596
> Disambiguate the creation of S3 bags in our tests

- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/Unpacker.scala
- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/UnpackerMessage.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/fixtures/BagUnpackerFixtures.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/fixtures/CompressFixture.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/UnpackerMessageTest.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/UnpackerTestCases.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/memory/MemoryUnpackerTest.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/s3/S3UnpackerTest.scala
Some improvements found while working on wellcomecollection/platform#4596, pulled out as a separate patch.
* Remove an unused class
* We used to have to wrap the StreamStore from the storage library, but now the metadata is gone, no more!
* Don't share state between different tests, eww
* Pull out the unpacker messages into a standalone object for simpler testing
> Tidy up the bag unpacker tests

- common/src/main/scala/uk/ac/wellcome/platform/archive/common/PipelinePayload.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/ingests/models/Ingest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/ingests/models/SourceLocation.scala
- common/src/main/scala/uk/ac/wellcome/storage/Location.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/SourceLocationPayloadTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/IngestGenerators.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/DisplayLocation.scala
- display/src/test/scala/uk/ac/wellcome/platform/archive/display/DisplayLocationTest.scala
- display/src/test/scala/uk/ac/wellcome/platform/archive/display/ingests/DisplayIngestTest.scala
- ingests/ingests_api/src/main/scala/uk/ac/wellcome/platform/storage/ingests/api/responses/CreateIngest.scala
- ingests/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/CreateIngestApiTest.scala
- ingests/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/LookupIngestApiTest.scala
- ingests/ingests_tracker/src/main/scala/uk/ac/wellcome/platform/storage/ingests_tracker/IngestsTrackerApi.scala
- notifier/src/test/scala/uk/ac/wellcome/platform/archive/notifier/NotifierFeatureTest.scala
- notifier/src/test/scala/uk/ac/wellcome/platform/archive/notifier/services/CallbackUrlServiceTest.scala
Follows #607, part of wellcomecollection/platform#4596
When you start an ingest, you supply a SourceLocation. This could be S3 or Azure, and until now it's held a generic ObjectLocation. Changes:
* Ingests API: you can only upload a bag with the S3 provider. Anything else will be rejected immediately, because the unpacker doesn't support it.
* Strongly type the SourceLocation model with the appropriate provider/location model. We can’t try to unpack an S3 bag from an Azure location, or vice versa.
* Store a generic SourceLocation on the Ingest model. If we never add Azure support, it's just an extra `"type"` parameter in a few places; but we're set up to support it if we ever do.
This doesn't change the external interfaces – the ingests API or the indexed models. We will need to migrate …
> Split SourceLocation into per-provider models

- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifier.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/verify/steps/VerifyFetch.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/verify/steps/VerifyFetchTest.scala
I wasn't sure if it did, and stumbled across it while doing ObjectLocation work. Added a test that, yes, it really does the right thing.
> Verify that the verifier checks the URI scheme in fetch.txt

- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/models/UnpackSummary.scala
- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/BagUnpackerWorker.scala
- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/Unpacker.scala
- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/UnpackerMessage.scala
- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/memory/MemoryUnpacker.scala
- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/s3/S3StreamReader.scala
- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/s3/S3Unpacker.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/UnpackerFeatureTest.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/fixtures/BagUnpackerFixtures.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/fixtures/CompressFixture.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/fixtures/s3/S3CompressFixture.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/BagUnpackerWorkerTest.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/UnpackerMessageTest.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/UnpackerTestCases.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/memory/MemoryUnpackerTest.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/s3/S3StreamReaderTest.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/s3/S3UnpackerTest.scala
- common/src/main/scala/uk/ac/wellcome/storage/Location.scala
This doesn't affect the interface between services, just the internals of the bag unpacker.
> Use the new per-provider Location models inside the bag unpacker

- common/src/main/scala/uk/ac/wellcome/platform/archive/common/PipelinePayload.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/ingests/models/SourceLocation.scala
- common/src/main/scala/uk/ac/wellcome/storage/Location.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/SourceLocationPayloadTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/IngestGenerators.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/DisplayLocation.scala
- display/src/test/scala/uk/ac/wellcome/platform/archive/display/DisplayLocationTest.scala
- display/src/test/scala/uk/ac/wellcome/platform/archive/display/ingests/DisplayIngestTest.scala
- ingests/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/CreateIngestApiTest.scala
- ingests/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/LookupIngestApiTest.scala
- notifier/src/test/scala/uk/ac/wellcome/platform/archive/notifier/NotifierFeatureTest.scala
- notifier/src/test/scala/uk/ac/wellcome/platform/archive/notifier/services/CallbackUrlServiceTest.scala
The SourceLocation refers to the location of the compressed tar.gz bag, not a prefix under which all the files are unpacked.  We should store it as a Location, not a Prefix.
I only noticed this when I deployed it and looked at a new row in DynamoDB.
> SourceLocation is an actual location, not a prefix

- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/Main.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifier.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/verify/steps/VerifyFetch.scala
- bag_verifier/src/test/resources/logback-test.xml
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixtures/BagVerifierFixtures.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/verify/steps/VerifyFetchTest.scala
The primary goal of this PR is to expunge `_.path.stripPrefix(root.path).stripPrefix("/")` where `_` is an old-style ObjectLocation, because getting a path from a new-style location is a bit trickier (and in this case, unnecessary). Plus some other general tidy-ups that don't change the functionality but make the code easier to work with.
> Continue to chip away at the bag verifier

- .gitignore
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FileFixityResult.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityChecker.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityListChecker.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityListResult.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/bag/BagExpectedFixity.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/memory/MemoryFixityChecker.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/s3/S3FixityChecker.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/models/VerificationSummary.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifier.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/storage/Locatable.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/storage/bag/BagLocatable.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/storage/s3/S3Locatable.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/verify/steps/VerifyChecksumAndSize.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/verify/steps/VerifyNoUnreferencedFiles.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/verify/steps/VerifyPayloadOxum.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityCheckerTestCases.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityCheckerTests.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/bag/BagExpectedFixityTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/memory/MemoryFixityCheckerTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/s3/S3FixityCheckerTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/generators/FixityGenerators.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierTest.scala
- common/src/main/scala/uk/ac/wellcome/storage/tags/s3/NewS3Tags.scala
Yet another step towards https://github.com/wellcomecollection/platform/issues/4596. I started at FixityChecker and worked my way outwards until the tests were passing and compiling again. This is probably the most fiddly part of the ObjectLocation disambiguation; I think it should be easier from here.
> Push BagLocation throughout the fixity checks in the verifier

- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/Main.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/bag/BagExpectedFixity.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/models/VerificationSummary.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifier.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierWorker.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/s3/S3BagVerifier.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/storage/bag/BagLocatable.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/storage/s3/S3Resolvable.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/verify/steps/VerifyChecksumAndSize.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/verify/steps/VerifyNoUnreferencedFiles.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/bag/BagExpectedFixityTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/s3/S3FixityCheckerTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixtures/BagVerifierFixtures.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierTest.scala
- common/src/main/scala/uk/ac/wellcome/storage/Location.scala
- common/src/main/scala/uk/ac/wellcome/storage/listing/s3/NewS3Listing.scala
- common/src/main/scala/uk/ac/wellcome/storage/listing/s3/NewS3ObjectLocationListing.scala
Another part of https://github.com/wellcomecollection/platform/issues/4596
This finishes the refactoring of the bag verifier internals. The inter-app payloads are still using old-style locations, but I'll fix that soon.
> Use new-style locations throughout the verifier

- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/models/ReplicaLocation.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/ReplicaLocationGenerators.scala
- replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/models/AggregatorInternalRecord.scala
- replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaCounter.scala
- replica_aggregator/src/test/resources/logback-test.xml
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/ReplicaAggregatorFeatureTest.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/models/AggregatorInternalRecordTest.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorTest.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorWorkerTest.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaCounterTest.scala
Part of wellcomecollection/platform#4596
Previously the replica aggregator would store a `PrimaryStorageLocation` and a list of `SecondaryStorageLocation`.
This patch modifies its internal storage to hold a `PrimaryReplicaLocation` and a list of `SecondaryReplicaLocation`. These omit the provider value, because we can deduce it from the type of `Prefix`.
It doesn't change the inter-app messaging formats.
Once this is merged and deployed, I'll run a migration over the existing replica aggregator tables to use the new format, which we know is always S3.
> Store new-style locations in the replica aggregator

- bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/services/StorageManifestService.scala
If you don't make this value lazy, you get an error when you start the app via Main:
Exception in thread "main" scala.UninitializedFieldError: Uninitialized field: bag_register/services/s3/S3StorageManifestService.scala: 28
I haven't fully debugged this error and I'm not sure why it occurs here but not in the tests; I do know that this change fixes it.  This is breaking the pipeline and doesn't add any tech debt, so I'm happy to leave it without digging further.
Fix for https://github.com/wellcomecollection/platform/issues/4617
> Create this instance of TagManifestFileFinder lazily

- terraform/modules/critical/s3_replica_primary.tf
Add role uniqueId to s3_replica_primary, this is to allow the dashboard to read these buckets.
See [iiif-builder-infrastructure commit](https://github.com/wellcomecollection/iiif-builder-infrastructure/pull/2/commits/07e89fcab0e212f4999906bc29ea6d8ec8be1c2e) for where this is coming from.
> Add iiif-builder dashboard principal to storage buckets

- bag_versioner/src/test/scala/uk/ac/wellcome/platform/storage/bag_versioner/BagVersionerFeatureTest.scala
- bag_versioner/src/test/scala/uk/ac/wellcome/platform/storage/bag_versioner/services/BagVersionerTest.scala
Another step for https://github.com/wellcomecollection/platform/issues/4596
> Remove a now-unused ObjectLocationGenerators trait

- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/builders/BagLocationBuilder.scala
- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/BagUnpackerWorker.scala
- bag_unpacker/src/test/resources/logback-test.xml
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/UnpackerFeatureTest.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/BagUnpackerWorkerTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/PipelinePayload.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/ingests/models/SourceLocation.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/SourceLocationPayloadTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/PayloadGenerators.scala
- display/src/main/scala/uk/ac/wellcome/platform/archive/display/DisplayLocation.scala
- display/src/test/scala/uk/ac/wellcome/platform/archive/display/DisplayLocationTest.scala
Another step towards removing ObjectLocation from the codebase. Part of https://github.com/wellcomecollection/platform/issues/4596
> Send a new-style location from the ingests API to the bag unpacker

- bag_replicator/docker-compose.yml
- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/azure/AzureReplicator.scala
- bag_replicator/src/test/resources/logback-test.xml
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/ReplicatorTestCases.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/azure/AzureReplicatorTest.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/s3/S3ReplicatorTest.scala
Part of https://github.com/wellcomecollection/platform/issues/4587
This adds a new AzureReplicator class which can be passed to BagReplicatorWorker once we sort out the config. I've not wired up the config yet because that requires more finesse, and I want to see how Alice does the verifier so we can stay in sync – this is a fairly vanilla patch that doesn't need as much thought.
> Add a internal AzureReplicator class

- terraform/modules/critical/s3_replica_primary.tf
There are now 2 'staging' dashboards - one using staging storage and one using production storage
https://github.com/wellcomecollection/iiif-builder-infrastructure/pull/7 is the 'other end' of this change, specifically [this](https://github.com/wellcomecollection/iiif-builder-infrastructure/blob/4591cecfa751dd3ed44b05be81baff274461f431/infrastructure/staging/dashboard.tf#L135-L144)
> Add dds dashboard principal to storage buckets

- bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/services/StorageManifestService.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/RegisterTest.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/StorageManifestServiceTest.scala
This is already checked by the bag verifier, and stricter as well -- it checks the scheme is s3://, rather than just lifting the host and path and treating it as definitely S3.
See https://github.com/wellcomecollection/storage-service/blob/167310dd85d78404ca7718017afcc572498f6277/bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/verify/steps/VerifyFetch.scala#L13-L54
If we detect an error here, it indicates a problem in the pipeline -- the bag should never have been allowed to get this far. The internal assertion gives us a quick check, but detailed error handling is unnecessary for what should be an impossible scenario.
This check was originally put in the bag register because it was the easiest place to add it, even though it's more appropriate in the bag verifier. …
> Don't check files are in the right namespace in the bag register

- terraform/modules/stack/images.tf
- terraform/modules/stack/replifier/variables.tf
Requires:
- https://github.com/wellcomecollection/storage-service/pull/640
- https://github.com/wellcomecollection/storage-service/pull/639
- A release to be prepared and deployed for the staging environment
*Note*: `weco-deploy` as of 4.1.0 does not recognise that multiple images can target the same service - this may result in multiple deployment of a service when ECS automated deployment runs (this will be resolved in an upcoming weco-deploy release. See (https://github.com/wellcomecollection/weco-deploy/pull/24)
> Use images in services with static tags for use with new deploy tool

- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/models/BagReplicationRequest.scala
- bag_root_finder/src/main/scala/uk/ac/wellcome/platform/storage/bag_root_finder/services/BagRootFinderWorker.scala
- bag_root_finder/src/test/scala/uk/ac/wellcome/platform/storage/bag_root_finder/BagRootFinderFeatureTest.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/Main.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/builder/BagVerifierWorkerBuilder.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierWorker.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/BagVerifierFeatureTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixtures/BagVerifierFixtures.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierWorkerTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/PipelinePayload.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/models/ReplicaResult.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/PayloadGenerators.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorTest.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorWorkerTest.scala
A straggling bit from https://github.com/wellcomecollection/platform/issues/4594 that I missed in code review – as written, the verifier checks that the tag manifest in a replicated bag is the same as … itself. Which is less than helpful.
We also start to head in a direction of using new-style locations in the verifier, which unlocks doing it in the rest of the pipeline. https://github.com/wellcomecollection/platform/issues/4596
> Pass the unpacked bag location from the replicator

- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/models/BagReplicationRequest.scala
- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/Replicator.scala
- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/azure/AzureReplicator.scala
- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/models/ReplicationRequest.scala
- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/models/ReplicationSummary.scala
- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/s3/S3Replicator.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/ReplicatorTestCases.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/azure/AzureReplicatorTest.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/s3/S3ReplicatorTest.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorkerTest.scala
- bag_root_finder/src/main/scala/uk/ac/wellcome/platform/storage/bag_root_finder/services/BagRootFinderWorker.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/builder/BagVerifierWorkerBuilder.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierWorkerTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/PipelinePayload.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/PayloadGenerators.scala
With this patch:
1. The bag root finder sends an S3ObjectLocationPrefix to the pre-replicator bag verifier
2. The pre-repl bag verifier sends an S3ObjectLocationPrefix to the bag replicator
3. The bag replicator expects to receive an S3ObjectLocationPrefix as a source
The last is mildly annoying, but follows what we've done elsewhere – the replicator/unpacker/root finder can only deal with bags stored in S3, and that's not changed, but now it's more explicit.
> Use the new-style location in more verifier payloads

- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/models/BagReplicationRequest.scala
- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorker.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/BagReplicatorFeatureTest.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorkerTest.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/builder/BagVerifierWorkerBuilder.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixtures/BagVerifierFixtures.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierWorkerTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/PipelinePayload.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/models/ReplicaResult.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/PayloadGenerators.scala
- replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregator.scala
- replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorWorker.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/ReplicaAggregatorFeatureTest.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorTest.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorWorkerTest.scala
Some more refactoring in service of https://github.com/wellcomecollection/platform/issues/4596
We have a model "ReplicaResult" and another "ReplicationResult". This isn't at all confusing.
The former is only a wrapper around two locations passed around as an inter-app payload, so this PR ditches the wrapper and puts those locations directly on the payload. One less class to think about.
> Ditch the ReplicaResult model; rename the payload to ReplicaComplete

- bag_register/docker-compose.yml
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/BagRegisterFeatureTest.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/fixtures/BagRegisterFixtures.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorkerTest.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/RegisterTest.scala
- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorker.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/BagReplicatorFeatureTest.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/fixtures/BagReplicatorFixtures.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorkerTest.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/builder/BagVerifierWorkerBuilder.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierWorkerTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/PipelinePayload.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/StorageRandomThings.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/PayloadGenerators.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/ReplicaLocationGenerators.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/StorageLocationGenerators.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/StorageManifestGenerators.scala
- replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/models/AggregatorInternalRecord.scala
- replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/models/ReplicaPath.scala
- replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregator.scala
- replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorWorker.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/ReplicaAggregatorFeatureTest.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/fixtures/ReplicaAggregatorFixtures.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorTest.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorWorkerTest.scala
Follows #648, part of https://github.com/wellcomecollection/platform/issues/4596
Both apps are using ReplicaLocation internally, so we can strip off a translation layer and pass it between them.
> Pass a new-style ReplicaLocation between the replicator and the aggregator

- bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorker.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/BagRegisterFeatureTest.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorkerTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/models/KnownReplicas.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/PayloadGenerators.scala
- replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaCounter.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/ReplicaAggregatorFeatureTest.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorWorkerTest.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaCounterTest.scala
Still not changing any of the bag register behaviour, but inching closer towards it…
> Send the new ReplicaLocations between the replica aggregator and the bag register

- bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/Main.scala
- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/Main.scala
- bag_root_finder/src/main/scala/uk/ac/wellcome/platform/storage/bag_root_finder/Main.scala
- bag_tagger/src/main/scala/uk/ac/wellcome/platform/storage/bag_tagger/Main.scala
- bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/Main.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/Main.scala
- bag_versioner/src/main/scala/uk/ac/wellcome/platform/storage/bag_versioner/Main.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/http/WellcomeHttpApp.scala
- indexer/bag_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/bags/Main.scala
- indexer/ingests_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/ingests/Main.scala
- ingests/ingests_api/src/main/scala/uk/ac/wellcome/platform/storage/ingests/api/Main.scala
- ingests/ingests_tracker/src/main/scala/uk/ac/wellcome/platform/storage/ingests_tracker/IngestsTrackerApi.scala
- ingests/ingests_tracker/src/main/scala/uk/ac/wellcome/platform/storage/ingests_tracker/Main.scala
- ingests/ingests_tracker/src/test/scala/uk/ac/wellcome/platform/storage/ingests_tracker/fixtures/IngestsTrackerApiFixture.scala
- ingests/ingests_worker/src/main/scala/uk/ac/wellcome/platform/storage/ingests_worker/Main.scala
- notifier/src/main/scala/uk/ac/wellcome/platform/archive/notifier/Main.scala
- replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/Main.scala
Spotted while doing some refactoring for https://github.com/wellcomecollection/platform/issues/4596
In [Akka 2.6][1], you don't need to supply an implicit Materializer if there's an implicit ActorSystem:
> A default materializer is now provided out of the box. For the Java API just pass system when running streams, for Scala an implicit materializer is provided if there is an implicit ActorSystem available. This avoids leaking materializers and simplifies most stream use cases somewhat.
The Materializer instances are often boilerplate that we can delete without losing anything; this highlights places where we *do* need a Materializer (e.g. for Akka flows).
[1]: https://doc.akka.io/docs/akka/current/project/migration-guide-2.5.x-2.6.x.html#materializer-changes
> Remove some unneeded Materializer instances

- terraform/critical_prod/locals.tf
- terraform/critical_prod/main.tf
- terraform/critical_staging/locals.tf
- terraform/critical_staging/main.tf
- terraform/modules/critical/s3_replica_primary.tf
As discussed in Slack, this is an interim change to test with iiif-builder as these are not live yet. When we have it working we can create a follow-up PR which removes all Digirati specific access for DLCS to use.
> Grant s3 access to digirati account, rather than roles

- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/builder/BagVerifierWorkerBuilder.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/models/BagVerifyContext.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifier.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/s3/S3BagVerifier.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/verify/steps/VerifySourceTagManifest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixtures/BagVerifierFixtures.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierTestCases.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/s3/S3BagVerifierTest.scala
Part of https://github.com/wellcomecollection/platform/issues/4595; follows #665 
Currently the original and replica location are both instances of `S3ObjectLocation`; when we want to verify bags from Azure, that's going to change. This replumbs the verifier so that it takes different type parameters everywhere it cares about these locations, which will allow us to have different locations in a later patch.
As a side note, I think it'd be worth breaking the BagVerifier/Standalone/Replicated classes into separate files (but not here; it would muddy the diffs enormously).
> Allow a replicated bag to have different source/replica locations

- scripts/_aws.py
- scripts/_azure.py
- scripts/azure_create_replicator_credentials.py
- scripts/azure_renew_storage_keys.py
- scripts/create_azure_connection_string.py
This patch includes two scripts:
* `azure_create_replicator_credentials.py` will log you in using the Azure CLI, create an SAS URI for our two storage accounts that's IP-limited to our Elastic IPs, then put a copy of that URI in Secrets Manager
* `azure_renew_storage_keys.py` will renew our storage account keys, effectively revoking the existing SAS URIs. It then calls the first script to create a new set of replicator credentials.
Part of https://github.com/wellcomecollection/platform/issues/4658
> Better scripts for doing Azure authentication

- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/ExpectedFileFixity.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityListChecker.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/bag/BagExpectedFixity.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/verify/steps/VerifyChecksumAndSize.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityCheckerTestCases.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityCheckerTests.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/bag/BagExpectedFixityTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/s3/S3FixityCheckerTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/generators/FixityGenerators.scala
Part of wellcomecollection/platform#4595. Extracted as a standalone piece from #669; follows #682.
This is @alicefuzier’s commit https://github.com/wellcomecollection/storage-service/pull/669/commits/3d2e3b7c762c624683ead63200509b3d348213ae cherry-picked into its own branch, as another piece that can be reviewed and merged separately.
She realised that when we verify bags in Azure, we'll need to use a different fixity checker depending on whether the file is from a fetch.txt (so in S3) or in the data directory (so in Azure). Although this is really only useful when we have an Azure fixity checker, we can do that in a separate PR, and further reduce the size of #669.
I made one change – the DataDirectoryFileFixity will never have an expected size, so we can hard-code it as None rather than …
> FixityListChecker always checks for fetch files in S3

- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/StorageManifestServiceTest.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityChecker.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityListChecker.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/memory/MemoryFixityChecker.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/s3/S3FixityChecker.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifier.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/s3/S3BagVerifier.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/verify/steps/VerifyChecksumAndSize.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityCheckerTestCases.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityCheckerTests.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/memory/MemoryFixityCheckerTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/s3/S3FixityCheckerTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierTestCases.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/s3/S3BagVerifierTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/BagBuilder.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/azure/AzureBagBuilder.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/memory/MemoryBagBuilder.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/s3/S3BagBuilder.scala
Part of wellcomecollection/platform#4595. Extracted as a standalone piece from #669.
This was pulled out of ea696bd (“Add AzureReplicatedBagVerifierTests”) and edf4e36 (“Starting to add a AzureFixityChecker”) as some refactoring that lays groundwork for the Azure verifier stuff, but doesn’t change any functionality – lots of diff churn. I’ve read it and I’m confident it is correct and it works.
I'm not sure if we want to merge this as a standalone thing, but I'm putting this as a stick in the ground “I got this far”.
> Pull out a bit more test refactoring

- .travis/run_job.py
- scripts/_azure.py
I tested the connection strings this script generates with a local version of AzureListing, and I was able to see blobs in the staging container. I then regenerated all the keys, so the plaintext string on my machine is useless now.
Closes https://github.com/wellcomecollection/platform/issues/4658, closes https://github.com/wellcomecollection/platform/issues/4719
> Grant container-level Azure permissions to the replicator/verifier, not blob-level

- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/fixtures/BagRegisterFixtures.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/StorageManifestServiceTest.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/builder/BagVerifierWorkerBuilder.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/models/BagVerifyContext.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifier.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/s3/S3BagVerifier.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/verify/steps/VerifySourceTagManifest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixtures/BagVerifierFixtures.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierTestCases.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/ReplicatedBagVerifierTestCases.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/s3/S3BagVerifierTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/services/BagReaderTestCases.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/BagBuilder.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/azure/AzureBagBuilder.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/memory/MemoryBagBuilder.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/s3/S3BagBuilder.scala
This refactoring by @alicefuzier reflects the fact that:
* The source bag of a replication is always S3
* The primary copy of a bag is in S3
Until now we've been able to get by sort of implicitly assuming these, because the destination of a replicated bag was also S3. This patch makes this explicit, and lays the groundwork for writing bags to different locations.
A combination of 47ad3f8, 161e4a7, 798abcd, e4e1000, bc9aaef, bd2155f.
Part of wellcomecollection/platform#4595. Extracted as a set of standalone commits from #669. I've reviewed this and I'm happy it looks good, so we can merge it if it passes tests.
> Reflect the primacy of S3 in the storage service in the verifier tests

- common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/services/BagReaderTestCases.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/services/azure/AzureBagReaderTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/services/memory/MemoryBagReaderTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/services/s3/S3BagReaderTest.scala
In the newest versions of scala-libs, the asLocation method is required on definitions of Prefix[_].
> We don't need to re-define asLocation in the BagReader tests

- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/azure/AzureFixityChecker.scala
- bag_verifier/src/test/resources/logback-test.xml
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/azure/AzureFixityCheckerTest.scala
These commits by @alicefuzier add the AzureFixityChecker, which is one of the classes we need for the Azure verifier.
A combination of 94469af and 9e4387a.
Part of wellcomecollection/platform#4595. Extracted as a set of standalone commits from #669, follows #686. I've reviewed this and I'm happy it looks good, so we can merge it if it passes tests.
> Add an Azure implementation of FixityChecker

- monitoring/end_to_end_bag_test/src/end_to_end_bag_test.py
- scripts/_azure.py
- scripts/azure_create_replicator_credentials.py
- terraform/modules/stack/main.tf
- terraform/modules/stack/replifier/main.tf
- terraform/modules/stack/replifier/variables.tf
- terraform/modules/stack/variables.tf
- terraform/stack_prod/main.tf
- terraform/stack_staging/main.tf
Closes https://github.com/wellcomecollection/platform/issues/4730
Previously we gave the Azure verifier read-write credentials, so it could tag blobs in Azure. (The SAS permissions aren't as granular as IAM permissions, so we couldn't give it "write tags but not blobs".)
Because we no longer tag objects in Azure, we can reduce the permissions we give the verifier to read-only.
This change is tested and applied in both staging and prod.
> Give read-only credentials to the Azure verifier

- terraform/critical_prod/outputs.tf
- terraform/critical_staging/outputs.tf
- terraform/modules/critical/azure_replica.tf
- terraform/modules/critical/outputs.tf
We can't actually manage legal holds in Terraform, but we can document their presence and expose whether or not they're enabled.
Closes https://github.com/wellcomecollection/platform/issues/4731
e.g.
> Expose the status of Azure immutability policies/legal holds in TF

- common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/services/BagInfoParser.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/services/BagInfoParserTest.scala
Closes https://github.com/wellcomecollection/platform/issues/4760
> Allow an empty External-Description in bag-info.txt

- common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/services/BagInfoParser.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/services/BagInfoParserTest.scala
The trailing whitespace is stripped in the previous test, so a line with extra whitespace, e.g., `External-Description: `, doesn't get parsed.
Closes https://github.com/wellcomecollection/platform/issues/4760 (again)
> Another fix for an empty External-Description

- bag_root_finder/src/test/scala/uk/ac/wellcome/platform/storage/bag_root_finder/BagRootFinderFeatureTest.scala
Occasionally it doesn't quite complete in the default timeout (1 second), so the test fails because it sees two ingest results instead of one.
See https://travis-ci.org/github/wellcomecollection/storage-service/jobs/721042247
> Bump the visibilityTimeout in this bag root finder test

- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/s3/S3SizeFinder.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/s3/S3LargeStreamReaderTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/s3/S3SizeFinderTest.scala
One of the changes I snuck into https://github.com/wellcomecollection/storage-service/pull/714 is that S3SizeFinder now does a GetObject instead of a HeadObject. This is to expose better error messages in the bag unpacker if something goes wrong, but on the vast majority of calls it won't.
Thus, the new behaviour:
* Try a HeadObject API call first.
* If it succeeds, great, otherwise try a GetObject API call.
* If the Get succeeds (which would be odd, but oh well), great, otherwise use the more detailed error to return to the user
> Only make a GetObject API call if something goes wrong

- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/storage/azure/AzureTransfer.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/storage/azure/AzurePutBlockFromURLTransferTest.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/storage/azure/AzurePutBlockTransferTest.scala
Addresses some issues discovered in https://github.com/wellcomecollection/platform/issues/4743
To write large blobs to Azure, we write a series of smaller, individual blocks and stitch them together at the end. The replicator should be the only service that's writing these blocks, so with this in mind we can cut a few corners to save time and money:
* The Azure API lets you look up all the blocks that have been written but not stitched together (“uncommitted blocks”). Because each instance of the replicator should pick the same blocks + block identifiers, **skip writing a block that already exists in Azure.** This means that if a replicator is interrupted midway through, it won't have to re-send all those blocks.
(If a bad block somehow makes it in, the verifier will catch it.)
* We need …
> Make the Azure transfer more reliable and cheaper

- common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/LargeStreamReader.scala
We had an Azure verification fail to read an OpenByteRange(0), but it doesn't include the underlying error message.
Expose it for easier debugging (e.g. is this a timeout? the object isn't there?).
Discovered while debugging https://wellcome-ingest-inspector.glitch.me/ingests/17495c0c-6d84-47db-b43b-4f30630b3ede
> If we can't read a range, expose the underlying error

- .buildkite/pipeline.yml
I think this will make it easier to spot failures in the BuildKite output.
Before:
After:
> Add labels to the BuildKite steps

- bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/storage/azure/AzureTransfer.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/storage/azure/AzurePutBlockFromURLTransferTest.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/storage/azure/AzurePutBlockTransferTest.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/storage/azure/AzureTransferFixtures.scala
Turns out a key that ends with a `.` has issues with Azure; I'm assuming because "Put Block from URL" can't actually get any data from the URL. This patch modifies the URLTransfer to fallback to transferring the bytes directly in this case. We don't want to do this all the time, but we can make one-off exceptions.
> Transfer objects to Azure whose keys end with a dot

- ingests/ingests_tracker/src/main/scala/uk/ac/wellcome/platform/storage/ingests_tracker/IngestsTrackerApi.scala
- ingests/ingests_tracker/src/main/scala/uk/ac/wellcome/platform/storage/ingests_tracker/client/IngestTrackerClient.scala
- ingests/ingests_tracker/src/main/scala/uk/ac/wellcome/platform/storage/ingests_tracker/client/IngestTrackerError.scala
- ingests/ingests_tracker/src/main/scala/uk/ac/wellcome/platform/storage/ingests_tracker/tracker/IngestError.scala
- ingests/ingests_tracker/src/main/scala/uk/ac/wellcome/platform/storage/ingests_tracker/tracker/IngestTracker.scala
- ingests/ingests_tracker/src/main/scala/uk/ac/wellcome/platform/storage/ingests_tracker/tracker/dynamo/DynamoIngestTracker.scala
- ingests/ingests_tracker/src/main/scala/uk/ac/wellcome/platform/storage/ingests_tracker/tracker/memory/MemoryIngestTracker.scala
- ingests/ingests_tracker/src/test/scala/uk/ac/wellcome/platform/storage/ingests_tracker/IngestsTrackerApiFeatureTest.scala
- ingests/ingests_tracker/src/test/scala/uk/ac/wellcome/platform/storage/ingests_tracker/client/IngestTrackerClientTest.scala
- ingests/ingests_tracker/src/test/scala/uk/ac/wellcome/platform/storage/ingests_tracker/fixtures/IngestTrackerFixtures.scala
- ingests/ingests_tracker/src/test/scala/uk/ac/wellcome/platform/storage/ingests_tracker/fixtures/IngestsTrackerApiFixture.scala
- ingests/ingests_tracker/src/test/scala/uk/ac/wellcome/platform/storage/ingests_tracker/tracker/dynamo/DynamoIngestTrackerTest.scala
- ingests/ingests_worker/src/main/scala/uk/ac/wellcome/platform/storage/ingests_worker/services/IngestsWorkerService.scala
- ingests/ingests_worker/src/test/scala/uk/ac/wellcome/platform/storage/ingests_worker/services/IngestsWorkerServiceTest.scala
Closes https://github.com/wellcomecollection/platform/issues/4781
This introduces a new status code in the ingest tracker API. If you do a `PATCH /ingest/{id}` and that ingest doesn't exist yet, you get an HTTP 404 Not Found instead of HTTP 409 Conflict. This can occur if there's a DynamoDB consistency issue that means the DynamoTracker can't find the ingest.
The tracker client turns this status code into a new error type, and the ingest worker treats this error as non-deterministic.
Plus a couple of other changes to make this code easier to debug if we have other issues in future.
> If the ingest worker tries to update a non-existent ingest, retry

- .buildkite/pipeline.yml
🙈 
I was wondering why the bag tracker wasn't being deployed. Oops.
```
image ID            summary of changes
------------------  ------------------------------------
bag_indexer         ECR tag updated, 1 service deployed
bag_register        ECR tag updated, 2 services deployed
bag_replicator      ECR tag updated, 3 services deployed
bag_root_finder     ECR tag updated, 1 service deployed
bag_tagger          ECR tag updated, 1 service deployed
bag_tracker         -
bag_unpacker        ECR tag updated, 1 service deployed
bag_verifier        ECR tag updated, 4 services deployed
bag_versioner       ECR tag updated, 1 service deployed
bags_api            ECR tag updated, 2 services deployed
ingests_api         ECR tag updated, 1 service deployed
ingests_indexer     ECR tag updated, 1 …
```
> Add the bag tracker to BuildKite

- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifier.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/verify/steps/VerifyLegalFilenames.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierTestCases.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/verify/steps/VerifyLegalFilenamesTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/BagBuilder.scala
Closes https://github.com/wellcomecollection/platform/issues/4790
These files will be caught at the pre-replicator verifier, so although we have one bag that's slipped through, it won't happen again.
This may cause a slight issue for Archivematica bags; we'll cross that bridge if/when we come to it.
> Don't allow storing new files with filenames that end with a trailing `.`

- terraform/infra/endpoints.tf
- terraform/infra/locals.tf
- terraform/infra/terraform.tf
- terraform/stack_prod/locals.tf
- terraform/stack_prod/terraform.tf
- terraform/stack_staging/locals.tf
- terraform/stack_staging/terraform.tf
Part of wellcomecollection/platform#4802
We've rearranged some of our Terraform configs to reduce the amount of cross-account coupling. Changing the storage VPC shouldn't affect the storage VPC, etc.
This should be a no-op, but Alice is doing other stuff in Terraform so it may conflict in ways I haven't spotted.
> Use the new location of the VPC terraform state

- .buildkite/pipeline.yml
In order to provide a consistently up-to-date stage environment and to provide a basis for testing whether a release to production can be done safely, this change keeps stage up to date with the latest build of the storage service.
This change will naively trigger a stage deployment from the "latest" tag whenever a merge is made to master. This does not check if the storage service images have actually been updated in a merge - but the deployment tool will ensure deploys only occur when the latest tag has been changed.
> Automatically deploy api to stage from latest on merge to master

- monitoring/daily_reporter/requirements.in
- monitoring/daily_reporter/requirements.txt
- monitoring/daily_reporter/src/aws.py
- monitoring/daily_reporter/src/daily_reporter.py
- monitoring/daily_reporter/src/elasticsearch.py
- monitoring/daily_reporter/src/html_report.py
- monitoring/daily_reporter/src/ingests.py
- monitoring/daily_reporter/src/slack.py
- monitoring/daily_reporter/src/templates/report.html
- terraform/monitoring/lambda_daily_reporter.tf
- terraform/monitoring/provider.tf
- terraform/monitoring/s3_daily_reporter.tf
Closes https://github.com/wellcomecollection/platform/issues/4769
New features:
* Previously the daily reporter would only report on ingests that were updated in the last 2 days. It now additionally looks for ingests from any time which are in the "processing" or "accepted" states, which might indicate a stalled ingest.
* Stalled ingests are now flagged in the daily Slack message.
* It writes a colourful HTML report of the last two days of storage service activity, which is written to a public S3 bucket configured to do static website hosting: https://wellcomecollection-storage-daily-reporting.s3-eu-west-1.amazonaws.com/2020-09-30.html
> Rewrite the daily reporter to be more useful

- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/BagRegisterFeatureTest.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/fixtures/BagRegisterFixtures.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorkerTest.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/RegisterTest.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/StorageManifestServiceTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierTestCases.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/ReplicatedBagVerifierTestCases.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/services/BagReaderTestCases.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/BagBuilder.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/s3/S3BagBuilder.scala
Some tidy ups I spotted while reading bag register code. Nothing earth-shattering, but does reduce the line code and make things easier to follow.
> Clean up the construction of bags in tests

- indexer/reindex_bags_backlog.py
It's too big, and trying to index it causes the bags API to completely fall over when it tries to retrieve the bag.  Don't let somebody send it for indexing by accident.
Part of https://github.com/wellcomecollection/platform/issues/4796
> Don't reindex C&D with the regular bag indexer

- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/StorageManifestServiceTest.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/fixtures/BagReplicatorFixtures.scala
- bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/models/ReplicationRequestTest.scala
- bag_root_finder/src/test/scala/uk/ac/wellcome/platform/storage/bag_root_finder/fixtures/BagRootFinderFixtures.scala
- bag_tagger/src/test/scala/uk/ac/wellcome/platform/storage/bag_tagger/services/ApplyTagsTest.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/fixtures/BagUnpackerFixtures.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/BagUnpackerWorkerTest.scala
- bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/UnpackerMessageTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityCheckerTests.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/memory/MemoryFixityCheckerTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixtures/BagVerifierFixtures.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierTestCases.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierWorkerTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/ReplicatedBagVerifierTestCases.scala
- bag_versioner/src/test/scala/uk/ac/wellcome/platform/storage/bag_versioner/fixtures/BagVersionerFixtures.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/services/BagMatcherTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/OperationFixtures.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/StorageRandomThings.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/PayloadGenerators.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/ReplicaLocationGenerators.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/StorageManifestGenerators.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/ingests/services/IngestUpdaterTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/LargeResponsesTest.scala
- display/src/test/scala/uk/ac/wellcome/platform/archive/display/ingests/DisplayIngestTest.scala
- replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/fixtures/ReplicaAggregatorFixtures.scala
Part of https://github.com/wellcomecollection/platform/issues/4827. This is PR 1 of 2 – this is a bunch of cleanups that aren't random-related, but make it easier to apply in the next PR.
> General tidy-ups in the storage-service tests before using the new RandomGenerators

- bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorker.scala
- bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/services/Register.scala
- bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/RegisterTest.scala
- bag_tracker/src/main/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/AkkaTrackerClientBase.scala
- bag_tracker/src/main/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/BagTrackerClient.scala
- bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/AkkaBagTrackerClientTest.scala
- bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/CreateBagTestCases.scala
- bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/GetBagTestCases.scala
- bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/GetLatestBagTestCases.scala
- bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/ListVersionsTestCases.scala
Closes https://github.com/wellcomecollection/platform/issues/4834
The default is still to fail bags with unrecognised errors, so they're visible and we know to investigate and fix them – but we've knocked over the bags API recently, and having the pipeline handle it gracefully is better than pretending it won't happen again.
> If the bag tracker is unavailable, the bag register will retry the registration

- terraform/modules/service/bags/main.tf
- terraform/modules/service/base/main.tf
- terraform/modules/service/ingest/main.tf
- terraform/stack_prod/provider.tf
- terraform/stack_staging/provider.tf
This fixes an issue where not all services/tasks had tags as expected. This also prepares for https://github.com/wellcomecollection/terraform-aws-ecs-service/pull/29 by ignoring the deployment label at the provider level.
> Propagate deployment tags correctly

- terraform/modules/service/bags/main.tf
- terraform/modules/service/base/main.tf
- terraform/modules/service/ingest/main.tf
Keep in sync with latest - removes need to specify propagate tags.
Note: this terraform is applied.
> Use latest ECS terraform module

- bag_versioner/src/main/scala/uk/ac/wellcome/platform/storage/bag_versioner/services/BagVersioner.scala
- bag_versioner/src/main/scala/uk/ac/wellcome/platform/storage/bag_versioner/versioning/VersionPicker.scala
- bag_versioner/src/main/scala/uk/ac/wellcome/platform/storage/bag_versioner/versioning/VersionPickerError.scala
- bag_versioner/src/test/scala/uk/ac/wellcome/platform/storage/bag_versioner/fixtures/BagVersionerFixtures.scala
- bag_versioner/src/test/scala/uk/ac/wellcome/platform/storage/bag_versioner/fixtures/VersionPickerFixtures.scala
- bag_versioner/src/test/scala/uk/ac/wellcome/platform/storage/bag_versioner/services/BagVersionerTest.scala
- bag_versioner/src/test/scala/uk/ac/wellcome/platform/storage/bag_versioner/versioning/VersionPickerTest.scala
A failure to get a lock when setting a version should be retryable.
We have seen this issue when runnning https://github.com/wellcomecollection/storage-service/pull/762.
> Retry on lock failure in bag_versioner

- build.sbt
- project/Packager.scala
Currently these are dropping warnings in CI:
there are 21 keys that are not used by any other settings/tasks:[0J
* bag_indexer / composeNoBuild[0J
+- /var/lib/buildkite-agent/builds/buildkite-elasticstack-i-07028dbe4122c20cd-1/wellcomecollection/storage-service/project/Packager.scala:7[0J
> Remove some unused packager settings

- terraform/modules/critical/s3_replica_glacier.tf
- terraform/modules/critical/s3_replica_primary.tf
Although we have versioning enabled, we never actually delete the old versions once they're gone!
I've applied this in staging and it looks fine (although we don't actually enable versioning on the staging buckets); I'll apply in prod once this has been reviewed.
> Expire non-current versions in our permanent storage buckets

- scripts/ss_delete_bag.py
Closes https://github.com/wellcomecollection/storage-service/pull/777, part of wellcomecollection/platform#4878
This is my third/fourth pass at this, and this one finally looks good. We've made it quite tricky to delete bags, so undoing those protections takes a while. 😅 
This is a reviewable unit – it does all the checking that yes, you really want to delete this bag, and then purges it from the reporting cluster. I'll add the rest in another PR.
> Add a script for deleting bags

- indexer/bag_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/bags/BagIndexerWorker.scala
- indexer/bag_indexer/src/test/scala/uk/ac/wellcome/platform/archive/indexer/bag/BagIndexerWorkerTest.scala
For https://github.com/wellcomecollection/platform/issues/4873
It turns out the file finder/indexer already retries these errors.
> Retry not-found errors in the bag indexer

- scripts/ss_delete_bag.py
This ties together a bunch of neat pieces from the helper functions and the script – all the objects in permanent storage now get deleted. Scrubbing the DynamoDB record is next, but a bit more fiddly.
> Delete all the objects in S3 and Azure

- project/Dependencies.scala
In order to incorporate changes allowing consistent-read from dynamo stores, (that switch will be added in an incoming PR).
> Bump scala-libs version to latest

- bag_tracker/src/main/scala/uk/ac/wellcome/platform/archive/bag_tracker/storage/dynamo/DynamoStorageManifestDao.scala
- indexer/common/src/main/scala/uk/ac/wellcome/platform/archive/indexer/elasticsearch/IndexerWorker.scala
- project/Dependencies.scala
These changes were proposed to fix an issue indexing bags that is [likely to be something else](https://github.com/wellcomecollection/storage-service/pull/791). 
They're still a good idea though. 
This change:
- Makes the bag tracker use strongly consistent reads so we can be sure that we never report a bag in an incorrect state
- Makes the bag indexer retry on a non-zero delay if something goes wrong (a zero length delay is unhelpful if a dependent service is temporarily unavailable).
> Implement reindexing consistency and retry

- bag_tracker/src/main/scala/uk/ac/wellcome/platform/archive/bag_tracker/BagTrackerApi.scala
- bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/BagTrackerClientTestCases.scala
- bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/GetBagTestCases.scala
- bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/GetLatestBagTestCases.scala
- bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/ListVersionsTestCases.scala
- bag_versioner/src/test/scala/uk/ac/wellcome/platform/storage/bag_versioner/versioning/VersionPickerTest.scala
- bag_versioner/src/test/scala/uk/ac/wellcome/platform/storage/bag_versioner/versioning/dynamo/DynamoVersionRecordTest.scala
- bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/BagsApi.scala
- bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/LookupBagApiTest.scala
- bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/LookupBagVersionsApiTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/models/ExternalIdentifier.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/http/LookupExternalIdentifier.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/models/ExternalIdentifierTest.scala
Closes https://github.com/wellcomecollection/platform/issues/4889
This PR:
* Updates the bags API and bag tracker to support bags with spaces in the identifier
* Blocks adding any other unexpected characters as part of new external identifiers
> Support spaces, and only spaces, in the external identifier

- terraform/critical_prod/locals.tf
- terraform/critical_prod/main.tf
- terraform/critical_staging/locals.tf
- terraform/critical_staging/main.tf
For https://github.com/wellcomecollection/platform/issues/4895
Rather than specifying individual roles, which we need to manage, just grant blanket read permission to the entire account.  We can assign permissions to individual roles within those accounts, but without having to keep modifying this block.
We've discussed this change in the past with folks at Digirati, and tested it on some Digirati roles, but apparently never got around to doing it properly.
> Grant blanket read permissions to other AWS accounts

- bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/GetBagTestCases.scala
- bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/GetLatestBagTestCases.scala
- bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/ListVersionsTestCases.scala
This is breaking tests on master; I'm not sure why it wasn't caught by #795.
> Fix a couple of missing .right.value in tests

- monitoring/daily_reporter/src/ingests.py
- monitoring/daily_reporter/src/test_ingests.py
If a bag fails to unpack and the storage service only says `"Unpacking failed"`, we should be prompted to investigate this by the daily report.
This patch moves those errors from "failure (user error)" to "failure (unknown reason)".
If the bag unpacker includes an explanation (e.g. "the object doesn't exist"), it's still treated as a user error.
For https://github.com/wellcomecollection/platform/issues/4911
> Unexplained bag unpacker errors get flagged by the daily report

- bag_tracker/src/main/scala/uk/ac/wellcome/platform/archive/bag_tracker/storage/StorageManifestDao.scala
- bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/storage/StorageManifestDaoTestCases.scala
As part of https://github.com/wellcomecollection/platform/issues/4913, I’m looking at the Maxima class from scala-libs – and in particular, where it's used.
I discovered this method in storage-service is only used in the tests, so we can safely delete it.
> Remove the unused getLatestVersion method

- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifier.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/azure/AzureReplicatedBagVerifier.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/s3/S3BagVerifier.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/verify/steps/VerifyBagDeclaration.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierTestCases.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/verify/steps/VerifyBagDeclarationTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/BagBuilder.scala
The first "required element" [in the BagIt spec](https://tools.ietf.org/html/rfc8493#section-2.1.1) is a "Bag Declaration", aka bagit.txt:
> The "bagit.txt" tag file MUST consist of exactly two lines in this order:
>
> ```
> BagIt-Version: M.N
> Tag-File-Character-Encoding: ENCODING
> ```
We didn't have any code that checked for the presence of this file; now we do. I'm running a script to check we have an appropriate bagit.txt file in all the existing bags.
> Verify that our bags include a bag declaration

- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifier.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/verify/steps/VerifyFilenames.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/verify/steps/VerifyLegalFilenames.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierTestCases.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/verify/steps/VerifyFilenamesTest.scala
- bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/verify/steps/VerifyLegalFilenamesTest.scala
- common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/BagBuilder.scala
Second part of https://github.com/wellcomecollection/platform/issues/4931, follows #807 
I think all our bags already follow these two rules. The "data/" rule is required by the BagIt spec and one we've not been rigidly enforcing; tag files in the root is a convention we've adopted that we should discuss if we ever want to break (rather than letting it slip through quietly).
> Verify that payload files are in data/, tag files are in the root

- project/Dependencies.scala
Some slightly better logging from SQSStream, and removing some deprecated EnrichConfig methods which shouldn't have an effect.
> Update scala-libs to v25.1.0

- project/Dependencies.scala
Although we use CloudWatch Metrics, it's entirely through scala-monitoring (which already uses the V2 SDK).
I don't think we need this explicit dependency here.
Closes https://github.com/wellcomecollection/platform/issues/4786
> Remove the explicit dependency on the CloudWatch Metrics SDK

- project/Dependencies.scala
This will roll back the AWS SDK updates, which have completely hosed the staging service.
> Bump to scala-libs 26.2.0

- bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/BagsApi.scala
- bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/LookupBagApiTest.scala
- bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/LookupBagVersionsApiTest.scala
- common/src/main/scala/uk/ac/wellcome/platform/archive/common/http/LookupExternalIdentifier.scala
We throw an IllegalArgumentException if you try to look up a bag with an external identifier that doesn't match our internal rules -- but these rules aren't part of the storage service spec, and we should 404 rather than returning a 500 error.
I've only done this in the public-facing API – you should never get as far as calling the internal bag tracker API with an invalid external identifier.
Closes https://github.com/wellcomecollection/platform/issues/5049
> Return a 404, not a 500 if somebody looks up an invalid external ID

- bag_tagger/src/main/scala/uk/ac/wellcome/platform/storage/bag_tagger/services/TagRules.scala
- bag_tagger/src/test/scala/uk/ac/wellcome/platform/storage/bag_tagger/BagTaggerFeatureTest.scala
- bag_tagger/src/test/scala/uk/ac/wellcome/platform/storage/bag_tagger/fixtures/BagTaggerFixtures.scala
- bag_tagger/src/test/scala/uk/ac/wellcome/platform/storage/bag_tagger/services/TagRulesTest.scala
- terraform/modules/critical/s3_replica_primary.tf
For https://github.com/wellcomecollection/platform/issues/5124
Quick recap for those unfamiliar with this feature:
The **bag tagger** gets a notification when a bag is successfully stored in the storage service – similar to the METS adapter in the catalogue.
It looks through all the files in the bag, and it decides whether to add [tags to the S3 objects](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-tagging.html). (We don't currently apply tags to objects in Azure, because [their tagging implementation was added after we did the Azure work](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-index-how-to?tabs=azure-portal).) We use those tags to trigger S3 lifecycle rules, in particular to cycle large preservation files to Glacier, with access copies staying …
> Lifecycle TIFFs to Glacier storage

- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityChecker.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/azure/AzureFixityChecker.scala
- bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/s3/S3FixityChecker.scala
Last night, we had a failure in one of the S3 bag verifiers because the connection timed out midway through reading an object. The object in question was multiple gigabytes in size (an MXF file).
This patch is my attempt to make this sort of failure less likely in future.
---
A quick refresher:
A timeout when reading an object isn't an uncommon failure mode: the larger the file, the longer you need to hold the screen open, the higher the risk of something dropping in the middle. To get around this in the bag _unpacker_, we divide large objects into smaller pieces, and then stitch the pieces back together in memory. Additionally, we read all the bytes for each piece immediately, so we're not holding a connection open for a long time. We also have retry logic around reading each piece.
I …
> Use the LargeStreamReader to increase reliability a little further

- terraform/infra/.terraform.lock.hcl
- terraform/infra/dynamo_deleted_bags.tf
- terraform/infra/provider.tf
- terraform/infra/s3_infra.tf
Turns out I added a couple of lifecycle rules in a PR that never got merged, so if you'd planned/applied Terraform as in master, you'd undo the rules and delete the table that records all the deleted bags. Oops!
> Bring the infra Terraform in line with what's actually deployed

- python_client/CHANGELOG.md
- python_client/src/wellcome_storage_service/secrets.py
- python_client/src/wellcome_storage_service/version.py
You can use boto3 to fetch the storage service OAuth secrets from Secrets Manager -- but that's not the only auth mechanism available. You can also get secrets from environment variables, at which point having boto3 installed is unnecessary.
Requiring boto3 was causing particular issues for the ingest inspector, because it has to install all its packages on startup, and boto3 brings in quite a few of its own dependencies.  Allowing us to run the ingest inspector without boto3 should make it start up quite a bit faster.
Fixed while looking at https://github.com/wellcomecollection/platform/issues/5148
> Only import boto3 when it's required

- monitoring/daily_reporter/src/ingests.py
This has been the failures in the last two days – but a 404 callback is (probably) an issue with the user giving us a bad callback URL or letting it expire, not a storage service error.
> Don't count a 404 callback as an unexpected failure in the reporter

- monitoring/daily_reporter/src/ingests.py
Based on today's errors, none of which are actually storage service errors, but reporting errors – this gets the report back to green.
> A couple of fixes in the daily reporter

- terraform/critical_prod/outputs.tf
- terraform/critical_staging/outputs.tf
- terraform/modules/critical/outputs.tf
- terraform/modules/critical/s3_static_content.tf
- terraform/modules/critical/vhs_manifests.tf
- terraform/modules/stack/api/static_objects.tf
- terraform/modules/stack/main.tf
- terraform/modules/stack/s3_static_content.tf
- terraform/modules/stack/variables.tf
- terraform/stack_prod/main.tf
- terraform/stack_staging/main.tf
This is an optimisation I noticed while looking at https://github.com/wellcomecollection/platform/issues/5206
The static content bucket is very definitely not persistent storage.
> Move the static content bucket to the stack module

- terraform/modules/stack/iam_policy_document.tf
- terraform/modules/stack/iam_role_policy.tf
- terraform/modules/stack/variables.tf
- terraform/stack_prod/locals.tf
- terraform/stack_prod/main.tf
- terraform/stack_staging/locals.tf
- terraform/stack_staging/main.tf
This makes the module more generic – it doesn't assume the use of Goobi and Archivematica as the sources of uploaded bags.  As a bonus, it means we only have to attach one IAM policy, instead of two.
Another small step towards https://github.com/wellcomecollection/platform/issues/5206
> Pass a list of upload_bucket_arns into the stack module

- terraform/modules/stack/dynamo.tf
- terraform/modules/stack/iam_policy_document.tf
- terraform/modules/stack/iam_role_policy.tf
- terraform/modules/stack/main.tf
- terraform/modules/stack/messaging.tf
- terraform/modules/stack/variables.tf
For the DAMS prototype project, we don't want to require an Azure account and do replication into Azure.  Make it optional, so if the caller doesn't specify an Azure Blob container, we won't replicate there.
I had to do a small state change in our stacks to make this a no-op plan:
$ terraform state mv module.stack_prod.module.replicator_verifier_azure module.stack_prod.module.replicator_verifier_azure[0]
I haven't tested this with the "no Azure" configuration, because I don't want to affect our existing environments -- I'm hoping to try it in the DAMS prototype account soon.
For https://github.com/wellcomecollection/platform/issues/5206
> Make the Azure replicator optional

- terraform/modules/service/base/iam.tf
- terraform/modules/stack/iam_policy_document.tf
- terraform/modules/stack/iam_role_policy.tf
- terraform/modules/stack/main.tf
- terraform/modules/stack/replifier/iam_replicator.tf
- terraform/modules/stack/replifier/iam_verifier.tf
- terraform/modules/stack/replifier/variables.tf
This is what we do in the pipeline repo, which seems like a better way to do it – you only need to define it once, not N times.
Discoveries:
* The ingests service was given access to CloudWatch Metrics *twice*
* The file finder/indexer weren't given any access at all
> Add a CloudWatch metrics policy in the base module, not for every service

- terraform/modules/service/bags/main.tf
- terraform/modules/service/bags/variables.tf
- terraform/modules/service/base/main.tf
- terraform/modules/service/base/variables.tf
- terraform/modules/service/ingest/main.tf
- terraform/modules/service/ingest/variables.tf
- terraform/modules/service/worker/main.tf
- terraform/modules/service/worker/variables.tf
- terraform/modules/stack/main.tf
- terraform/modules/stack/replifier/main.tf
- terraform/modules/stack/replifier/variables.tf
- terraform/modules/stack/variables.tf
- terraform/stack_prod/main.tf
- terraform/stack_staging/main.tf
For https://github.com/wellcomecollection/platform/issues/5206, requires https://github.com/wellcomecollection/terraform-aws-ecs-service/pull/35
I'll need to update to a released version of terraform-aws-ecs-service before I merge this.
> Wire up config to allow picking a different Fluentbit container

- terraform/modules/service/base/outputs.tf
- terraform/modules/service/worker/main.tf
You can't register an autoscaling definition until the associated service has been created, but the previous approach would allow Terraform to create them in parallel -- and sometimes it would get the wrong order.
This change should force Terraform to create the service THEN create the autoscaling definition.
It's a no-op in the existing storage service, but should make planning a bit easier for the prototype.
For https://github.com/wellcomecollection/platform/issues/5206
> Make the autoscaling module dependent on the service module

- bag_register/Dockerfile
- bag_replicator/Dockerfile
- bag_root_finder/Dockerfile
- bag_tagger/Dockerfile
- bag_tracker/Dockerfile
- bag_unpacker/Dockerfile
- bag_verifier/Dockerfile
- bag_versioner/Dockerfile
- bags_api/Dockerfile
- indexer/bag_indexer/Dockerfile
- indexer/file_finder/Dockerfile
- indexer/file_indexer/Dockerfile
- indexer/ingests_indexer/Dockerfile
- ingests/ingests_api/Dockerfile
- ingests/ingests_tracker/Dockerfile
- ingests/ingests_worker/Dockerfile
- notifier/Dockerfile
- replica_aggregator/Dockerfile
The typesafe_config_base image has a couple of issues:
- It fetches ECS_METADATA_URI on startup, even though we no longer need to do this – it's a holdover from an old approach to doing logging.
- It obscures exactly how the image is being built, and what's available.
- Actually finding the Dockerfile for this image is very hard to impossible.
Since we don't need it, let's simplify the Dockerfile.
For https://github.com/wellcomecollection/platform/issues/4619
> Remove the typesafe_config_base container

- demo/terraform/README.md
- demo/terraform/bump_refs.py
- demo/terraform/demo_stack/cognito.tf
- demo/terraform/demo_stack/elastic.tf
- demo/terraform/demo_stack/metadata_stores.tf
- demo/terraform/demo_stack/stack.tf
- demo/terraform/demo_stack/topics.tf
- demo/terraform/main.tf
Me, last week: _"I've made a demo of the storage service. It just works™!"_
Literally anybody trying to use it: _"No. No it does not."_
---
We use Git commit refs to refer to the modules throughout the demo because they're consistent, reproducible references. For our other Terraform modules we use tags and semantic versioning (e.g. `v1.2.3`), but we don't have any versioning like that set up in the storage service repo yet.
It turns out the demo currently points at a commit ref that no longer exists, oops.
It worked on my machine because I'd run `terraform init` when the commit did exist, Terraform cached the module, and then didn't try to fetch it again later. Anybody else trying to init the demo would get an error trying to fetch a non-existent commit.
This patch adds a script to …
> Fix the refs in the demo stack, add a script for bumping them

- demo/terraform/README.md
- demo/terraform/demo_stack/metadata_stores.tf
- demo/terraform/demo_stack/stack.tf
- demo/terraform/main.tf
- terraform/modules/service/bags/main.tf
- terraform/modules/service/base/main.tf
- terraform/modules/service/ingest/main.tf
- terraform/modules/service/worker/main.tf
Brings in https://github.com/wellcomecollection/terraform-aws-ecs-service/pull/39, so hopefully you can spin up the logging container outside eu-west-1.
> Bump the version of terraform-aws-ecs-service to v3.9.2

- demo/terraform/README.md
- demo/terraform/demo_stack/cognito.tf
- demo/terraform/demo_stack/elastic.tf
- demo/terraform/demo_stack/metadata_stores.tf
- demo/terraform/demo_stack/stack.tf
- demo/terraform/demo_stack/variables.tf
- demo/terraform/main.tf
- docs/howto/ingest-a-bag.md
- terraform/modules/critical/metadata_stores/dynamo_ingests.tf
- terraform/modules/critical/metadata_stores/vhs_manifests.tf
- terraform/modules/queue/main.tf
- terraform/modules/queue/variables.tf
- terraform/modules/service/ingest/main.tf
- terraform/modules/stack/main.tf
- terraform/modules/stack/messaging.tf
- terraform/modules/stack/replifier/messaging.tf
- terraform/modules/stack/replifier/variables.tf
- terraform/modules/stack/variables.tf
For https://github.com/wellcomecollection/platform/issues/5241
This patch:
* Will delete secrets immediately when the demo stack is torn down
* Use Scala apps that don't hard-code their region as `eu-west-1`
* Use a version of the SQS queue module that doesn't need a region variable set (https://github.com/wellcomecollection/terraform-aws-sqs/pull/7)
> Continue to make the storage-service more region agnostic

- bag_verifier/src/main/scala/weco/storage_service/bag_verifier/verify/steps/VerifyBagDeclaration.scala
- bag_verifier/src/test/scala/weco/storage_service/bag_verifier/services/BagVerifierTestCases.scala
- bag_verifier/src/test/scala/weco/storage_service/bag_verifier/verify/steps/VerifyBagDeclarationTest.scala
- common/src/test/scala/weco/storage_service/bagit/services/BagInfoParserTest.scala
- common/src/test/scala/weco/storage_service/fixtures/BagBuilder.scala
For https://github.com/wellcomecollection/storage-service/issues/894
Previously we had an overly strict regex for matching the Bag Declaration (bagit.txt):
```scala
private val declaration = new Regex(
"BagIt-Version: \\d\\.\\d+\nTag-File-Character-Encoding: UTF-8\n?"
)
```
Now we defer to Scala to split lines in bagit.txt for us (`String.lines`), so we don't have to worry about supporting different line endings.  This means we get support for Windows line endings for "free".
This approach also means we can provide slightly better error messages when we don't accept the Bag Declaration as supplied, e.g. "encoding must be UTF-8" or "not correctly formatted".
Once this patch is merged, I'll try a Windows bag in the staging environment and see if anything else breaks; if not, I'll close the …
> Support Windows line endings in the bag verifier

- .buildkite/pipeline.yml
Running this step on pull requests is a waste of CPU cycles.
> Only run "tag commit as latest" on the main branch

- demo/terraform/README.md
- demo/terraform/demo_stack/metadata_stores.tf
- demo/terraform/demo_stack/stack.tf
- demo/terraform/main.tf
- terraform/modules/resource/outputs.tf
- terraform/modules/stack/api/gateway.tf
- terraform/modules/stack/api/gateway_responses.tf
- terraform/modules/stack/api/outputs.tf
- terraform/modules/stack/api/response_4xx/main.tf
- terraform/modules/stack/api/response_5xx/main.tf
This PR fixes an intermittent issue that can occur on initial Terraform deployments — the API Gateway Deployment can be created before all of the API resources are defined, so things like authentication or API resources/methods may not be present in the Deployment. It also avoids a theoretical problem in that future changes to API resources currently don't trigger the creation of a new Deployment, so API changes wouldn't be visible without manual intervention to update the Deployment.
The fix is to make the relationship between API Gateway resources (`aws_api_gateway_method`,
`aws_api_gateway_resource`, etc) explicit, so that Terraform creates/updates them prior to `aws_api_gateway_deployment`, and also re-creates the Deployment if the resources it indirectly contains are modified. …
> Ensure API Gateway Deployments contain all resources

- bag_verifier/src/test/scala/weco/storage_service/bag_verifier/storage/s3/S3LocatableTest.scala
- common/src/main/scala/weco/storage_service/bagit/models/BagFetch.scala
- common/src/test/scala/weco/storage_service/bagit/models/BagFetchTest.scala
This slightly improves the error if you have a space in the URI
Error loading fetch.txt: URI is incorrectly formatted on line 1.
Spaces should be URI-encoded: http://example.org/abc def - data/example.txt
We also include the line number for other URI parsing errors, e.g.
Error loading fetch.txt: URI is incorrectly formatted on line 1.
Illegal character in path at index 0: {uri} - data/example.txt
Plus handling percent characters in the URI to properly adhere to the BagIt RFC.
> Improve our handling of URI encoding in fetch.txt

- bag_verifier/src/test/scala/weco/storage_service/bag_verifier/services/BagVerifierTestCases.scala
- common/src/main/scala/weco/storage_service/bagit/services/BagReader.scala
- common/src/main/scala/weco/storage_service/checksum/ChecksumAlgorithm.scala
- common/src/test/scala/weco/storage_service/bagit/services/BagReaderTestCases.scala
For #900, follows #909.
This patch means that whenever we read a bag from S3 or Azure, we'll read all the available manifests and check they're consistent. The applications will only look at the SHA256 manifest, but the other manifests will be sitting in-memory waiting to be used.
In places we're taking a stricter reading of the BagIt spec in a way that I think is mostly fine – e.g. the BagIt spec says you SHOULD use the same algorithms for payload and tag manifests, but doesn't actually require it. This code does require they're the same.
(The BagIt spec also lists tag manifests as an optional element, but we require them.)
> Read multiple checksums in the BagReader

- bag_verifier/src/main/scala/weco/storage_service/bag_verifier/verify/steps/VerifyPayloadOxum.scala
- bag_verifier/src/test/scala/weco/storage_service/bag_verifier/fixity/FixityCheckerTagsTestCases.scala
- bag_verifier/src/test/scala/weco/storage_service/bag_verifier/fixity/FixityCheckerTestCases.scala
- bag_verifier/src/test/scala/weco/storage_service/bag_verifier/fixity/s3/S3FixityCheckerTest.scala
- bag_verifier/src/test/scala/weco/storage_service/bag_verifier/services/s3/S3BagVerifierTest.scala
- common/src/main/scala/weco/storage_service/bagit/models/BagManifest.scala
- common/src/main/scala/weco/storage_service/checksum/MismatchedChecksum.scala
- common/src/main/scala/weco/storage_service/checksum/MultiChecksum.scala
- common/src/main/scala/weco/storage_service/checksum/MultiManifestChecksum.scala
- common/src/test/scala/weco/storage_service/checksum/MultiChecksumTest.scala
For #900.
I'm continuing to write this in small pieces, because the bag verifier is such a critical service and I don't want to muck it up. This PR continues to rearrange some pieces to prepare for doing verification of multiple checksums.
Most of it is just refactoring or clean-ups; the one big change is:
```diff
case class MultiChecksum(md5, sha1, sha256, sha512: ChecksumValue) {
-  def compare(manifestChecksum: MultiManifestChecksum): Boolean
+  def compare(manifestChecksum: MultiManifestChecksum): Either[Seq[MismatchedChecksum], Unit]
...
}
```
This is to enable better error reporting in a subsequent patch: rather than saying "some of the checksums were different", we can say *which* checksums were different.
> Minor tweaks stepping towards a multi-checksum verifier

- bag_verifier/src/main/scala/weco/storage_service/bag_verifier/fixity/FailedChecksum.scala
- bag_verifier/src/main/scala/weco/storage_service/bag_verifier/fixity/FixityChecker.scala
- bag_verifier/src/main/scala/weco/storage_service/bag_verifier/fixity/FixityTagChecker.scala
- bag_verifier/src/main/scala/weco/storage_service/bag_verifier/fixity/azure/AzureFixityChecker.scala
- bag_verifier/src/test/scala/weco/storage_service/bag_verifier/fixity/FixityCheckerTestCases.scala
- bag_verifier/src/test/scala/weco/storage_service/bag_verifier/services/BagVerifierTestCases.scala
- common/src/main/scala/weco/storage_service/checksum/MismatchedChecksum.scala
Another small step towards #900. The key here is changing how we do tags – right now we only write a single fixity tag for every object, but in future we'll write multiple tags – one per manifest. This PR rearranges some of the tag-related pieces to deal with multiple tags, where right now it's just the degenerate case of a single-item list. This should make adding multiple tags a smaller change.
> Continue inching towards a multi-checksum bag verifier

- bag_verifier/src/main/scala/weco/storage_service/bag_verifier/fixity/bag/BagExpectedFixity.scala
- common/src/main/scala/weco/storage_service/bagit/models/MatchedLocation.scala
- common/src/main/scala/weco/storage_service/bagit/services/BagMatcher.scala
- common/src/test/scala/weco/storage_service/bagit/services/BagMatcherTest.scala
Another tiny step towards #900.
Currently the `MatchedLocation` case class only holds a single checksum; now it holds every checksum in the bag and has a back-compatibility shim to return just one checksum. In the next patch I'll update the bag verifier to read and use this multi-checksum, but I'm still keeping these patches small so they can be easily reviewed.
> Use multiple checksums in the BagMatcher

- bag_verifier/src/main/scala/weco/storage_service/bag_verifier/fixity/ExpectedFileFixity.scala
- bag_verifier/src/main/scala/weco/storage_service/bag_verifier/fixity/FixityChecker.scala
- bag_verifier/src/main/scala/weco/storage_service/bag_verifier/fixity/FixityTagChecker.scala
- bag_verifier/src/main/scala/weco/storage_service/bag_verifier/fixity/bag/BagExpectedFixity.scala
- bag_verifier/src/test/scala/weco/storage_service/bag_verifier/fixity/FixityCheckerTagsTestCases.scala
- bag_verifier/src/test/scala/weco/storage_service/bag_verifier/fixity/FixityCheckerTestCases.scala
- bag_verifier/src/test/scala/weco/storage_service/bag_verifier/fixity/FixityCheckerTests.scala
- bag_verifier/src/test/scala/weco/storage_service/bag_verifier/fixity/bag/BagExpectedFixityTest.scala
- bag_verifier/src/test/scala/weco/storage_service/bag_verifier/generators/FixityGenerators.scala
- common/src/main/scala/weco/storage_service/bagit/models/MatchedLocation.scala
- common/src/main/scala/weco/storage_service/bagit/services/BagMatcher.scala
- common/src/test/scala/weco/storage_service/bagit/services/BagMatcherTest.scala
- common/src/test/scala/weco/storage_service/generators/BagGenerators.scala
- common/src/test/scala/weco/storage_service/generators/StorageRandomGenerators.scala
For #900. This patch changes the behaviour of the bag verifier (specifically, the FixityChecker trait) so it now looks at every checksum on a file, rather than just the SHA-256 checksum.
I've tried to keep this patch as small as I can so it can be reviewed carefully, but it's a pretty core piece of the verifier. 😅
> Verify every checksum in the bag verifier

- bag_register/src/main/scala/weco/storage_service/bag_register/services/S3StorageManifestService.scala
- bag_register/src/test/scala/weco/storage_service/bag_register/services/StorageManifestServiceTest.scala
- common/src/main/scala/weco/storage_service/bagit/models/Bag.scala
- common/src/main/scala/weco/storage_service/bagit/models/UnreferencedFiles.scala
- common/src/main/scala/weco/storage_service/bagit/services/BagReader.scala
- common/src/main/scala/weco/storage_service/checksum/ChecksumAlgorithm.scala
- common/src/test/scala/weco/storage_service/generators/StorageRandomGenerators.scala
For #900. This updates the bag register to be aware of multiple checksums, and it picks the best available checksum – so we'll start seeing SHA-512 instead of SHA-256 in storage manifests returned by Goobi.
There's a reasonable argument that we should be tracking all the checksums within the storage manifests (and consequently the reporting cluster), but that means migrating all the existing storage manifests. We might tack it onto the process of verifying the SHA-512 checksums in the Goobi manifests, if we choose to do that.
I think this is the last feature change – the final patch will be clearing out all the backward compatibility code.
> Use multiple checksums in the bag register

- terraform/modules/service/bags/main.tf
- terraform/modules/service/base/main.tf
- terraform/modules/service/ingest/main.tf
- terraform/modules/service/worker/main.tf
- terraform/stack_prod/locals.tf
- terraform/stack_prod/provider.tf
- terraform/stack_prod/terraform.tf
- terraform/stack_staging/.terraform.lock.hcl
- terraform/stack_staging/locals.tf
- terraform/stack_staging/provider.tf
- terraform/stack_staging/terraform.tf
This uses the new SQS DLQ alerting infra from https://github.com/wellcomecollection/platform-infrastructure/pull/221
If/when another message ends up on a DLQ in the storage service, we should now get alerts about it in Slack.
> Use the new per-account SQS DLQ alarm topic

- terraform/modules/stack/main.tf
- terraform/modules/stack/variables.tf
- terraform/stack_prod/locals.tf
- terraform/stack_prod/main.tf
- terraform/stack_staging/locals.tf
- terraform/stack_staging/main.tf
This means we'll get alerts of API Gateway errors for the storage service, which we haven't had before.
Requires https://github.com/wellcomecollection/platform-infrastructure/pull/232, part of wellcomecollection/platform#5245
> Use the new API Gateway alarm topics

- terraform/modules/lambda/lambda_function.tf
- terraform/modules/lambda/variables.tf
- terraform/monitoring/end_to_end_test_lambda/main.tf
- terraform/monitoring/end_to_end_test_lambda/variables.tf
- terraform/monitoring/lambda_daily_reporter.tf
- terraform/monitoring/lambda_end_to_end_bag_test.tf
- terraform/monitoring/locals.tf
- terraform/monitoring/terraform.tf
Builds on wellcomecollection/platform-infrastructure#233, for wellcomecollection/platform#5245
Previously we didn't have any alarms set up for these Lambdas.
> Add alarms for the Lambda functions in the storage account

- bag_verifier/src/main/scala/weco/storage_service/bag_verifier/fixity/FileFixityResult.scala
- bag_verifier/src/main/scala/weco/storage_service/bag_verifier/fixity/FixityChecker.scala
- bag_verifier/src/test/scala/weco/storage_service/bag_verifier/fixity/FixityCheckerTests.scala
Closes https://github.com/wellcomecollection/storage-service/issues/932
A BagIt bag contains manifests with a list of files and their expected checksums, e.g. this is an MD5 manifest:
```
c40e6411794ca9f1fdb84729bf99c2a263fb54fa374bf403f24e1be70707a56a  data/README.txt
```
The bag verifier reads the manifest, and verifies that every object matches its checksum in the manifest.
The bag verifier adds a tag to the object after it's been successfully verified, recording the checksum. e.g. for this object we'd add the tag:
```
Content-MD5 => c40e6411794ca9f1fdb84729bf99c2a263fb54fa374bf403f24e1be70707a56a
```
There are two main reasons we do this:
- If the bag verifier gets interrupted midway through a bag with lots of files, it can look at the tag and see "I've already verified this object, I …
> Allow writing fixity tags to soft-fail in the verifier

- bag_register/src/test/scala/weco/storage_service/bag_register/BagRegisterFeatureTest.scala
- bag_tracker/src/main/scala/weco/storage_service/bag_tracker/client/BagTrackerClient.scala
- bag_tracker/src/main/scala/weco/storage_service/bag_tracker/storage/StorageManifestDao.scala
- bag_tracker/src/test/scala/weco/storage_service/bag_tracker/storage/StorageManifestDaoTestCases.scala
- common/src/test/scala/weco/storage_service/generators/IngestGenerators.scala
- ingests/ingests_tracker/src/test/scala/weco/storage_service/ingests_tracker/IngestsTrackerApiFeatureTest.scala
- ingests/ingests_tracker/src/test/scala/weco/storage_service/ingests_tracker/tracker/IngestTrackerTestCases.scala
- ingests/ingests_tracker/src/test/scala/weco/storage_service/ingests_tracker/tracker/dynamo/DynamoIngestTrackerTest.scala
- project/Dependencies.scala
- terraform/modules/stack/main.tf
- terraform/stack_prod/provider.tf
- terraform/stack_staging/provider.tf
For https://github.com/wellcomecollection/platform/issues/5287, closes https://github.com/wellcomecollection/storage-service/pull/939
The final step in storing a bag is the "bag register". This gets a notification about a fully replicated and verified bag, then it constructs a "storage manifest" which it stores in the VHS. The manifest is a JSON description of:
* the bag
* the files it contains, their size and checksum
* the replica locations (S3 buckets, Blob containers)
A bag can have multiple versions, so the DynamoDB table looks something like this:
```
id              | version | location
----------------+---------+------------------------------------------
digitised/b1234 | v1      | s3://storage-manifests-vhs/b1234/v1.json
digitised/b1234 | v2      | …
```
> Make bag register idempotent

- terraform/modules/service/base/main.tf
- terraform/modules/service/worker/main.tf
Enabling the ECS deployment circuit breaker , turns on detection of repeated failed attempts to start tasks as part of an ECS deployment and will "cancel" a deployment if a particular threshold for failed tasks is met.
See: https://github.com/wellcomecollection/platform/issues/5306
Note: This is applied.
> Update ECS service module to version with circuit breaker protection

- terraform/modules/stack/replifier/iam_replicator.tf
- terraform/stack_prod/.terraform.lock.hcl
The replicator is a service that does bulk copying of objects from one S3 bucket to another.  But we don't want to overwrite/replace objects in the destination bucket if they already exist.
* if they're the same we can save ourselves a write
* if they're different then something has gone extremely wrong
So the replicator queries for the destination object before it starts the copy.
What happens if there's no existing object?  If you call GetObject on a non-existent object, one of two things can happen:
*   If you have List* permissions, S3 returns a 404 Not Found
*   If you don't have List* permissions, S3 returns a 401 Not Authorized (to avoid leaking information about bucket contents in 404s)
It turns out we'd given the replicator Get* and Put* permissions on the destination bucket, but …
> Give the replicators List* permissions

- .buildkite/pipeline.deploy-prod.yml
This step runs as part of the "deploy prod" pipeline… and triggers another "deploy prod" pipeline.
This is obviously wrong.
> Don't trigger infinite prod deploys

- terraform/modules/service/bags/main.tf
- terraform/modules/service/bags/variables.tf
- terraform/modules/service/ingest/main.tf
- terraform/modules/stack/main.tf
I had a look at the CPU/memory metrics for the last 6 weeks, and they're mostly over-provisioned.  Cutting their size by half should save us ~$230 in compute costs per month, and our monitoring will notice if we do something that breaks them.
> Reduce the size of the "always on" tasks by half

- terraform/README.md
- terraform/modules/stack/iam_policy_document.tf
- terraform/modules/stack/messaging.tf
- terraform/modules/stack/variables.tf
- terraform/stack_prod/locals.tf
- terraform/stack_prod/main.tf
- terraform/stack_staging/locals.tf
- terraform/stack_staging/main.tf
~This change is already applied; this PR is just for visibility.~
Okay it wasn't, but now it is.
I've also added a few notes on how the storage service Terraform is organised, and tried to make the cross-account SNS subscriptions a bit more obvious.
> Allow Digirati to subscribe to notifications from the staging service

- bag_replicator/src/main/resources/application.conf
- scripts/ss_retry_unpacking.py
- terraform/modules/stack/main.tf
- terraform/modules/stack/messaging.tf
- terraform/modules/stack/replifier/main.tf
- terraform/modules/stack/replifier/messaging.tf
- terraform/modules/stack/replifier/variables.tf
For https://github.com/wellcomecollection/storage-service/issues/993
This reduces the max tasks in the Azure replicator in prod from 10 to 8, plus makes sure we actually configure replicator locks properly (i.e. not the default of 3 minutes). We'll probably want to back out these changes again later, but I hope they'll stave off any more intermittent failures.
> Reduce the Azure replicator concurrency to avoid intermittent issues

- bag_replicator/src/main/scala/weco/storage_service/bag_replicator/replicator/Replicator.scala
- bag_replicator/src/main/scala/weco/storage_service/bag_replicator/replicator/azure/AzureReplicator.scala
- bag_replicator/src/main/scala/weco/storage_service/bag_replicator/replicator/s3/S3Replicator.scala
- bag_replicator/src/test/scala/weco/storage_service/bag_replicator/replicator/ReplicatorTestCases.scala
For #993. This change doesn't affect much code, but it requires quite a lot of context to understand.
---
The bag replicator copies bags around, or more specifically prefixes. For example, it might get a request
> copy bag `s3://temporary-storage/b1234/v1` to `s3://permanent-storage/b1234/v1`
We don't want the replicator to overwrite existing objects, and we can't enforce this in S3 itself. If you call PutObject twice for the same key, S3 will happily write both versions of the object. We do have the bag verifier to check the bag after it's been written, but we'd rather not have multiple versions of individual objects. If each object has exactly one version, everything gets easier to reason about.
(Or rather, we can using S3 Object Lock and write-once-read-many (WORM), but we don't have …
> Always check for existing objects in the prefix when replicating

- python_client/setup.py
- python_client/src/wellcome_storage_service/__init__.py
- python_client/src/wellcome_storage_service/_utils.py
- python_client/src/wellcome_storage_service/downloader.py
- python_client/src/wellcome_storage_service/exceptions.py
- python_client/src/wellcome_storage_service/version.py
- python_client/tests/conftest.py
- python_client/tests/test_bags.py
- python_client/tests/test_downloader.py
- python_client/tests/test_ingests.py
- python_client/tests/test_oauth.py
- python_client/tests/test_utils.py
- scripts/ss_download_bag.py
- scripts/ss_get_bag.py
I suspect the logic for deciding when to fetch a token was a bit borked; this changes it so we fetch a new token if:
1. we don't have one
2. the existing token has expired
which feels more robust.
Tentatively closes https://github.com/wellcomecollection/storage-service/issues/983
> Fetch the token whenever it's expired

- terraform/modules/service/bags/target_group.tf
- terraform/modules/service/ingest/target_group.tf
Currently deployments are failing because the `aws ecs wait` command only waits for 40 × 15s ≈ 10m before marking a deployment as failed. I hope that if I lower the deregistration delay, deployments will go faster and the builds will succeed.
I borrowed this from something Jamie did aaaaaages ago in the catalogue API.
Tentative fix for https://github.com/wellcomecollection/platform/issues/5626
> Try lowering the deregistration delay on the API services

- bag_verifier/src/main/scala/weco/storage_service/bag_verifier/Main.scala
- bag_verifier/src/main/scala/weco/storage_service/bag_verifier/builder/BagVerifierWorkerBuilder.scala
- bag_verifier/src/main/scala/weco/storage_service/bag_verifier/services/s3/S3BagVerifier.scala
- bag_verifier/src/main/scala/weco/storage_service/bag_verifier/storage/s3/S3Locatable.scala
- bag_verifier/src/main/scala/weco/storage_service/bag_verifier/storage/s3/S3Resolvable.scala
- bag_verifier/src/test/scala/weco/storage_service/bag_verifier/fixity/s3/S3FixityCheckerTest.scala
- bag_verifier/src/test/scala/weco/storage_service/bag_verifier/fixtures/BagVerifierFixtures.scala
- bag_verifier/src/test/scala/weco/storage_service/bag_verifier/services/s3/S3BagVerifierTest.scala
- bag_verifier/src/test/scala/weco/storage_service/bag_verifier/storage/s3/S3LocatableTest.scala
- build.sbt
- project/Dependencies.scala
Closes https://github.com/wellcomecollection/platform/issues/4785
There were two classes I didn't migrate in the previous PR:
* S3Resolvable, which turns a storage location into a URI; this URI is in turn used in logs and debugging (e.g. `verified checksum of s3://bukkit/cat.jpg as 1234`)
* S3Locatable, which parses a URI as a location. I dumped all the URIs which get parsed during our tests to a file, then checked them all with the new code. Bits of it are copied from the old implementation.
> Remove the last bits of the V2 SDK

- terraform/stack_prod/main.tf
- terraform/stack_staging/main.tf
I realised https://github.com/wellcomecollection/storage-service/pull/1056 was not actually doing anything because the storage service stacks have the container version specified
> Pin fluentbit container tags to the latest version

- bag_replicator/Dockerfile
For https://github.com/wellcomecollection/storage-service/issues/1066
To test this, I switched to the commit just before we removed the AWS CRT dependency, and ran the repro described in the original ticket. The app now starts without complaining about a linking error.
> Switch to the 11-jre base image in the bag replicator

- bag_tracker/docker-compose.yml
- bag_tracker/src/main/scala/weco/storage_service/bag_tracker/BagTrackerApi.scala
- bag_tracker/src/test/scala/weco/storage_service/bag_tracker/client/CreateBagTestCases.scala
For https://github.com/wellcomecollection/storage-service/issues/1071
After a bag has been successfully replicated to a verified in our permanent storage buckets, it goes to the "bag register", which creates a storage manifest (a JSON description of the bag). The bag register tries to put this manifest in the storage manifest database.
In front of the database is the "bag tracker", which mediates all access to the database. After the bag register has stored a new manifest, the manifest can be retrieved from the bags API.
```mermaid
flowchart TD
P["… rest of pipeline …"] --> R[bag register]
R -->|HTTP POST| T[bag tracker]
A[bags API] -->|HTTP GET| T
T --> D[(storage manifest<br/>database)]
classDef externalNode fill:#e8e8e8,stroke:#8f8f8f
class P,A,D externalNode
classDef repoNode …
```
> Allow posting storing arbitrarily large manifests in the bag tracker

- bag_verifier/docker-compose.yml
- bag_verifier/src/main/scala/weco/storage_service/bag_verifier/storage/s3/S3Resolvable.scala
- bag_verifier/src/test/scala/weco/storage_service/bag_verifier/services/BagVerifierTestCases.scala
- bag_verifier/src/test/scala/weco/storage_service/bag_verifier/storage/s3/S3LocatableResolvableTest.scala
- bag_verifier/src/test/scala/weco/storage_service/bag_verifier/storage/s3/S3ResolvableTest.scala
This fixes a small regression; we need this bugfix for https://github.com/wellcomecollection/platform/issues/5708
We definitely used to support this, because we have Miro bags that have spaces in the external identifier/keys. You could make an argument that we shouldn't support this, but there's historical precedent for it and S3 is fine with it, so this patch adds support and proper test coverage for this case.
(In unsurprising news, the bug was in S3Resolvable, a class we thought was simple enough not to require tests – oops.)
> Allow verifying bags with a space in the key

- bags_api/src/test/scala/weco/storage_service/bags_api/LookupBagApiTest.scala
- common/src/main/scala/weco/storage_service/bagit/models/ExternalIdentifier.scala
- common/src/test/scala/weco/storage_service/bagit/models/ExternalIdentifierTest.scala
- common/src/test/scala/weco/storage_service/bagit/services/BagInfoParserTest.scala
- ingests/ingests_api/src/main/scala/weco/storage_service/ingests_api/responses/CreateIngest.scala
- ingests/ingests_api/src/test/scala/weco/storage_service/ingests_api/CreateIngestApiTest.scala
See: https://github.com/wellcomecollection/storage-service/issues/1037
This adds the ability to use identifiers containing dots, and also tightens the rules around spaces and start/end characters.
> New id constraints

- docs/wellcome/completely-deleting-bags-from-the-storage-service.md
Flavio Vecellio (cloud engineer) 's suggestion:
> Regarding the template request, I'd suggest to specify that the write permissions are usually given by assigning the "Contributor" role to the c_cloud account.
> The role named "Contributor" will be clear to everyone, because it's a pre-defined role in Azure which will always exist and cannot be modified
> makes it clearer how to grant the required permissions

- builds/publish_sbt_image_to_ecr.sh
This fixes another example of the problem found in https://github.com/wellcomecollection/archivematica-infrastructure/pull/141
See https://buildkite.com/wellcomecollection/storage-service/builds/1691
Open a PR and see whether the PR checks pass.
We can build the storage service again.
This has been applied successfully in other project. We can also check it works properly before even merging the change. The build here also signs into ecr public so we might see the problem pop up in another place too.
> log into ECR with get-login-password

- bags_api/src/main/scala/weco/storage_service/bags_api/BagsApi.scala
- ingests/ingests_api/src/main/scala/weco/storage_service/ingests_api/IngestsApi.scala
- project/Dependencies.scala
- project/build.properties
- project/build.sbt
- project/plugins.sbt
- terraform/modules/service/bags/main.tf
- terraform/modules/service/bags/target_group.tf
- terraform/modules/service/bags/variables.tf
- terraform/modules/service/base/main.tf
- terraform/modules/service/ingest/main.tf
- terraform/modules/service/ingest/target_group.tf
- terraform/modules/service/ingest/variables.tf
- terraform/modules/service/worker/main.tf
- terraform/stack_prod/main.tf
- terraform/stack_staging/.terraform.lock.hcl
- terraform/stack_staging/main.tf
This change is part of https://github.com/wellcomecollection/wellcomecollection.org/issues/10545, and adds an HTTP healthcheck to the bags and ingest APsI to ensure the scala service has started before it is registered healthy at the NLB and starts serving requests.
Depends: https://github.com/wellcomecollection/storage-service/pull/1114
No downtime during deployments resulting in a better experience for consumers of this service, and fewer errors that we cannot effectively respond to in the alerts channel.
Changing the health-checks changes the failure modes for the API, although we have tested this principle successfully in lots of other places so the risk is reduced.
> Adds a simple healthcheck endpoint to the bags and ingest apis

- bags_api/src/main/scala/weco/storage_service/bags_api/BagsApi.scala
- ingests/ingests_api/src/main/scala/weco/storage_service/ingests_api/IngestsApi.scala
- project/Dependencies.scala
- project/build.properties
- project/build.sbt
- project/plugins.sbt
- terraform/modules/service/bags/main.tf
- terraform/modules/service/bags/target_group.tf
- terraform/modules/service/bags/variables.tf
- terraform/modules/service/base/main.tf
- terraform/modules/service/ingest/main.tf
- terraform/modules/service/ingest/target_group.tf
- terraform/modules/service/ingest/variables.tf
- terraform/modules/service/worker/main.tf
- terraform/stack_prod/main.tf
- terraform/stack_staging/.terraform.lock.hcl
- terraform/stack_staging/main.tf
This is another instance of https://github.com/wellcomecollection/catalogue-api/pull/737, needed to compile the app on new Macs.  
The most recent version (1.9.8) of sbt seems to work with this project, so upgrading.
People working on this project with M1 macs can build and test it.
> Bump the SBT version from 1.4.1 to 1.9.8

- .github/workflows/dependency-graph.yml
- .github/workflows/stale.yml
- build.sbt
Follows https://github.com/wellcomecollection/catalogue-api/pull/766 this change pushes the scala dependency graph to the GitHub API to surface vulnerabilities.
We don't need access to S3 as with other similar pull requests as we're not pulling our own deps (we build them here).
Part of https://github.com/wellcomecollection/platform-infrastructure/issues/431
Depends on https://github.com/wellcomecollection/aws-account-infrastructure/pull/19
This change also adds the [stale GitHub workflow](https://github.com/wellcomecollection/catalogue-api/pull/762).
Visibility on dependencies and vulnerabilities. 
This change should help manage / reduce risk.
> Send the Scala dependency graph

- .github/workflows/deploy-daily-reporter.yml
- monitoring/daily_reporter/src/slack.py
- monitoring/ingest_inspector/README.md
This updates the daily reporter lambda that provides summaries of storage service activities in Slack to use the correct URL pattern for the new ingest inspector. In addition this PR adds a GitHub action workflow to deploy the daily reporter lambda as this previously was done manually.
The daily reporter lambda provides working links to the ingest inspector enabling quicker debugging and future updates to the daily-reporter are deployed automatically on merge to main.
This change should not impact any critical storage service processes and can be safely reverted if it does not behave as expected.
> Update links to ingest inspector from daily reporter lambda

- .github/workflows/stale.yml
Call the reusable workflow https://github.com/wellcomecollection/.github/blob/main/.github/workflows/stale.yml, avoids duplication in multiple projects
Change the cron expression to something more frequent and wait for the workflow to run
Runs only on `main`
Stale PRs are checked every morning Mon-Thu
Workflow is easier to maintain, changes applied only in one place
Negligible
> set up new stale PR workflow

- .github/workflows/dependency-graph.yml
The dependency graph action used to update dependabot with Scala deps, no longer needs to authenticate itself in AWS as packages are pulled from Sonatype, not S3. 
The role it used has been deleted: https://github.com/wellcomecollection/aws-account-infrastructure/pull/38, so this action now fails.
Removing the auth step should fix it.
Green ticks on our builds are less confusing than a partial failure indicating that not everything has succeeded (this is also a non-critical error so more confusing).
Risks should be minimal, this does not impact end-users.
> Remove auth for dependency graph action

- scripts/ss_retry_unpacking.py
This adds a new option 'update' to the ss_retry_unpacking script.  See https://github.com/wellcomecollection/editorial-photography-ingest/issues/37
If you have a bag in the relevant broken state, run it.
We remember how to deal with this problem.
> make update a CLI option
