wellcomecollection/storage-service

terraform/critical/ecr.tf
terraform/critical/outputs.tf
terraform/critical/s3_account_public_access_block.tf
terraform/locals.tf
terraform/main.tf
terraform/stack/api/gateway.tf
terraform/stack/api/variables.tf
terraform/stack/main.tf
terraform/stack/variables.tf
terraform/terraform.tf

add custom domain, nginx repo
getting services up for  https://github.com/wellcometrust/platform/issues/2969

Storage infrastructure

---

terraform/modules/resource/main.tf
terraform/stack/api/gateway.tf
terraform/stack/api/locals.tf
terraform/stack/api/nlb.tf
terraform/stack/api/services/bags.tf
terraform/stack/api/services/ingests.tf
terraform/stack/iam_role_policy.tf
terraform/stack/local.tf
terraform/stack/main.tf
terraform/stack/messaging.tf

Make service names a bit easier to understand

Simplify service names

---

terraform/modules/service/worker+nvm/main.tf
terraform/modules/service/worker+nvm/variables.tf

Specify task desired count

---

terraform/stack/main.tf
terraform/stack/messaging.tf

move bag_replicator inline into flow
infrastructure for https://github.com/wellcometrust/platform/issues/2969

Change flow for bag replication

---

terraform/stack/ecs.tf
terraform/stack/iam_role_policy.tf
terraform/stack/main.tf

Reduce the number of ECS instances and tasks running

Scale down ECS

---

terraform/stack/iam_role_policy.tf
terraform/stack/main.tf
terraform/stack/messaging.tf

Push metrics and progress messages from the bag replicator

Bag replicator metrics and progress

---

terraform/modules/queue/main.tf
terraform/modules/queue/variables.tf
terraform/modules/topic/main.tf
terraform/modules/topic/variable.tf
terraform/stack/messaging.tf

SNS changes,
fix bagger topic.
normalise '-' to '_' in sns names.

SNS bagger change

---

terraform/main_colbert.tf
terraform/main_stewart.tf
terraform/stack/main.tf
terraform/stack/variables.tf
terraform/variables.tf

add archivist queue_parallelism configuration

Archivist queue_parallelism

---

bagger/README.md
bagger/src/files.py

Fix a case mismatch between what is in the METS file for a given ALTO path and what's actually on disk
Storage migration
---
Ported from https://github.com/wellcometrust/platform/pull/3413

Retry with upper case X in bnum checksum if ALTO fetch fails

---

archivist/src/main/scala/uk/ac/wellcome/platform/archive/archivist/bag/ArchiveItemJobCreator.scala
archivist/src/main/scala/uk/ac/wellcome/platform/archive/archivist/bag/ArchiveJobCreator.scala
archivist/src/main/scala/uk/ac/wellcome/platform/archive/archivist/bag/ZippedBagFile.scala
archivist/src/main/scala/uk/ac/wellcome/platform/archive/archivist/flow/ArchiveJobDigestItemsFlow.scala
archivist/src/main/scala/uk/ac/wellcome/platform/archive/archivist/flow/ArchiveTagManifestFlow.scala
archivist/src/main/scala/uk/ac/wellcome/platform/archive/archivist/models/ArchiveDigestItemJob.scala
archivist/src/main/scala/uk/ac/wellcome/platform/archive/archivist/models/ArchiveItemJob.scala
archivist/src/main/scala/uk/ac/wellcome/platform/archive/archivist/models/ArchiveJob.scala
archivist/src/main/scala/uk/ac/wellcome/platform/archive/archivist/models/errors/ArchiveError.scala
archivist/src/test/scala/uk/ac/wellcome/platform/archive/archivist/ArchivistFeatureTest.scala
archivist/src/test/scala/uk/ac/wellcome/platform/archive/archivist/bag/ArchiveJobCreatorTest.scala
archivist/src/test/scala/uk/ac/wellcome/platform/archive/archivist/bag/ZippedBagFileTest.scala
archivist/src/test/scala/uk/ac/wellcome/platform/archive/archivist/flow/ArchiveJobDigestItemsFlowTest.scala
archivist/src/test/scala/uk/ac/wellcome/platform/archive/archivist/flow/ArchiveTagManifestFlowTest.scala
archivist/src/test/scala/uk/ac/wellcome/platform/archive/archivist/flow/ArchiveZipFileFlowTest.scala
archivist/src/test/scala/uk/ac/wellcome/platform/archive/archivist/flow/ArchiveZipFileFlowTest.scala.rej
archivist/src/test/scala/uk/ac/wellcome/platform/archive/archivist/flow/DownloadAndVerifyDigestItemFlowTest.scala
archivist/src/test/scala/uk/ac/wellcome/platform/archive/archivist/flow/UploadDigestItemFlowTest.scala
archivist/src/test/scala/uk/ac/wellcome/platform/archive/archivist/flow/UploadItemFlowTest.scala
archivist/src/test/scala/uk/ac/wellcome/platform/archive/archivist/generators/ArchiveJobGenerators.scala
archivist/src/test/scala/uk/ac/wellcome/platform/archive/archivist/generators/FileGenerators.scala
bags/src/main/scala/uk/ac/wellcome/platform/archive/registrar/async/factories/StorageManifestFactory.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/bag/BagDigestFileCreator.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/models/bagit/BagIt.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/models/bagit/BagItemPath.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/models/error/ArchiveError.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/models/bagit/BagItemPathTest.scala

Find bag in ZIP file when archiving.  Primarily to support bags inside a parent directory when ingesting from a ZIP file.
part of:
https://github.com/wellcometrust/platform/issues/3431 
https://github.com/wellcometrust/platform/issues/3420 
---
Ported from https://github.com/wellcometrust/platform/pull/3434 using `git format-patch` and `git am`.

Find bag in ZIP file

---

bagger/src/files.py
bagger/src/test_files.py

For https://github.com/wellcometrust/platform/issues/3420

Fix more capitalisation problems in the bagger

---

archivist/src/test/scala/uk/ac/wellcome/platform/archive/archivist/generators/ArchiveJobGenerators.scala
bags/src/test/scala/uk/ac/wellcome/platform/archive/registrar/async/RegistrarFeatureTest.scala
bags/src/test/scala/uk/ac/wellcome/platform/archive/registrar/async/factories/StorageManifestFactoryTest.scala
bags/src/test/scala/uk/ac/wellcome/platform/archive/registrar/async/fixtures/RegistrarFixtures.scala
bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/BagsApiFeatureTest.scala
bags_common/src/test/scala/uk/ac/wellcome/platform/archive/registrar/generators/StorageManifestGenerators.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/bag/BagInfoParserTest.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/BagLocationFixtures.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/RandomThings.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/BagIdGenerators.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/BagInfoGenerators.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/IngestBagRequestGenerators.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/ProgressGenerators.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/StorageSpaceGenerators.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/progress/fixtures/ProgressGenerators.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/progress/models/ProgressTest.scala
display/src/test/scala/uk/ac/wellcome/platform/archive/display/DisplayIngestTest.scala
ingests/src/test/scala/uk/ac/wellcome/platform/archive/progress_async/ProgressAsyncFeatureTest.scala
ingests/src/test/scala/uk/ac/wellcome/platform/archive/progress_async/flows/CallbackNotificationFlowTest.scala
ingests/src/test/scala/uk/ac/wellcome/platform/archive/progress_async/flows/ProgressUpdateFlowTest.scala
ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/ProgressStarterTest.scala
ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/fixtures/IngestsApiFixture.scala
ingests_common/src/test/scala/uk/ac/wellcome/platform/archive/common/progress/ProgressTrackerTest.scala
ingests_common/src/test/scala/uk/ac/wellcome/platform/archive/common/progress/fixtures/ProgressTrackerFixture.scala
notifier/src/test/scala/uk/ac/wellcome/platform/archive/notifier/NotifierFeatureTest.scala
notifier/src/test/scala/uk/ac/wellcome/platform/archive/notifier/flows/PrepareNotificationFlowTest.scala

I feel like I might push the very core of it (randomAlphanumeric and similar bits) into the fixtures library.

Keep cleaning up bits of RandomThings to tidy up this stack

---

terraform/main_colbert.tf
terraform/main_stewart.tf
terraform/stack/main.tf
terraform/variables.tf

Increase concurrency in the archivist, by increasing the deployed number of tasks and queue parallelism.

Archivist more concurrency

---

bagger/src/mappings.py

Add another PRONOM mapping for Waveform Audio

---

bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/BagsApiFeatureTest.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/http/WellcomeHttpApp.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/http/models/ErrorResponse.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/HttpFixtures.scala
ingests_api/src/main/scala/uk/ac/wellcome/platform/storage/ingests/api/Router.scala
ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/IngestsApiFeatureTest.scala

Resolves https://github.com/wellcometrust/platform/issues/3433

Don't expose the error description in HTTP 500 error responses

---

common/src/main/scala/uk/ac/wellcome/platform/archive/common/models/bagit/ChecksumVerifier.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/models/bagit/ChecksumVerifierTest.scala

Small utility object to verify bagit checksums for an S3 object

BagIt checksum verification

---

terraform/main_colbert.tf
terraform/stack/api/main.tf
terraform/stack/api/services/bags.tf
terraform/stack/api/services/ingests.tf
terraform/stack/api/services/variables.tf
terraform/stack/api/variables.tf
terraform/stack/ecs.tf
terraform/stack/main.tf
terraform/stack/variables.tf

Reduce the size (and cost) of the staging API

---

terraform/stack/main.tf
terraform/stack/messaging.tf

A speculative fix for https://github.com/wellcometrust/platform/issues/3458

Bump the visibility timeout on the bag replicator Q

---

common/src/main/scala/uk/ac/wellcome/platform/archive/common/progress/models/ProgressUpdate.scala
ingests_common/src/test/scala/uk/ac/wellcome/platform/archive/common/progress/ProgressTrackerTest.scala
notifier/src/main/scala/uk/ac/wellcome/platform/archive/notifier/services/PrepareNotificationService.scala

Standalone bit pulled from #65

Tidy up the apply() method for ProgressCallbackStatusUpdate

---

terraform/stack/iam_policy_document.tf
terraform/stack/iam_role_policy.tf

give the bag unpacker permission to S3 and `PutMetricData`

Bag unpacker permissions

---

archivist/src/main/scala/uk/ac/wellcome/platform/archive/archivist/builders/UploadLocationBuilder.scala
archivist/src/main/scala/uk/ac/wellcome/platform/archive/archivist/models/BagItemLocation.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/Main.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/BagReplicatorFeatureTest.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/fixtures/BagReplicatorFixtures.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/fixtures/WorkerServiceFixture.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorkerServiceTest.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagStorageServiceTest.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/BagVerifierFeatureTest.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierWorkerServiceTest.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/BagRequestGenerators.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/services/StorageManifestServiceTest.scala
ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/ProgressStarterTest.scala
project/Dependencies.scala

Part of https://github.com/wellcometrust/platform/issues/3443
I'm going to copy the existing bag_replicator wholesale, so tidying it up first felt useful. This patch should have no functional changes, just cleanups.

Refactoring in the bag replicator

---

terraform/stack/main.tf
terraform/stack/messaging.tf

This is the current set of topic ~> queue subscriptions:
```
storage_bag_replicator_output ~> storage_bag_verifier_input
storage_bag_replicator_output ~> storage_bags_input
storage_bag_unpacker_input ~> storage_bag_unpacker_input
storage_bag_unpacker_output ~> storage_bag_replicator_input
storage_bag_verifier_output ~> storage_bag_verifier_output
storage_bagger ~> storage_bagger
storage_ingest_requests ~> storage_archivist_input
storage_ingests ~> storage_ingests_input
storage_ingests_output ~> storage_notifier
```

Wire up the storage replicator (partially)

---

archivist/src/main/scala/uk/ac/wellcome/platform/archive/archivist/bag/BagDigestFileCreator.scala
archivist/src/main/scala/uk/ac/wellcome/platform/archive/archivist/flow/DownloadAndVerifyDigestItemFlow.scala
archivist/src/main/scala/uk/ac/wellcome/platform/archive/archivist/models/errors/ArchiveError.scala
archivist/src/test/scala/uk/ac/wellcome/platform/archive/archivist/flow/ArchiveJobDigestItemsFlowTest.scala
archivist/src/test/scala/uk/ac/wellcome/platform/archive/archivist/flow/ArchiveZipFileFlowTest.scala
archivist/src/test/scala/uk/ac/wellcome/platform/archive/archivist/flow/DownloadAndVerifyDigestItemFlowTest.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/models/error/ArchiveError.scala

A bit more code that will fall into the sea.

Push two more errors into the archivist

---

terraform/stack/iam_policy_document.tf
terraform/stack/iam_role_policy.tf

add permission for the bag_replicator to read from ingests S3

bag_replicator permissions

---

bagger/src/settings.py
bagger/src/storage_api.py
terraform/stack/main.tf
terraform/stack/messaging.tf

Switch bagger tools to create and ingest tar.gz archives.

Bagger to use tar.gz

---

archivist/src/main/resources/application.conf
bag_register/src/main/resources/application.conf
bag_replicator/src/main/resources/application.conf
bag_unpacker/src/main/resources/application.conf
bag_verifier/src/main/resources/application.conf
bags_api/src/main/resources/application.conf
ingests/src/main/resources/application.conf
ingests_api/src/main/resources/application.conf
notifier/src/main/resources/application.conf

I haven't tested it, but I bet this helps https://github.com/wellcometrust/platform/issues/3279
Maybe https://github.com/wellcometrust/platform/issues/3423 as well

metrics.namespace needs to be prefixed with aws.

---

bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/Unpacker.scala
bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/fixtures/CompressFixture.scala
bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/BagArchiveWorkerTest.scala
bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/UnpackerTest.scala
bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/storage/ArchiveTest.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/RandomThings.scala

Unpacker tgz file tests

---

bag_register/src/main/resources/application.conf
bag_replicator/src/main/resources/application.conf
bag_unpacker/src/main/resources/application.conf
bag_verifier/src/main/resources/application.conf
bags_api/src/main/resources/application.conf
ingests/src/main/resources/application.conf
ingests_api/src/main/resources/application.conf
notifier/src/main/resources/application.conf
terraform/stack/locals.tf
terraform/stack/main.tf
terraform/stack/release_uris.tf

Use service names for all metric namespaces

Update metric namespaces

---

bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/BagUnpackerWorker.scala
bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/Unpacker.scala
bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/fixtures/WorkerServiceFixture.scala
bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/BagArchiveWorkerTest.scala
bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/UnpackerTest.scala

Resolves https://github.com/wellcometrust/platform/issues/3479

Fail the ingest if we're asked to unpack a non-existent bag; don't just fall over

---

bagger/src/bagger.py
bagger/src/files.py
bagger/src/local_bag_all.py
bagger/src/local_enqueue.py
bagger/src/mappings.py
bagger/src/mets.py
bagger/src/migration_report.py
bagger/src/storage_api.py
bagger/src/tech_md.py

Use hashed data structures to improve bagger performance and lazy logging

---

bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/S3Uploader.scala
bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/Unpacker.scala

With a view to eventually moving it into a separate lib.

Split out the S3Uploader as a separate class

---

bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/models/RegistrationSummary.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/models/ReplicationSummary.scala
bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/models/UnpackSummary.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/models/VerificationSummary.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/operation/Summary.scala

add toString method for Summary types and use single method for formating the duration

Summary toString

---

bagger/src/dlcs.py

For better diagnostics in https://github.com/wellcometrust/platform/issues/3302

Add a custom error message for JSON decoding errors from DLCS

---

bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/BagsApiFeatureTest.scala

Remove stray unused import in `BagsApiFeatureTest`

Remove unused import

---

bag_unpacker/src/main/resources/application.conf
terraform/stack/main.tf

Use queue_parallelism configuration in the bag_unpacker.

Unpacker parallelism

---

terraform/modules/queue/main.tf

Depends https://github.com/wellcometrust/terraform-modules/pull/154

Use new TF scaling module

---

bagger/src/aws.py

Look for tar.gz not zip bagged files

Bagger status for tar.gz bagged files

---

bag_unpacker/src/main/resources/application.conf
bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/Main.scala
bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/config/BagLocationBuilder.scala
bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/config/UnpackerConfig.scala
bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/config/builders/UnpackerConfigBuilder.scala
bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/config/builders/UnpackerWorkerConfigBuilder.scala
bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/config/models/UnpackerConfig.scala
bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/config/models/UnpackerWorkerConfig.scala
bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/S3Uploader.scala
bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/Unpacker.scala
bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/UnpackerWorker.scala
bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/storage/Archive.scala
bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/fixtures/CompressFixture.scala
bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/fixtures/WorkerServiceFixture.scala
bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/UnpackerFeatureTest.scala
bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/UnpackerTest.scala
bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/storage/ArchiveTest.scala
terraform/stack/main.tf

Config option for unpacker.buffer.size

Unpacker configurable buffer size

---

.travis/run_job.py
bagger/src/aws.py

I think this should be more efficient. Shared connection pools FTW.

Create the S3 client/resource once, not repeatedly

---

terraform/stack/main.tf

Increase bag_verifier capacity

Increase bag_verifier capacity

---

bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/models/RegistrationSummary.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/models/ReplicationSummary.scala
bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/models/UnpackSummary.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/models/VerificationSummary.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/operation/models/Timed.scala

Tiny change to also log duration in seconds

Log duration in seconds

---

common/src/main/scala/uk/ac/wellcome/platform/archive/common/operation/services/DiagnosticReporter.scala

Make the reporter log exception messages, so it's easier to see in the logs.

Log exception messages

---

bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/S3Uploader.scala

revert previous change - remove multipart upload threshold configuration.

Revert upload threshold config

---

api/ingests_api/src/main/scala/uk/ac/wellcome/platform/storage/ingests/api/Router.scala
api/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/IngestsApiFeatureTest.scala
api/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/fixtures/IngestsApiFixture.scala

Fixes https://github.com/wellcometrust/platform/issues/3513

Return a JSON response for 404 from the ingests API

---

api/bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/Router.scala
api/bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/BagsApiFeatureTest.scala
api/ingests_api/src/main/scala/uk/ac/wellcome/platform/storage/ingests/api/Router.scala
api/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/IngestsApiFeatureTest.scala
terraform/stack/api/gateway.tf

For https://github.com/wellcometrust/platform/issues/3516

Use the same names internally as we do everywhere else

---

bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicator.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/S3BagLocatorTest.scala
bag_verifier/docker-compose.yml
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierWorker.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/Verifier.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/VerifierTest.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/models/BagItemPath.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/S3BagLocator.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestService.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/BagLocationFixtures.scala

locate the root of the bag in the BagLocation when verifying

Bag verifier supports verification of a bag in a subdirectory

---

notifier/src/main/scala/uk/ac/wellcome/platform/archive/notifier/Main.scala
notifier/src/main/scala/uk/ac/wellcome/platform/archive/notifier/services/CallbackUrlService.scala
notifier/src/test/scala/uk/ac/wellcome/platform/archive/notifier/fixtures/NotifierFixtures.scala

Spotted by accident; I think a JSON encoding error here would throw an exception.

Don't do a toJson(…).get in the notifier

---

api/ingests_api/src/main/scala/uk/ac/wellcome/platform/storage/ingests/api/IngestStarter.scala
api/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/IngestStarterTest.scala
api/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/IngestsApiFeatureTest.scala
bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/services/BagAuditorWorker.scala
bag_auditor/src/test/scala/uk/ac/wellcome/platform/storage/bagauditor/BagAuditorFeatureTest.scala
bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorker.scala
bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/BagRegisterFeatureTest.scala
bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorkerTest.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorker.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/BagReplicatorFeatureTest.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorkerTest.scala
bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/BagUnpackerWorker.scala
bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/UnpackerFeatureTest.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/PipelinePayload.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/IngestRequestPayloadTest.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/UnpackedBagPayloadTest.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/PayloadGenerators.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/operation/services/OutgoingPublisherTest.scala

Another piece for https://github.com/wellcometrust/platform/issues/2777
This is tested and works

Pass around the ingest date in payloads

---

bag_auditor/src/test/scala/uk/ac/wellcome/platform/storage/bagauditor/fixtures/BagAuditorFixtures.scala
bag_auditor/src/test/scala/uk/ac/wellcome/platform/storage/bagauditor/services/BagAuditorTest.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/versioning/IngestVersionManager.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/versioning/IngestVersionManagerDao.scala

Spun out into a separate PR for ease of reviewing in #205.

High-noise, low-value line churn from #205

---

bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/versioning/VersionPicker.scala
bag_auditor/src/test/scala/uk/ac/wellcome/platform/storage/bagauditor/BagAuditorFeatureTest.scala
bag_auditor/src/test/scala/uk/ac/wellcome/platform/storage/bagauditor/versioning/VersionPickerTest.scala

First part of wellcometrust/platform#3657.

Only assign a version that's consistent with the ingest type

---

bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/Main.scala
bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/Main.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/Main.scala
bag_root_finder/src/main/scala/uk/ac/wellcome/platform/storage/bag_root_finder/Main.scala
bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/Main.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/Main.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/config/builders/OperationNameBuilder.scala

Closes https://github.com/wellcometrust/platform/issues/3690

Ditch the default operation names; always require one

---

bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/services/BagAuditor.scala
bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/versioning/VersionPicker.scala
bag_auditor/src/test/scala/uk/ac/wellcome/platform/storage/bagauditor/versioning/VersionPickerTest.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/versioning/IngestVersionManager.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/versioning/IngestVersionManagerDao.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/versioning/IngestVersionManagerError.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/versioning/VersionRecord.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/versioning/dynamo/DynamoEntry.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/versioning/dynamo/DynamoID.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/versioning/dynamo/DynamoIngestVersionManagerDao.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/versioning/memory/MemoryIngestVersionManagerDao.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/versioning/IngestVersionManagerDaoTestCases.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/versioning/IngestVersionManagerTestCases.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/versioning/VersionRecordGenerators.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/versioning/dynamo/DynamoEntryTest.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/versioning/dynamo/DynamoIngestVersionManagerDaoTest.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/versioning/dynamo/DynamoIngestVersionManagerTest.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/versioning/dynamo/IngestVersionManagerTable.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/versioning/memory/MemoryIngestVersionManagerTest.scala

Closes https://github.com/wellcometrust/platform/issues/3693

Split versions by (storage space, external identifier)

---

bag_auditor/src/test/scala/uk/ac/wellcome/platform/storage/bagauditor/BagAuditorFeatureTest.scala
bag_root_finder/src/test/scala/uk/ac/wellcome/platform/storage/bag_root_finder/BagRootFinderFeatureTest.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/PayloadGenerators.scala

And add more randomisation so we'll catch a similar clock assumption in future.

Fix a flaky test in the bag_root_finder

---

api/bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/BagsApi.scala
api/bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/Main.scala
api/bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/Router.scala
api/bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/BagsApiFeatureTest.scala
api/bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/fixtures/BagsApiFixture.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/StorageManifestGenerators.scala

For https://github.com/wellcometrust/platform/issues/2777

Add support for retrieving multiple versions of a bag

---

common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/models/MatchedLocation.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/models/package.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/services/BagMatcher.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/services/BagVerifiable.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/models/BagFetchTest.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/services/BagMatcherTest.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/services/BagVerifiableTest.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/BagFileGenerators.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/BagGenerators.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/FetchEntryGenerators.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/StorageManifestGenerators.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestDaoTest.scala

Prep for changing the output of the bags API.

Consolidate some generators in the tests and extract the BagMatcher

---

bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/fixtures/BagReplicatorFixtures.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorkerTest.scala

Attempted fix for https://github.com/wellcometrust/platform/issues/3719

Rejig the bag replicator tests for hopefully less flakiness

---

api/bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/BagsApiFeatureTest.scala

Just a cleanup – we no longer need these materialisers.

Simplify the bags API tests slightly

---

bag_auditor/src/main/scala/uk/ac/wellcome/platform/storage/bagauditor/versioning/VersionPicker.scala
bag_auditor/src/test/scala/uk/ac/wellcome/platform/storage/bagauditor/services/BagAuditorTest.scala
bag_auditor/src/test/scala/uk/ac/wellcome/platform/storage/bagauditor/versioning/VersionPickerTest.scala

For https://github.com/wellcometrust/platform/issues/3732

Skip checking ingestType in the bag versioner

---

bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/BagRegisterFeatureTest.scala
bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/fixtures/BagRegisterFixtures.scala
bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorkerTest.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/models/VerificationSummary.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifier.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierWorker.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/BagVerifierFeatureTest.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierTest.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierWorkerTest.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/S3BagLocationFixtures.scala

for https://github.com/wellcometrust/platform/issues/3696

Verify the external identifier in the bag-info.txt

---

bagger/src/bag_assembly.py
bagger/src/bagger.py
bagger/src/files.py
bagger/src/image_size.py
bagger/src/tech_md.py

Addresses https://github.com/wellcometrust/platform/issues/3718

First pass at including poster images in bags and METS

---

common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestDao.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/dynamo/DynamoStorageManifestDao.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/memory/MemoryStorageManifestDao.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestDaoTestCases.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/dynamo/DynamoStorageManifestDaoTest.scala

Another piece for https://github.com/wellcometrust/platform/issues/3731

Add a method for listing versions on StorageManifestDao

---

python_client/src/wellcome_storage_service/__init__.py
python_client/src/wellcome_storage_service/version.py
python_client/tests/cassettes/test_can_get_bag_version.json
python_client/tests/cassettes/test_gets_correct_bag_version.json
python_client/tests/cassettes/test_raises_404_for_missing_bag_with_version.json
python_client/tests/test_bags.py

Add support for getting bag by version

---

bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/Unpacker.scala

Two logs that were helpful in diagnosing https://github.com/wellcometrust/platform/issues/3743

Add some extra debug logging to the unpacker

---

bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifier.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierTest.scala

Closes #3519.
This was blocking Jonathan ingesting bags yesterday.

If we see a SHA512 tag manifest in the bag, ignore it

---

makefiles/functions.Makefile

More arny ![arny](https://amp.businessinsider.com/images/556c7027eab8ea6d74b5ebcf-640-1136.jpg)

use new publish service that uses arns

---

.wellcome_project

use arn in release tool config

---

ingests/src/main/scala/uk/ac/wellcome/platform/archive/ingests/services/IngestsWorker.scala
ingests/src/test/scala/uk/ac/wellcome/platform/archive/ingests/services/IngestsWorkerServiceTest.scala

Closes https://github.com/wellcometrust/platform/issues/3812

Failures in the ingests monitor are non-deterministic

---

bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/models/ReplicationSummary.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicator.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorker.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/BagReplicatorFeatureTest.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/fixtures/BagReplicatorFixtures.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorkerTest.scala

Some refactoring in anticipation of https://github.com/wellcometrust/platform/issues/3823 – just making the replicator codebase a little cleaner and more consistent.

Tidy up the bag replicator

---

terraform/stack/locals.tf

bump logstash transit version

---

bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/BagRegisterFeatureTest.scala
bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/fixtures/BagRegisterFixtures.scala
bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorkerTest.scala
bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/RegisterTest.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorkerTest.scala
bag_versioner/src/test/scala/uk/ac/wellcome/platform/storage/bag_versioner/BagVersionerFeatureTest.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/StorageRandomThings.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/IngestGenerators.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/PayloadGenerators.scala

Small refactoring ahead of https://github.com/wellcometrust/platform/issues/3825

Slightly tidy up the creation of random BagVersion values

---

bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/Main.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorker.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/fixtures/BagReplicatorFixtures.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorkerTest.scala

Closes https://github.com/wellcometrust/platform/issues/3823

Check the tag manifests match in the bag replicator

---

bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/config/ReplicatorDestinationConfig.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorker.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/DestinationBuilder.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/BagReplicatorFeatureTest.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/fixtures/BagReplicatorFixtures.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorkerTest.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/DestinationBuilderTest.scala

Closes https://github.com/wellcometrust/platform/issues/3825
~Blocked on #311.~

Remove the rootPath setting from the replicator

---

bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/Main.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicator.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorker.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/fixtures/BagReplicatorFixtures.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorkerTest.scala
project/Dependencies.scala

This should get us parallelism in the bag replications, which make them a bit faster and more efficient.
Closes https://github.com/wellcometrust/platform/issues/3727

Bump the scala-storage version to 7.19.0

---

bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/BagRegisterFeatureTest.scala
bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/fixtures/BagRegisterFixtures.scala
bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorkerTest.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/StorageRandomThings.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestServiceTest.scala

A bit of refactoring ahead of https://github.com/wellcometrust/platform/issues/3845

Register: refactor the tests for smaller assertions

---

replica_aggregator/src/main/resources/application.conf
replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/Main.scala
terraform/stack/main.tf

Closes https://github.com/wellcometrust/platform/issues/3836

Add a flag to the aggregator for the expected replica count

---

bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/Main.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/bags/BagReplicator.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorker.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/bags/BagReplicatorTest.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/fixtures/BagReplicatorFixtures.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorkerTest.scala
project/Dependencies.scala

And simplify the replicator primary/secondary work a bit.

Use DynamoLockDaoBuilder from scala-storage

---

bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/models/RegistrationSummary.scala
bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorker.scala
bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/services/Register.scala
bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/BagRegisterFeatureTest.scala
bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/fixtures/BagRegisterFixtures.scala
bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorkerTest.scala
bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/RegisterTest.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/models/KnownReplicas.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestService.scala

Closes https://github.com/wellcometrust/platform/issues/3845

Register: store multiple replica locations

---

bagger/reference_data/b_numbers.md

This is a 6 volume _audio_ multiple manifestation flagged by Harkiran

Add a new example to reference b numbers

---

replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/Main.scala

https://github.com/wellcometrust/platform/issues/3824 is rearing its head again.

Fix a problem with the replica aggregator starting

---

bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/fixtures/BagRegisterFixtures.scala
bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/RegisterTest.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorker.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/BagReplicatorFeatureTest.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/bags/BagReplicatorTest.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorkerTest.scala
bag_root_finder/src/main/scala/uk/ac/wellcome/platform/storage/bag_root_finder/models/RootFinderSummary.scala
bag_root_finder/src/main/scala/uk/ac/wellcome/platform/storage/bag_root_finder/services/BagRootFinder.scala
bag_root_finder/src/main/scala/uk/ac/wellcome/platform/storage/bag_root_finder/services/BagRootFinderWorker.scala
bag_root_finder/src/test/scala/uk/ac/wellcome/platform/storage/bag_root_finder/BagRootFinderFeatureTest.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierWorker.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/BagVerifierFeatureTest.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierTest.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierWorkerTest.scala
bag_versioner/src/main/scala/uk/ac/wellcome/platform/storage/bag_versioner/services/BagVersionerWorker.scala
bag_versioner/src/test/scala/uk/ac/wellcome/platform/storage/bag_versioner/BagVersionerFeatureTest.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/PipelinePayload.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/S3BagLocator.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/verify/Verification.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/services/BagReaderTestCases.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/services/memory/MemoryBagReaderTest.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/services/s3/S3BagReaderTest.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/BagBuilderBase.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/PayloadGenerators.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/S3BagLocatorTest.scala
replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/models/ReplicaResult.scala
replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorWorker.scala
replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/ReplicaAggregatorFeatureTest.scala
replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorWorkerTest.scala

Refactoring in prep for https://github.com/wellcometrust/platform/issues/3834

Use ObjectLocationPrefix for the root of a bag, not ObjectLocation

---

bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/bags/models/BagReplicationRequest.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorker.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/BagReplicatorFeatureTest.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorkerTest.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/BagVerifierFeatureTest.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierWorkerTest.scala
bag_versioner/src/main/scala/uk/ac/wellcome/platform/storage/bag_versioner/services/BagVersionerWorker.scala
bag_versioner/src/test/scala/uk/ac/wellcome/platform/storage/bag_versioner/BagVersionerFeatureTest.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/PipelinePayload.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/models/ReplicaResult.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/PayloadGenerators.scala
replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregator.scala
replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorWorker.scala
replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/ReplicaAggregatorFeatureTest.scala
replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorTest.scala
replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorWorkerTest.scala

For https://github.com/wellcometrust/platform/issues/3834

Pass a ReplicaResultPayload between the replicator and the aggregator

---

bag_replicator/src/main/resources/application.conf
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/Main.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/config/ReplicatorDestinationConfig.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorker.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/BagReplicatorFeatureTest.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/fixtures/BagReplicatorFixtures.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorkerTest.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/ingests/models/StorageProvider.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/StorageRandomThings.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/PayloadGenerators.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/StorageLocationGenerators.scala
terraform/stack/main.tf

For https://github.com/wellcometrust/platform/issues/3835

Add config to the replicator for provider and primary/secondary

---

terraform/locals.tf
terraform/main_staging.tf

Fixes: https://github.com/wellcometrust/workflow/issues/192

Ensure working access to workflow staging bucket

---

ingests_common/src/test/scala/uk/ac/wellcome/platform/archive/common/ingests/tracker/memory/MemoryIngestTrackerTest.scala
project/Dependencies.scala
replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorWorker.scala
replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorTest.scala
replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorWorkerTest.scala

Tentative fix for https://github.com/wellcometrust/platform/issues/3860

A retryable error in the replica aggregator => retry operation

---

replica_aggregator/docker-compose.yml
replica_aggregator/src/main/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorWorker.scala
replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/services/ReplicaAggregatorWorkerTest.scala
terraform/modules/stack/messaging.tf

Another attempt at https://github.com/wellcometrust/platform/issues/3860

Handle DynamoDB conditional update errors in the replica aggregator

---

scripts/common.py
scripts/ss_get_ingest.py
scripts/ss_start_ingest.py

Get them out of my repo and into a useful place!

Start adding some scripts for working with ingests

---

bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifier.scala
bagger/src/migration_tools.py

Differentiate between JSON decoding and request status errors and provide some output to help debug.
e.g.
```
AWS_PROFILE=storage ./migtool.sh simulate_goobi_calls --delay 0 --filter '3/0/0/0'
[
Unexpected error: <class 'Exception'>
Traceback (most recent call last):
File "../src/migration_tools.py", line 319, in <module>
fire.Fire(MigrationTool)
File "/Users/k/Library/Python/3.6/lib/python/site-packages/fire/core.py", line 127, in Fire
component_trace = _Fire(component, args, context, name)
File "/Users/k/Library/Python/3.6/lib/python/site-packages/fire/core.py", line 366, in _Fire
component, remaining_args)
File "/Users/k/Library/Python/3.6/lib/python/site-packages/fire/core.py", line 542, in _CallCallable
result = fn(*varargs, **kwargs)
File "../src/migration_tools.py", line 36, in …
```

Slightly nicer errors when dealing with DDS

---

common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/S3ObjectExists.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/S3Uploader.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/S3ObjectExistsTest.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/S3UploaderTest.scala
scripts/ss_get_ingest.py

For wellcometrust/platform#3937

Add existence check for S3Uploader

---

api/Makefile
api/bags_api/docker-compose.yml
api/bags_api/src/main/resources/application.conf
api/bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/BagsApi.scala
api/bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/Main.scala
api/bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/BagsApiFeatureTest.scala
api/bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/fixtures/BagsApiFixture.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/LargeResponses.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/S3ObjectExists.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/S3Uploader.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/StorageManifestGenerators.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/S3ObjectExistsTest.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/S3UploaderTest.scala
terraform/modules/stack/iam_policy_document.tf
terraform/modules/stack/iam_role_policy.tf
terraform/modules/stack/main.tf
terraform/modules/stack/s3_responses.tf

For wellcometrust/platform#3937

Store & redirect large responses

---

python_client/.coveragerc
python_client/CHANGELOG.md
python_client/setup.py
python_client/src/wellcome_storage_service/__init__.py
python_client/src/wellcome_storage_service/_utils.py
python_client/src/wellcome_storage_service/downloader.py
python_client/src/wellcome_storage_service/version.py
python_client/test_requirements.in
python_client/test_requirements.txt
python_client/tests/test_downloader.py
python_client/tests/test_utils.py
python_client/tox.ini
scripts/ss_download_bag.py
scripts/ss_get_bag.py

This isn't especially hard, but it is a little fiddly and something we'll probably want to do over and over again.
Closes https://github.com/wellcometrust/platform/issues/3949

Add some code for downloading the contents of a bag

---

terraform/modules/stack/messaging.tf

Closes https://github.com/wellcometrust/platform/issues/3960

Bump the visibility timeout on the bag register queue

---

api/ingests_api/src/main/resources/application.conf
api/ingests_api/src/main/scala/uk/ac/wellcome/platform/storage/ingests/api/Main.scala
ingests/src/main/resources/application.conf
ingests/src/main/scala/uk/ac/wellcome/platform/archive/ingests/Main.scala
ingests_common/src/main/scala/uk/ac/wellcome/platform/archive/common/ingests/tracker/dynamo/DynamoIngestTracker.scala
ingests_common/src/test/scala/uk/ac/wellcome/platform/archive/common/ingests/tracker/dynamo/DynamoIngestTrackerTest.scala

For wellcometrust/platform#3966.

Don’t store an ingest for looking up by bag ID in the ingests monitor

---

terraform/critical_prod/delete_protection.tf
terraform/modules/critical/outputs.tf
terraform/modules/critical/vhs.tf
terraform/modules/critical/vhs_manifests.tf

We need to think about how we do deletions properly; I've started recording some thoughts in https://github.com/wellcometrust/platform/issues/4002. For now that's not a big concern, and we don't want to accidentally delete any of the digitised content.
Requires https://github.com/wellcometrust/terraform-modules/pull/171
Closes https://github.com/wellcometrust/platform/issues/3948

Prevent dev deletions/writes in the prod storage service

---

bag_versioner/src/main/scala/uk/ac/wellcome/platform/storage/bag_versioner/services/UserFacingMessages.scala
bag_versioner/src/main/scala/uk/ac/wellcome/platform/storage/bag_versioner/versioning/IngestVersionManager.scala
bag_versioner/src/main/scala/uk/ac/wellcome/platform/storage/bag_versioner/versioning/IngestVersionManagerError.scala
bag_versioner/src/main/scala/uk/ac/wellcome/platform/storage/bag_versioner/versioning/VersionPicker.scala
bag_versioner/src/main/scala/uk/ac/wellcome/platform/storage/bag_versioner/versioning/VersionPickerError.scala
bag_versioner/src/test/scala/uk/ac/wellcome/platform/storage/bag_versioner/versioning/IngestVersionManagerTestCases.scala
bag_versioner/src/test/scala/uk/ac/wellcome/platform/storage/bag_versioner/versioning/VersionPickerTest.scala

Closes https://github.com/wellcometrust/platform/issues/4015

Only record versions in the bag versioner if we know we can assign a version to this ingest

---

terraform/modules/stack/iam_policy_document.tf
terraform/modules/stack/iam_role_policy.tf
terraform/stack_prod/main.tf
terraform/stack_prod/terraform.tf
terraform/stack_staging/locals.tf
terraform/stack_staging/terraform.tf

For https://github.com/wellcometrust/platform/issues/4009

Point to the new Archivematica buckets

---

terraform/critical_prod/main.tf
terraform/critical_staging/main.tf
terraform/modules/critical/s3_replica_glacier.tf

Closes https://github.com/wellcometrust/platform/issues/4039

Don't give unnecessary read principals to our Glacier buckets

---

terraform/critical_prod/locals.tf
terraform/critical_staging/locals.tf

Change catalogue role with permissions to read the storage s3 bucket

---

terraform/modules/stack/iam_policy_document.tf
terraform/modules/stack/messaging.tf
terraform/modules/stack/outputs.tf
terraform/modules/stack/variables.tf
terraform/stack_prod/locals.tf
terraform/stack_prod/main.tf
terraform/stack_prod/outputs.tf
terraform/stack_staging/main.tf

For https://github.com/wellcometrust/platform/issues/4045

Allow catalogue pipeline to subscribe to register_output topic

---

terraform/critical_prod/locals.tf
terraform/critical_prod/main.tf
terraform/critical_staging/locals.tf
terraform/critical_staging/main.tf

Goobi has some more tasks that need read access to the storage bucket.

Goobi script tasks need read access

---

terraform/critical_prod/README.md

This stack has a couple of rough edges which are non-obvious and annoying to debug, so include some notes on the types of error you might get.

Explain some known "issues" in the critical_prod stack

---

api/bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/responses/LookupBag.scala
api/bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/responses/LookupBagVersions.scala
api/bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/responses/ResponseBase.scala
api/bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/LookupBagVersionsApiTest.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/StorageManifestGenerators.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestDaoTestCases.scala
scripts/clone_bag.py

Since #436 is quite big and unwieldy, I pulled out a couple of the easy bits to make the diff easier to review.

Small refactorings from #436

---

makefiles/formatting.Makefile
terraform/critical_prod/locals.tf
terraform/critical_staging/locals.tf
terraform/modules/critical/dynamo_replicas.tf
terraform/stack_prod/locals.tf
terraform/stack_prod/main.tf
terraform/stack_staging/main.tf

For https://github.com/wellcomecollection/platform/issues/4268

Use "terraform fmt -recursive"

---

terraform/critical_prod/main.tf
terraform/critical_staging/main.tf
terraform/modules/critical/s3_replica_glacier.tf
terraform/modules/critical/s3_replica_primary.tf
terraform/modules/critical/variables.tf

This change is already applied.
Closes https://github.com/wellcomecollection/platform/issues/4276

Add versioning to the irreplaceable storage buckets

---

bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/s3/S3Unpacker.scala

Tentative fix for https://github.com/wellcomecollection/platform/issues/4320

Don't warn about unread bytes when getting the length of the file

---

terraform/modules/stack/main.tf

Closes https://github.com/wellcomecollection/platform/issues/4309, and saves us ~$1000 a year.

Don't record AWS SDK metrics that we aren't using

---

terraform/modules/stack/s3_responses.tf

Closes https://github.com/wellcomecollection/platform/issues/4322

Cycle objects in the large responses bucket to Standard-IA

---

project/Dependencies.scala

Closes https://github.com/wellcomecollection/platform/issues/4352

Bump the version of scala-storage to get retries in S3Transfer

---

common/src/main/scala/uk/ac/wellcome/platform/archive/common/ingests/services/IngestUpdater.scala

IntelliJ tells me it can't find any uses of this method, so let's spike it!

Remove an unused sendEvent() method from IngestUpdater

---

build.sbt
indexer/common/src/main/scala/uk/ac/wellcome/platform/archive/indexer/elasticsearch/ElasticClientFactory.scala
indexer/common/src/main/scala/uk/ac/wellcome/platform/archive/indexer/elasticsearch/config/ElasticClientBuilder.scala
indexer/common/src/test/scala/uk/ac/wellcome/platform/archive/indexer/fixtures/ElasticsearchFixtures.scala

Another piece of foundation work for https://github.com/wellcomecollection/platform/issues/4416

Add the ElasticClient typesafe config

---

api/bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/models/DisplayFileManifest.scala
api/bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/models/DisplayFileManifestTest.scala
bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/BagRegisterFeatureTest.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/StorageManifestGenerators.scala
display/src/test/scala/uk/ac/wellcome/platform/archive/display/fixtures/DisplayJsonHelpers.scala

Closes https://github.com/wellcomecollection/platform/issues/4422

Sort files in the display manifest alphabetically by name, rather than the order they were listed in the bag

---

.sbt_metadata/bag_indexer.json
.travis.yml
build.sbt
indexer/Makefile
indexer/bag_indexer/Dockerfile
indexer/bag_indexer/docker-compose.yml
indexer/bag_indexer/src/main/resources/application.conf
indexer/bag_indexer/src/main/resources/logback.xml
terraform/infra/ecr.tf

A first step towards https://github.com/wellcomecollection/platform/issues/4410
No interesting code here, just the skeleton of an app.

Add a skeleton for the bag indexer

---

indexer/README.md
indexer/ingests_indexer/src/main/resources/logback.xml
indexer/ingests_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/ingests/Main.scala
terraform/modules/service/worker/main.tf
terraform/modules/stack/images.tf
terraform/modules/stack/locals.tf
terraform/modules/stack/main.tf
terraform/modules/stack/messaging.tf
terraform/modules/stack/variables.tf
terraform/stack_prod/main.tf
terraform/stack_staging/main.tf

Closes https://github.com/wellcomecollection/platform/issues/4430

Wire up the ingests indexer worker

---

.sbt_metadata/ingests_tracker.json
api/bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/fixtures/BagsApiFixture.scala
api/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/fixtures/IngestsApiFixture.scala
build.sbt
common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/HttpFixtures.scala
ingests_tracker/Dockerfile
ingests_tracker/docker-compose.yml
ingests_tracker/src/main/resources/application.conf
ingests_tracker/src/main/resources/logback.xml
ingests_tracker/src/main/scala/uk/ac/wellcome/platform/storage/ingests_tracker/IngestsTrackerApi.scala
ingests_tracker/src/main/scala/uk/ac/wellcome/platform/storage/ingests_tracker/Main.scala
ingests_tracker/src/test/resources/application.conf
ingests_tracker/src/test/resources/logback-test.xml
ingests_tracker/src/test/scala/uk/ac/wellcome/platform/storage/ingests_tracker/IngestsTrackerApiFeatureTest.scala
ingests_tracker/src/test/scala/uk/ac/wellcome/platform/storage/ingests_tracker/fixtures/IngestsTrackerApiFixture.scala

Part of https://github.com/wellcomecollection/platform/issues/4419

Ingest Tracker Skeleton app

---

ingests_tracker/src/main/scala/uk/ac/wellcome/platform/storage/ingests_tracker/IngestsTrackerApi.scala
ingests_tracker/src/test/scala/uk/ac/wellcome/platform/storage/ingests_tracker/IngestsTrackerApiFeatureTest.scala

Part of https://github.com/wellcomecollection/platform/issues/4419

Add GET /ingest to ingest_tracker

---

ingests_tracker/src/main/scala/uk/ac/wellcome/platform/storage/ingests_tracker/IngestsTrackerApi.scala
ingests_tracker/src/test/scala/uk/ac/wellcome/platform/storage/ingests_tracker/IngestsTrackerApiFeatureTest.scala

Part of https://github.com/wellcomecollection/platform/issues/4419

Add POST /ingest to ingest tracker

---

ingests/src/test/scala/uk/ac/wellcome/platform/archive/ingests/IngestsFeatureTest.scala

This is to avoid situations where messages will get resent and result in double processing. Specifically we have seen this problem in CI where tests are slower.
See https://travis-ci.org/github/wellcomecollection/storage-service/jobs/682247213

Add explicit visibilityTimeout to messages on queue

---

bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorkerTest.scala
project/Dependencies.scala

See https://github.com/wellcomecollection/scala-messaging/pull/34

Use scala-messaging v9.2.0 for better SQS assertions

---

common/src/test/scala/uk/ac/wellcome/platform/archive/common/ingests/models/StorageProviderTest.scala
display/src/main/scala/uk/ac/wellcome/platform/archive/display/DisplayProvider.scala
display/src/test/scala/uk/ac/wellcome/platform/archive/display/DisplayProviderTest.scala

We might be changing how these work soon (see https://github.com/wellcomecollection/platform/issues/4466)
If we do, we'll want to maintain compatibility with existing clients, so it would be good to have some tests for the existing behaviour!

Add some tests for StorageProvider and DisplayProvider

---

bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/BagRegisterFeatureTest.scala
bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/fixtures/BagRegisterFixtures.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/BagReplicatorFeatureTest.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/fixtures/BagReplicatorFixtures.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorkerTest.scala
bag_root_finder/src/test/scala/uk/ac/wellcome/platform/storage/bag_root_finder/BagRootFinderFeatureTest.scala
bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/fixtures/BagUnpackerFixtures.scala
bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/BagUnpackerWorkerTest.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/BagVerifierFeatureTest.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixtures/BagVerifierFixtures.scala
bag_versioner/src/test/scala/uk/ac/wellcome/platform/storage/bag_versioner/BagVersionerFeatureTest.scala
bag_versioner/src/test/scala/uk/ac/wellcome/platform/storage/bag_versioner/fixtures/BagVersionerFixtures.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/StorageRandomThings.scala
indexer/ingests_indexer/src/test/scala/uk/ac/wellcome/platform/archive/indexer/ingests/IngestsIndexerFeatureTest.scala
indexer/ingests_indexer/src/test/scala/uk/ac/wellcome/platform/archive/indexer/ingests/fixtures/IngestsIndexerFixtures.scala
ingests/src/test/scala/uk/ac/wellcome/platform/archive/ingests/IngestsFeatureTest.scala
ingests/src/test/scala/uk/ac/wellcome/platform/archive/ingests/fixtures/IngestsFixtures.scala
notifier/src/test/scala/uk/ac/wellcome/platform/archive/notifier/fixtures/NotifierFixtures.scala
project/Dependencies.scala
replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/ReplicaAggregatorFeatureTest.scala
replica_aggregator/src/test/scala/uk/ac/wellcome/platform/storage/replica_aggregator/fixtures/ReplicaAggregatorFixtures.scala

See https://github.com/wellcomecollection/catalogue/pull/585

Bump scala-messaging to 9.3.0

---

terraform/modules/stack/main.tf
terraform/modules/stack/messaging.tf

For https://github.com/wellcomecollection/platform/issues/4419

Make sure the new ingests service writes to the _updated_ ingests topic

---

terraform/modules/service/api/main.tf
terraform/modules/service/ingest/main.tf
terraform/modules/stack/main.tf

This sets us back the princely sum of ~$40/month, aka easily worth it.
Closes https://github.com/wellcomecollection/platform/issues/4523

Make the indexer run a minimum of 1 task all the time

---

terraform/modules/stack/images.tf
terraform/modules/stack/locals.tf
terraform/modules/stack/main.tf
terraform/modules/stack/messaging.tf
terraform/modules/stack/variables.tf
terraform/stack_prod/main.tf
terraform/stack_staging/main.tf

For https://github.com/wellcomecollection/platform/issues/4521

Bag Indexer infrastructure

---

.travis.yml
s3_object_tagger/src/s3_object_tagger.py
s3_object_tagger/src/tag_chooser.py
s3_object_tagger/src/test_s3_object_tagger.py
s3_object_tagger/src/test_tag_chooser.py
terraform/modules/stack/lambda_s3_object_tagger.tf
terraform/modules/stack/s3_bucket_notifications.tf

Closes https://github.com/wellcomecollection/platform/issues/4488
I'm 98% sure that https://github.com/wellcomecollection/platform/issues/4535 will turn out to be false.

Add a Lambda that applies tags to new objects written to storage buckets

---

.sbt_metadata/bag_tracker.json
.travis.yml
Makefile
bag_tracker/Dockerfile
bag_tracker/src/main/resources/logback.xml
bag_tracker/src/main/scala/uk/ac/wellcome/platform/archive/bag_tracker/BagTrackerApi.scala
bag_tracker/src/main/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/BagTrackerClient.scala
bag_tracker/src/main/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/BagTrackerError.scala
bag_tracker/src/main/scala/uk/ac/wellcome/platform/archive/bag_tracker/models/BagVersionList.scala
bag_tracker/src/test/resources/application.conf
bag_tracker/src/test/resources/logback-test.xml
bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/BagTrackerApiTest.scala
build.sbt

This includes a minimal API and classes, but no actual implementations – those will come in separate PRs.
First step towards https://github.com/wellcomecollection/platform/issues/4534

Add a stub for the bag tracker app

---

bag_tracker/src/main/scala/uk/ac/wellcome/platform/archive/bag_tracker/BagTrackerApi.scala
bag_tracker/src/main/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/BagTrackerClient.scala
bag_tracker/src/main/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/BagTrackerError.scala
bag_tracker/src/main/scala/uk/ac/wellcome/platform/archive/bag_tracker/services/GetBag.scala
bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/BagTrackerClientTestCases.scala
bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/GetBagTestCases.scala
bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/ListVersionsTestCases.scala

Now we can look up bags! But only if you know the version of the bag you want to find.
For https://github.com/wellcomecollection/platform/issues/4534

Add a getBag() method to the bag tracker API

---

indexer/bag_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/bags/BagIndexer.scala
indexer/bag_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/bags/BagsIndexConfig.scala
indexer/bag_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/bags/models/IndexedStorageManifest.scala
indexer/bag_indexer/src/test/scala/uk/ac/wellcome/platform/archive/indexer/bag/BagIndexerTest.scala

Part of https://github.com/wellcomecollection/platform/issues/4521

More details on an indexed bag

---

bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/BagsApi.scala

Fixes https://github.com/wellcomecollection/platform/issues/4553

Put the Chemist + Druggist logic in the right endpoint

---

.sbt_metadata/bag_register.json
bag_register/src/main/resources/application.conf
bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/Main.scala
bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorker.scala
bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/services/Register.scala
bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/fixtures/BagRegisterFixtures.scala
bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorkerTest.scala
bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/RegisterTest.scala
build.sbt

Another part of https://github.com/wellcomecollection/platform/issues/4534

Modify the bag register to use the bag tracker

---

terraform/critical_prod/main.tf
terraform/critical_staging/main.tf
terraform/modules/critical/s3_replica_glacier.tf
terraform/modules/critical/s3_replica_primary.tf
terraform/modules/critical/variables.tf

Closes https://github.com/wellcomecollection/platform/issues/4550

Add an S3 inventory report for the storage service; ditch some unused Glacier read code

---

indexer/bag_indexer/src/main/resources/logback.xml

Maybe this will fix it ... also it should not reference logstash anymore.

Bag Indexer logs are noisy

---

bag_tracker/src/main/scala/uk/ac/wellcome/platform/archive/bag_tracker/Main.scala
terraform/modules/service/bags/main.tf
terraform/modules/stack/iam_policy_document.tf
terraform/modules/stack/iam_role_policy.tf
terraform/modules/stack/main.tf

For https://github.com/wellcomecollection/platform/issues/4534

Write up the bag register to talk to the bag tracker

---

terraform/infra/ecr.tf

And alphabetise the ones that are left, for readability.
Closes https://github.com/wellcomecollection/platform/issues/4543

Remove some old ECR repo definitions

---

indexer/reindex_ingests_backlog.py

Both for future users and @kenoir reference.

Add a script for reindexing the ingests backlog

---

terraform/infra/s3_infra.tf
terraform/modules/critical/s3_replica_glacier.tf
terraform/modules/critical/s3_replica_primary.tf

Another two steps toward https://github.com/wellcomecollection/platform/issues/4550

Expire old S3 inventory objects; don't double up the bucket name

---

terraform/app_clients/provider.tf
terraform/app_clients/secrets.tf
terraform/modules/lambda/cloudwatch_log_group.tf
terraform/modules/lambda/lambda_function.tf
terraform/modules/lambda/role.tf
terraform/modules/lambda/variables.tf
terraform/monitoring/end_to_end_test_lambda/cloudwatch_trigger.tf
terraform/monitoring/end_to_end_test_lambda/iam.tf
terraform/monitoring/end_to_end_test_lambda/main.tf
terraform/monitoring/end_to_end_test_lambda/variables.tf
terraform/monitoring/lambda_daily_reporter.tf
terraform/monitoring/lambda_end_to_end_bag_test.tf
terraform/monitoring/provider.tf
terraform/monitoring/s3_test_bags.tf
terraform/monitoring/test_bag/main.tf

For https://github.com/wellcomecollection/platform/issues/3793

Add tags for app clients and monitoring

---

python_client/.coveragerc
python_client/CHANGELOG.md
python_client/README.rst
python_client/src/wellcome_storage_service/__init__.py
python_client/src/wellcome_storage_service/exceptions.py
python_client/src/wellcome_storage_service/version.py
python_client/tests/cassettes/test_it_wraps_a_4xx_as_a_usererror.json
python_client/tests/conftest.py
python_client/tests/test_bags.py
python_client/tests/test_ingests.py
python_client/tests/test_spaces.py

* Use the new storage provider string `amazon-s3`
* Fix some inconsistent terminology in the function signatures
For https://github.com/wellcomecollection/platform/issues/4551

Bump the Python client to v2.0.0

---

indexer/reindex_bags_backlog.py
terraform/critical_prod/main.tf
terraform/critical_prod/provider.tf
terraform/critical_staging/main.tf
terraform/critical_staging/provider.tf
terraform/modules/critical/dynamo_ingests.tf
terraform/modules/critical/dynamo_replicas.tf
terraform/modules/critical/dynamo_versions.tf
terraform/modules/critical/s3_replica_glacier.tf
terraform/modules/critical/s3_replica_primary.tf
terraform/modules/critical/s3_static_content.tf
terraform/modules/critical/variables.tf
terraform/modules/critical/vhs_manifests.tf
terraform/modules/stack/iam_role_policy.tf

For https://github.com/wellcomecollection/platform/issues/3793

Add tags to the critical stack

---

.sbt_metadata/bag_indexer.json
bag_tracker/src/main/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/BagTrackerClient.scala
build.sbt
indexer/bag_indexer/src/main/resources/application.conf
indexer/bag_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/bags/BagIndexerWorker.scala
indexer/bag_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/bags/Main.scala
indexer/bag_indexer/src/test/resources/application.conf
indexer/bag_indexer/src/test/resources/logback-test.xml
indexer/bag_indexer/src/test/scala/uk/ac/wellcome/platform/archive/indexer/bag/BagIndexerFeatureTest.scala
indexer/bag_indexer/src/test/scala/uk/ac/wellcome/platform/archive/indexer/bag/BagIndexerWorkerTest.scala
indexer/common/src/test/scala/uk/ac/wellcome/platform/archive/indexer/IndexerWorkerTestCases.scala
terraform/modules/stack/main.tf

For https://github.com/wellcomecollection/platform/issues/4534

Use bag_tracker in bag_indexer

---

indexer/bag_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/bags/BagIndexerWorker.scala
indexer/bag_indexer/src/test/scala/uk/ac/wellcome/platform/archive/indexer/bag/BagIndexerFeatureTest.scala
indexer/bag_indexer/src/test/scala/uk/ac/wellcome/platform/archive/indexer/bag/BagIndexerWorkerTest.scala
indexer/bag_indexer/src/test/scala/uk/ac/wellcome/platform/archive/indexer/bag/fixtures/BagIndexerFixtures.scala
terraform/modules/stack/messaging.tf

Follows #565, for https://github.com/wellcomecollection/platform/issues/4558

Use the new notifications sent by the bag register in the indexer

---

terraform/modules/stack/iam_policy_document.tf
terraform/modules/stack/messaging.tf
terraform/modules/stack/outputs.tf
terraform/stack_prod/outputs.tf

For https://github.com/wellcomecollection/platform/issues/4558 and https://github.com/wellcomecollection/catalogue/pull/620

Export the new notification stream for the METS adapter

---

bag_register/src/main/resources/application.conf
bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/Main.scala
bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorker.scala
bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/fixtures/BagRegisterFixtures.scala

Follows #569, closes https://github.com/wellcomecollection/platform/issues/4558

Remove outgoing messages from the bag register

---

indexer/reindex_bags_backlog.py

Following bag indexer input format change.

Update reindex bag script to new format

---

common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/services/BagVerifiable.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/verify/Verifiable.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/verify/Verification.scala

Part of https://github.com/wellcomecollection/platform/issues/4562

Tidy up some unneeded implicit classes in the bag verifier

---

indexer/bag_indexer/src/main/resources/application.conf

For https://github.com/wellcomecollection/platform/issues/4571

Increase maximum parsable content length

---

.sbt_metadata/bag_tagger.json
.travis.yml
Makefile
bag_tagger/Dockerfile
bag_tagger/docker-compose.yml
bag_tagger/src/main/resources/application.conf
bag_tagger/src/main/resources/logback.xml
bag_tagger/src/main/scala/uk/ac/wellcome/platform/storage/bag_tagger/Main.scala
bag_tagger/src/main/scala/uk/ac/wellcome/platform/storage/bag_tagger/services/BagTaggerWorker.scala
bag_tagger/src/test/resources/application.conf
bag_tagger/src/test/resources/logback-test.xml
bag_tagger/src/test/scala/uk/ac/wellcome/platform/storage/bag_tagger/BagTaggerFeatureTest.scala
bag_tagger/src/test/scala/uk/ac/wellcome/platform/storage/bag_tagger/fixtures/BagTaggerFixtures.scala
build.sbt
terraform/infra/ecr.tf
terraform/modules/stack/iam_role_policy.tf
terraform/modules/stack/images.tf
terraform/modules/stack/locals.tf
terraform/modules/stack/main.tf
terraform/modules/stack/messaging.tf

For https://github.com/wellcomecollection/platform/issues/4570

Add skeleton for bag_tagger app

---

bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityChecker.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/memory/MemoryFixityChecker.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/s3/S3FixityChecker.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityCheckerTests.scala

For wellcomecollection/platform#4562, another piece from #581

Use SizeFinder to look up the size of objects in the bag verifier

---

terraform/modules/stack/iam_policy_document.tf
terraform/modules/stack/iam_role_policy.tf
terraform/modules/stack/replifier/iam_verifier.tf

For https://github.com/wellcomecollection/platform/issues/4562

Add IAM policies to allow the verifier to tag objects

---

indexer/index_chemist_and_druggist.py

Closes https://github.com/wellcomecollection/platform/issues/4571

Add a script for indexing Chemist & Druggist in Elasticsearch

---

.sbt_metadata/bag_tagger.json
bag_tagger/docker-compose.yml
bag_tagger/src/main/resources/application.conf
bag_tagger/src/main/scala/uk/ac/wellcome/platform/storage/bag_tagger/Main.scala
bag_tagger/src/main/scala/uk/ac/wellcome/platform/storage/bag_tagger/services/ApplyTags.scala
bag_tagger/src/main/scala/uk/ac/wellcome/platform/storage/bag_tagger/services/BagTaggerWorker.scala
bag_tagger/src/test/scala/uk/ac/wellcome/platform/storage/bag_tagger/BagTaggerFeatureTest.scala
bag_tagger/src/test/scala/uk/ac/wellcome/platform/storage/bag_tagger/fixtures/BagTaggerFixtures.scala
bag_tagger/src/test/scala/uk/ac/wellcome/platform/storage/bag_tagger/services/ApplyTagsTest.scala
bag_tagger/src/test/scala/uk/ac/wellcome/platform/storage/bag_tagger/services/BagTaggerWorkerTest.scala
build.sbt
common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/models/BagVersion.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/models/BagVersionTest.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/StorageManifestGenerators.scala

For https://github.com/wellcomecollection/platform/issues/4570

Actually apply tags in the bag tagger

---

terraform/modules/critical/s3_replica_glacier.tf
terraform/modules/critical/s3_replica_primary.tf

Closes https://github.com/wellcomecollection/platform/issues/4489
Applied in staging, not in prod (yet).

Add a lifecycle rule to send MXF-tagged objects to Glacier

---

project/Dependencies.scala

For: https://github.com/wellcomecollection/platform/issues/4577

Use latest version of all libs and keep in sync

---

bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/s3/S3ReplicatorTest.scala
bag_tagger/src/test/scala/uk/ac/wellcome/platform/storage/bag_tagger/BagTaggerFeatureTest.scala
bag_tagger/src/test/scala/uk/ac/wellcome/platform/storage/bag_tagger/services/ApplyTagsTest.scala
bag_tagger/src/test/scala/uk/ac/wellcome/platform/storage/bag_tagger/services/BagTaggerWorkerTest.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityChecker.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityCheckerTestCases.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityCheckerTests.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/memory/MemoryFixityCheckerTest.scala
build.sbt
common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/SizeFinder.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestServiceTest.scala
project/Dependencies.scala

For https://github.com/wellcomecollection/platform/issues/4397

Use latest version of storage libs

---

bag_tagger/src/test/scala/uk/ac/wellcome/platform/storage/bag_tagger/services/BagTaggerWorkerTest.scala
bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/BagTrackerClientTestCases.scala
bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/CreateBagTestCases.scala
bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/GetBagTestCases.scala
bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/GetLatestBagTestCases.scala
bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/ListVersionsTestCases.scala
bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/fixtures/BagsApiFixture.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestDao.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/dynamo/DynamoStorageManifestDao.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/memory/MemoryStorageManifestDao.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/StorageManifestDaoFixture.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/memory/MemoryStorageManifestDaoTest.scala
indexer/bag_indexer/src/test/scala/uk/ac/wellcome/platform/archive/indexer/bag/BagIndexerWorkerTest.scala
migrate_vhs.py
project/Dependencies.scala
scripts/migrate_vhs.py
terraform/critical_prod/main.tf
terraform/critical_staging/main.tf

This will require a migration of data held in the storage manifest VHS dynamo table.

Use latest version of scala-libs > 14.0 - changes VHS models

---

bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/Main.scala
bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorker.scala
bag_register/src/main/scala/uk/ac/wellcome/platform/archive/bag_register/services/Register.scala
bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/BagRegisterFeatureTest.scala
bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/fixtures/BagRegisterFixtures.scala
bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/BagRegisterWorkerTest.scala
bag_register/src/test/scala/uk/ac/wellcome/platform/archive/bag_register/services/RegisterTest.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/Main.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifier.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierWorker.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixtures/BagVerifierFixtures.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierTest.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/services/BagReader.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/services/memory/MemoryBagReader.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/services/s3/S3BagReader.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/memory/MemorySizeFinder.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/services/BagReaderTestCases.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/services/memory/MemoryBagReaderTest.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/services/s3/S3BagReaderTest.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/StorageManifestServiceTest.scala
terraform/modules/critical/variables.tf

Use the new location types inside the bag reader

---

bag_root_finder/src/main/scala/uk/ac/wellcome/platform/storage/bag_root_finder/models/RootFinderSummary.scala
bag_root_finder/src/main/scala/uk/ac/wellcome/platform/storage/bag_root_finder/services/BagRootFinder.scala
bag_root_finder/src/main/scala/uk/ac/wellcome/platform/storage/bag_root_finder/services/BagRootFinderWorker.scala

Another tiny step towards wellcomecollection/platform#4596

Use the S3 prefix in the bag root finder internal models

---

bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/Main.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifier.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/verify/steps/VerifyFetch.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixtures/BagVerifierFixtures.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/verify/steps/VerifyFetchTest.scala

(It would have been such a bad idea to try to do all these changes in one PR, what was I _thinking_)

Modify VerifyFetch to use new-style locations

---

scripts/migrations/migrate_ingest_sourcelocation.py

Part of wellcomecollection/platform#4596 and https://github.com/wellcomecollection/storage-service/pull/608
This script has already been run; I’m checking it in for posterity and as a possible template for future migration scripts.

Add the migration script for SourceLocation

---

bag_tagger/src/main/scala/uk/ac/wellcome/platform/storage/bag_tagger/Main.scala
bag_tagger/src/main/scala/uk/ac/wellcome/platform/storage/bag_tagger/services/ApplyTags.scala
bag_tagger/src/test/scala/uk/ac/wellcome/platform/storage/bag_tagger/fixtures/BagTaggerFixtures.scala
bag_tagger/src/test/scala/uk/ac/wellcome/platform/storage/bag_tagger/services/ApplyTagsTest.scala
bag_tagger/src/test/scala/uk/ac/wellcome/platform/storage/bag_tagger/services/BagTaggerWorkerTest.scala

Use new-style locations in the bag tagger

---

terraform/modules/stack/messaging.tf

Closes https://github.com/wellcomecollection/platform/issues/4615

Add autoscaling actions for the bag indexer and tagger

---

bag_root_finder/src/main/scala/uk/ac/wellcome/platform/storage/bag_root_finder/services/BagRootFinder.scala
bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/BagUnpackerWorker.scala
bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/UnpackerFeatureTest.scala
bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/BagUnpackerWorkerTest.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/PipelinePayload.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/generators/PayloadGenerators.scala

Bag root finder gets the unpacked bag location as a new-style location

---

scripts/common.py
scripts/create_azure_connection_string.py

Closes https://github.com/wellcomecollection/platform/issues/4582, which I’m retrospectively scoping to be an exploratory ticket. I’ll open another ticket for working out the long-term plan.

Add a script for creating an Azure connection string

---

terraform/modules/service/bags/main.tf
terraform/modules/service/bags/variables.tf
terraform/modules/service/base/main.tf
terraform/modules/service/base/variables.tf
terraform/modules/service/ingest/main.tf
terraform/modules/service/ingest/variables.tf
terraform/modules/service/worker/main.tf
terraform/modules/service/worker/variables.tf
terraform/modules/stack/main.tf
terraform/modules/stack/replifier/main.tf
terraform/modules/stack/replifier/variables.tf
terraform/stack_staging/provider.tf

Adds tags required for deployment tool to automate deploys.
This terraform has been applied in stage & prod stacks.

Add tags to services for deployment tool

---

.wellcome_project
makefiles/functions.Makefile

Update config & makefiles to use latest version of tool.

Use latest version of weco-deploy

---

.wellcome_project
terraform/modules/stack/main.tf
terraform/modules/stack/replifier/iam_verifier.tf
terraform/modules/stack/replifier/main.tf
terraform/modules/stack/replifier/variables.tf

Part of https://github.com/wellcomecollection/platform/issues/4594

Deploy a new bag verifier

---

bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/builder/BagVerifierWorkerBuilder.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/BagVerifierFeatureTest.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixtures/BagVerifierFixtures.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierWorkerTest.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/PipelinePayload.scala

BagRootLocationPayload *is* verifiable, and sent by the root finder

---

bag_root_finder/src/test/scala/uk/ac/wellcome/platform/storage/bag_root_finder/services/S3BagLocatorTest.scala

Remove an unused method from the bag root finder tests

---

bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/Main.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/Replicator.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/azure/AzureReplicator.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/models/ReplicationRequest.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/models/ReplicationResult.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/models/ReplicationSummary.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/s3/S3Replicator.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorker.scala
bag_replicator/src/main/scala/uk/ac/wellcome/storage/store/azure/NewAzureStreamStore.scala
bag_replicator/src/main/scala/uk/ac/wellcome/storage/store/azure/NewAzureTypedStore.scala
bag_replicator/src/main/scala/uk/ac/wellcome/storage/tags/azure/NewAzureBlobMetadata.scala
bag_replicator/src/main/scala/uk/ac/wellcome/storage/transfer/NewPrefixTransfer.scala
bag_replicator/src/main/scala/uk/ac/wellcome/storage/transfer/NewTransfer.scala
bag_replicator/src/main/scala/uk/ac/wellcome/storage/transfer/NewTransferResult.scala
bag_replicator/src/main/scala/uk/ac/wellcome/storage/transfer/azure/NewS3toAzurePrefixTransfer.scala
bag_replicator/src/main/scala/uk/ac/wellcome/storage/transfer/azure/NewS3toAzureTransfer.scala
bag_replicator/src/main/scala/uk/ac/wellcome/storage/transfer/s3/NewS3PrefixTransfer.scala
bag_replicator/src/main/scala/uk/ac/wellcome/storage/transfer/s3/NewS3Transfer.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/BagReplicatorFeatureTest.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/fixtures/BagReplicatorFixtures.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/ReplicatorTestCases.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/azure/AzureReplicatorTest.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/models/ReplicationRequestTest.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/s3/S3ReplicatorTest.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorkerTest.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/DestinationBuilder.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/DestinationBuilderTest.scala

Specifically, I've swapped out the Transfer classes for ones that use new-style locations (or wrappers around them, at least).

Refactor the internals of the bag replicator to use new-style locations

---

.wellcome_project
makefiles/functions.Makefile
terraform/modules/stack/main.tf

Use new project format & use new version of deploy tool in build.

Use new .wellcome_project format

---

scripts/migrations/20200724_migrate_source_location.py
scripts/migrations/common.py
terraform/critical_prod/main.tf
terraform/critical_staging/main.tf

For https://github.com/wellcomecollection/platform/issues/4596
I ran this script over the storage manifest VHS; it updated the StorageLocation in the manifests and wrote that to a new VHS. Then I updated the apps to point at the new VHS instance.
This change has been run and applied in prod.

Add a script for migrating StorageLocations

---

bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/builder/BagVerifierWorkerBuilder.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/models/BagVerifyContext.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifier.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierWorker.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/s3/S3BagVerifier.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/verify/steps/VerifySourceTagManifest.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixtures/BagVerifierFixtures.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierTestCases.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/s3/S3BagVerifierTest.scala

A first step towards https://github.com/wellcomecollection/platform/issues/4595
No behaviour changes; just some minor code cleanups I spotted while starting to write an AzureBagVerifier class.

Minor refactorings in the bag verifier

---

bag_tagger/docker-compose.yml
bag_tagger/src/main/resources/application.conf
bag_tagger/src/main/scala/uk/ac/wellcome/platform/storage/bag_tagger/Main.scala
bag_tagger/src/main/scala/uk/ac/wellcome/platform/storage/bag_tagger/services/ApplyTags.scala
bag_tagger/src/test/scala/uk/ac/wellcome/platform/storage/bag_tagger/fixtures/BagTaggerFixtures.scala
bag_tagger/src/test/scala/uk/ac/wellcome/platform/storage/bag_tagger/services/ApplyTagsTest.scala
bag_tagger/src/test/scala/uk/ac/wellcome/platform/storage/bag_tagger/services/BagTaggerWorkerTest.scala

Closes https://github.com/wellcomecollection/platform/issues/4592

Add support for tagging objects in Azure to the bag tagger

---

terraform/modules/stack/main.tf
terraform/modules/stack/variables.tf
terraform/stack_prod/main.tf
terraform/stack_staging/main.tf

Oops, I forgot to check this in on the first pass. >.<
For https://github.com/wellcomecollection/platform/issues/4592

Allow the bag tagger to get our Azure connection string

---

bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/azure/AzureReplicator.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/azure/AzureReplicatorTest.scala
bags_api/src/test/scala/uk/ac/wellcome/platform/storage/bags/api/fixtures/BagsApiFixture.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/LargeResponsesTest.scala
indexer/bag_indexer/src/test/resources/logback-test.xml
indexer/ingests_indexer/src/test/resources/logback-test.xml
ingests/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/fixtures/IngestsApiFixture.scala
project/Dependencies.scala

Hopefully a minor bump; nothing significant.

Bump scala-libs to 19.4.3

---

common/docker-compose.yml
common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/services/azure/AzureBagReader.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/services/azure/AzureBagReaderTest.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/fixtures/azure/AzureBagBuilder.scala

Part of https://github.com/wellcomecollection/platform/issues/4595. Extracted as a standalone piece from https://github.com/wellcomecollection/storage-service/pull/669
This was a single, standalone commit that can be merged on its own.

Add an implementation of AzureBagReader

---

common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/azure/AzureSizeFinder.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/azure/AzureBlobSizeFinderTest.scala

Part of wellcomecollection/platform#4595. Extracted as a standalone piece from #669; follows #680.
I split this out of https://github.com/wellcomecollection/storage-service/pull/669/commits/131b749a040df07415d2136af13577fbba2998a2 as another nice, standalone piece.

Add an implementation of AzureSizeFinder

---

bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/storage/azure/AzureLocatable.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/storage/azure/AzureResolvable.scala

Part of wellcomecollection/platform#4595. Extracted as a standalone piece from #669; follows #681.
I split this out of https://github.com/wellcomecollection/storage-service/pull/669/commits/630d9c7fd1bc2ef73eafbbefcf554f92e543218c and https://github.com/wellcomecollection/storage-service/pull/669/commits/e7967bcfb38e7db437fb884a99180bb182e13189 as a standalone piece.

Add implementations of Locatable and Resolvable for Azure

---

bag_verifier/docker-compose.yml
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifier.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/s3/S3BagVerifier.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/verify/steps/VerifyFetch.scala

Two useful commits for https://github.com/wellcomecollection/platform/issues/4595 that fix frustrations rather than deep, interesting bits of the codebase.

Two useful commits

---

bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/azure/AzureBagVerifier.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/azure/AzureReplicatedBagVerifier.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifierTestCases.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/azure/AzureReplicatedBagVerifierTests.scala

Part of wellcomecollection/platform#4595. Extracted as a standalone piece from #669; follows #688.
This is a cherry-picked version of @alicefuzier’s work in 3731e16, 1b6cc13, 17959d3, 2e77de97ef21dcc4142c002bdfbc33536e64a7a3, 94469aff52382682164cd6664685e620302e31e5, 551916070647277959707a9202a812c7a8269683, f5416b82474252ef50fdd6b4e824f64b11e35be6, 56736786c8a6e992bb7ce70087e120c86d24b77d
Now we have an AzureBagVerifier, which I believe is the last bits of #669.

Add the remaining Azure verifier classes

---

monitoring/daily_reporter/src/daily_reporter.py
terraform/monitoring/end_to_end_test_lambda/main.tf
terraform/monitoring/lambda_end_to_end_bag_test.tf
terraform/monitoring/s3_test_bags.tf

Closes https://github.com/wellcomecollection/platform/issues/4722

Run the bag reporter even if there's no ingest activity

---

bag_tagger/src/main/resources/application.conf
bag_tagger/src/main/scala/uk/ac/wellcome/platform/storage/bag_tagger/Main.scala
bag_tagger/src/main/scala/uk/ac/wellcome/platform/storage/bag_tagger/services/ApplyTags.scala
bag_tagger/src/test/scala/uk/ac/wellcome/platform/storage/bag_tagger/services/ApplyTagsTest.scala
bag_tagger/src/test/scala/uk/ac/wellcome/platform/storage/bag_tagger/services/BagTaggerWorkerTest.scala
terraform/modules/stack/main.tf

Part of https://github.com/wellcomecollection/platform/issues/4730

Don't write tags to Azure locations in the bag tagger

---

bag_tracker/src/main/scala/uk/ac/wellcome/platform/archive/bag_tracker/storage/StorageManifestDao.scala
bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/storage/StorageManifestDaoTestCases.scala

Closes https://github.com/wellcomecollection/platform/issues/4737

Allow writing storage manifests out-of-order

---

bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/Main.scala
project/Dependencies.scala

Tentatively closes https://github.com/wellcomecollection/platform/issues/4739

Bump scala-libs to 19.5.2

---

bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/Replicator.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/azure/AzureReplicator.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/s3/S3Replicator.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/ReplicatorTestCases.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/azure/AzureReplicatorTest.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/s3/S3ReplicatorTest.scala
build.sbt

Closes https://github.com/wellcomecollection/platform/issues/4746

Check for existing objects in the destination prefix, not the source

---

bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityChecker.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/azure/AzureFixityChecker.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/memory/MemoryFixityChecker.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/s3/S3FixityChecker.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/azure/AzureFixityCheckerTest.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/s3/S3FixityCheckerTest.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/azure/AzureLargeStreamReader.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/storage/services/azure/AzureRangedReader.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/LargeStreamReaderTestCases.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/azure/AzureLargeStreamReaderTest.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/storage/services/azure/AzureRangedReaderTest.scala

Follows https://github.com/wellcomecollection/storage-service/pull/714; for wellcomecollection/platform#4757 and wellcomecollection/platform#4743

Add an implementation of a LargeStreamReader for Azure

---

bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/azure/AzureFixityChecker.scala
common/src/main/scala/uk/ac/wellcome/platform/archive/common/bagit/services/BagInfoParser.scala
common/src/test/scala/uk/ac/wellcome/platform/archive/common/bagit/services/BagInfoParserTest.scala

For https://github.com/wellcomecollection/platform/issues/4766

Handle colons in the External-Description of a bag-info.txt properly

---

bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityCheckerTagsTestCases.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityCheckerTestCases.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/azure/AzureFixityCheckerTest.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/memory/MemoryFixityCheckerTest.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/s3/S3FixityCheckerTest.scala

Spun out as a separate patch from https://github.com/wellcomecollection/storage-service/pull/725 – these are some code tidies rather than functional changes.

Minor refactoring in the bag verifier

---

bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityChecker.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/azure/AzureFixityChecker.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/memory/MemoryFixityChecker.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/s3/S3FixityChecker.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityCheckerTagsTestCases.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/FixityCheckerTests.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/azure/AzureFixityCheckerTest.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/memory/MemoryFixityCheckerTest.scala
terraform/modules/stack/main.tf
terraform/modules/stack/replifier/main.tf

Follows #726; closes https://github.com/wellcomecollection/platform/issues/4771

Tag blobs in Azure with their SHA256 checksum

---

bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/Main.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/Replicator.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/azure/AzureReplicator.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/s3/S3Replicator.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/services/BagReplicatorWorker.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/storage/azure/AzurePrefixTransfer.scala
bag_replicator/src/main/scala/uk/ac/wellcome/platform/archive/bagreplicator/storage/azure/AzureTransfer.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/fixtures/BagReplicatorFixtures.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/ReplicatorTestCases.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/azure/AzureReplicatorTest.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/replicator/s3/S3ReplicatorTest.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/storage/azure/AzurePutBlockFromURLTransferTest.scala
bag_replicator/src/test/scala/uk/ac/wellcome/platform/archive/bagreplicator/storage/azure/AzurePutBlockTransferTest.scala

For https://github.com/wellcomecollection/platform/issues/4772

Use S3ObjectSummary as SrcLocation in Azure Transfer

---

bag_verifier/docker-compose.yml
bag_verifier/src/main/resources/application.conf
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/builder/BagVerifierWorkerBuilder.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/azure/AzureDynamoTags.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/azure/AzureFixityChecker.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/azure/AzureReplicatedBagVerifier.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/azure/AzureDynamoTagsTest.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixity/azure/AzureFixityCheckerTest.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/fixtures/BagVerifierFixtures.scala
bag_verifier/src/test/scala/uk/ac/wellcome/platform/archive/bagverifier/services/azure/AzureReplicatedBagVerifierTests.scala
terraform/modules/stack/dynamo.tf
terraform/modules/stack/iam_policy_document.tf
terraform/modules/stack/iam_role_policy.tf
terraform/modules/stack/main.tf
terraform/modules/stack/replifier/main.tf
terraform/modules/stack/replifier/variables.tf

What if we stuck tags about Azure objects in a DynamoDB sidecar?

Add an implementation of Azure tags in Dynamo

---

bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/BagVerifier.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/azure/AzureReplicatedBagVerifier.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/services/s3/S3BagVerifier.scala
bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/verify/steps/VerifySourceTagManifest.scala
ingests/ingests_api/src/test/resources/logback-test.xml
ingests/ingests_tracker/src/test/resources/logback-test.xml
ingests/ingests_worker/src/test/resources/logback-test.xml

Spotted while reading some code for https://github.com/wellcomecollection/platform/issues/4774

Code tidies in the bag verifier

---

bag_verifier/src/main/scala/uk/ac/wellcome/platform/archive/bagverifier/models/VerificationSummary.scala

Include the total size verified in a verification summary log

---

terraform/modules/service/base/main.tf

In order to add "deployment:label" tags to services.

Update ecs service modules to latest

---

.buildkite/pipeline.yml
terraform/monitoring/end_to_end_test_lambda/main.tf
terraform/monitoring/lambda_end_to_end_bag_test.tf
terraform/monitoring/terraform.tf

For https://github.com/wellcomecollection/platform/issues/4819

Send a test bag in stage from BuildKite

---

monitoring/daily_reporter/src/slack.py
monitoring/daily_reporter/src/templates/report.html

Stealing an idea from @kenoir in the snapshot reporter: if all is well, it prints ✅. If something needs attention, it prints ⁉️

Use an emoji to highlight daily reporter state

---

python_client/CHANGELOG.md
python_client/README.rst
python_client/release.sh
python_client/setup.py
python_client/src/wellcome_storage_service/__init__.py
python_client/src/wellcome_storage_service/version.py
python_client/tests/conftest.py
python_client/tests/test_client.py
python_client/tests/test_downloader.py
python_client/tox.ini

Closes https://github.com/wellcomecollection/platform/issues/4852
Plus automating the release process.

Allow creating a Python client for the storage service from a path

---

README.md
scripts/migrations/2020-10-miro-migration/miro_ids.py
scripts/migrations/2020-10-miro-migration/test_miro_ids.py

`master` is borken as I was too eager with the merge button, let CI apply autofixes.

Apply auto-formatting rules

---

indexer/file_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/files/FilesIndexConfig.scala
indexer/file_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/files/models/IndexedFile.scala
indexer/file_indexer/src/test/scala/uk/ac/wellcome/platform/archive/indexer/files/models/IndexedFileTest.scala

For https://github.com/wellcomecollection/platform/issues/4859

Add a name field to the bags index

---

bag_register/docker-compose.yml
bag_replicator/docker-compose.yml
bag_root_finder/docker-compose.yml
bag_tagger/docker-compose.yml
bag_tracker/docker-compose.yml
bag_unpacker/docker-compose.yml
bag_verifier/docker-compose.yml
bag_versioner/docker-compose.yml
bags_api/docker-compose.yml
common/docker-compose.yml
docker_run.py
indexer/file_finder/docker-compose.yml
indexer/ingests_indexer/docker-compose.yml
ingests/ingests_tracker/docker-compose.yml
ingests/ingests_worker/docker-compose.yml
makefiles/formatting.Makefile
makefiles/functions.Makefile
notifier/docker-compose.yml
replica_aggregator/docker-compose.yml

For https://github.com/wellcomecollection/platform/issues/4879

Pull Docker images from our private ECR registry, not Docker Hub

---

scripts/helpers/azure.py

Part of wellcomecollection/platform#4878, spun out of #777

Add some helper functions for dealing with Azure

---

bag_register/Dockerfile
bag_replicator/Dockerfile
bag_root_finder/Dockerfile
bag_tagger/Dockerfile
bag_tracker/Dockerfile
bag_unpacker/Dockerfile
bag_verifier/Dockerfile
bag_versioner/Dockerfile
bags_api/Dockerfile
indexer/bag_indexer/Dockerfile
indexer/file_finder/Dockerfile
indexer/file_indexer/Dockerfile
indexer/ingests_indexer/Dockerfile
ingests/ingests_api/Dockerfile
ingests/ingests_tracker/Dockerfile
ingests/ingests_worker/Dockerfile
nginx/Dockerfile
notifier/Dockerfile
replica_aggregator/Dockerfile

Another 19 images that we'd pull on every build! 🙈 
The images aren't in ECR yet, but I'm uploading them now.

Use an image in ECR as the base for our Docker images

---

scripts/helpers/dynamo.py
scripts/helpers/iam.py
scripts/helpers/reporting.py
scripts/helpers/s3.py
scripts/helpers/storage_service.py
scripts/ss_delete_bag.py
scripts/tests/test_s3.py

The final part of https://github.com/wellcomecollection/platform/issues/4878!

Delete all the DynamoDB items for a deleted bag

---

scripts/helpers/storage_service.py

The indentation here is playing tricks with looking at both apis.

Bag deletion only looks at stage

---

bag_unpacker/src/main/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/Unpacker.scala
bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/UnpackerFeatureTest.scala
bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/fixtures/BagUnpackerFixtures.scala
bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/fixtures/CompressFixture.scala
bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/UnpackerTestCases.scala
bag_unpacker/src/test/scala/uk/ac/wellcome/platform/archive/bagunpacker/services/s3/S3UnpackerTest.scala

Some cleanups done while working on https://github.com/wellcomecollection/platform/issues/4911

Refactor a few of the tests in the bag unpacker

---

project/Dependencies.scala

This will allow us to retry a particular class of flaky Azure error.

Bump scala-libs to v25.0.2

---

.buildkite/scripts/run_job.py
terraform/modules/lock_table/main.tf
terraform/modules/service/bags/main.tf
terraform/modules/service/base/main.tf
terraform/modules/service/ingest/main.tf
terraform/stack_prod/.terraform.lock.hcl
terraform/stack_prod/provider.tf
terraform/stack_staging/.terraform.lock.hcl
terraform/stack_staging/provider.tf

The actually interesting bit is a single line change, then I did some Terraform housekeeping while I was here.
These changes are all applied.

Give our services the BatchWriteItem permission to write to our lock tables

---

project/Dependencies.scala
terraform/modules/stack/replifier/main.tf

For https://github.com/wellcomecollection/platform/issues/5148
It's hard to test either of these changes directly – they may not have a deterministic result – but they both seem plausibly useful.

Fix a couple of things that might be causing the recent flakiness

---

bag_tracker/src/main/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/BagTrackerClient.scala
bag_tracker/src/main/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/TrackerClientBase.scala
bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/client/AkkaBagTrackerClientTest.scala
bag_tracker/src/test/scala/uk/ac/wellcome/platform/archive/bag_tracker/fixtures/BagTrackerFixtures.scala
bags_api/src/main/scala/uk/ac/wellcome/platform/storage/bags/api/Main.scala
build.sbt
indexer/bag_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/bags/BagsIndexConfig.scala
indexer/common/src/main/scala/uk/ac/wellcome/platform/archive/indexer/elasticsearch/ElasticFieldOps.scala
indexer/common/src/main/scala/uk/ac/wellcome/platform/archive/indexer/elasticsearch/StorageServiceIndexConfig.scala
indexer/file_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/files/FilesIndexConfig.scala
indexer/ingests_indexer/src/main/scala/uk/ac/wellcome/platform/archive/indexer/ingests/IngestsIndexConfig.scala
ingests/ingests_api/src/main/scala/uk/ac/wellcome/platform/storage/ingests/api/Main.scala
ingests/ingests_api/src/test/scala/uk/ac/wellcome/platform/storage/ingests/api/fixtures/IngestsApiFixture.scala
ingests/ingests_tracker/src/main/scala/uk/ac/wellcome/platform/storage/ingests_tracker/client/IngestTrackerClient.scala
ingests/ingests_tracker/src/test/scala/uk/ac/wellcome/platform/storage/ingests_tracker/client/IngestTrackerClientTest.scala
ingests/ingests_worker/src/test/scala/uk/ac/wellcome/platform/storage/ingests_worker/IngestsWorkerIntegrationTest.scala
ingests/ingests_worker/src/test/scala/uk/ac/wellcome/platform/storage/ingests_worker/fixtures/IngestsWorkerFixtures.scala
ingests/ingests_worker/src/test/scala/uk/ac/wellcome/platform/storage/ingests_worker/services/IngestsWorkerServiceTest.scala
notifier/src/main/scala/uk/ac/wellcome/platform/archive/notifier/Main.scala
notifier/src/main/scala/uk/ac/wellcome/platform/archive/notifier/services/CallbackUrlService.scala
notifier/src/test/scala/uk/ac/wellcome/platform/archive/notifier/fixtures/NotifierFixtures.scala
project/Dependencies.scala

For https://github.com/wellcomecollection/platform/issues/5192
This gets all our services using a similar implementation of an HTTP client and the latest version of elastic4s.

Use the new scala-libs and the shared HTTP client

---

terraform/modules/stack/iam_policy_document.tf

Give GetObject permissions on individual objects, not the buckets

---

terraform/infra/ecr_policy.tf
terraform/modules/stack/images.tf

For https://github.com/wellcomecollection/platform/issues/5206

Allow cross-account ECR access to our storage service images

---

terraform/modules/service/bags/main.tf
terraform/modules/service/bags/variables.tf
terraform/modules/service/base/main.tf
terraform/modules/service/ingest/main.tf
terraform/modules/service/ingest/variables.tf
terraform/modules/service/worker/main.tf
terraform/modules/stack/main.tf
terraform/modules/stack/variables.tf
terraform/stack_prod/main.tf
terraform/stack_staging/main.tf

For https://github.com/wellcomecollection/platform/issues/5226 and https://github.com/wellcomecollection/platform/issues/5206, builds on https://github.com/wellcomecollection/terraform-aws-ecs-service/pull/36

Make the nginx container configurable in the stack module

---

bag_verifier/src/test/scala/weco/storage_service/bag_verifier/services/BagVerifierTestCases.scala
common/src/main/scala/weco/storage_service/verify/ChecksumValue.scala
common/src/test/scala/weco/storage_service/fixtures/BagBuilder.scala
common/src/test/scala/weco/storage_service/verify/ChecksumValueTest.scala

Closes https://github.com/wellcomecollection/storage-service/issues/896

Treat uppercase and lowercase checksums as equal

---

common/src/main/scala/weco/storage_service/ingests/models/IngestType.scala
docs/README.md
docs/explanations/ingest-semantics.md

Based on a conversation in Slack here: https://wellcome.slack.com/archives/CN56BRQ5B/p1626427292100000

Write a bit about the semantics of ingests and ingest types

---

common/src/main/scala/weco/storage_service/bagit/models/Bag.scala
common/src/main/scala/weco/storage_service/bagit/models/BagManifest.scala
common/src/main/scala/weco/storage_service/bagit/models/UnreferencedFiles.scala
common/src/main/scala/weco/storage_service/bagit/services/BagReader.scala
common/src/main/scala/weco/storage_service/checksum/ChecksumAlgorithm.scala
common/src/main/scala/weco/storage_service/checksum/MultiManifestChecksum.scala
common/src/test/scala/weco/storage_service/bagit/services/BagReaderTestCases.scala
common/src/test/scala/weco/storage_service/checksum/MultiChecksumTest.scala
common/src/test/scala/weco/storage_service/generators/StorageRandomGenerators.scala

For #900. This is some refactoring and variable name tweaking that isn't complicated, I just wanted to pull it out separately to avoid noise in the diff of my next PR.

A few tidy-ups for multi-checksum support

---

demo/terraform/demo_stack/metadata_stores.tf
demo/terraform/demo_stack/stack.tf

cc @h4l 
Closes https://github.com/wellcomecollection/storage-service/issues/906

Use local references for in-repo Terraform modules in the demo

---

bag_tracker/src/test/scala/weco/storage_service/bag_tracker/client/GetBagTestCases.scala
bag_tracker/src/test/scala/weco/storage_service/bag_tracker/client/GetLatestBagTestCases.scala
bag_tracker/src/test/scala/weco/storage_service/bag_tracker/client/ListVersionsTestCases.scala
bag_tracker/src/test/scala/weco/storage_service/bag_tracker/fixtures/StorageManifestDaoFixture.scala
bag_tracker/src/test/scala/weco/storage_service/bag_tracker/storage/StorageManifestDaoTestCases.scala
bag_tracker/src/test/scala/weco/storage_service/bag_tracker/storage/dynamo/DynamoStorageManifestDaoTest.scala
bags_api/src/test/scala/weco/storage_service/bags_api/LookupBagApiTest.scala
bags_api/src/test/scala/weco/storage_service/bags_api/LookupBagVersionsApiTest.scala
bags_api/src/test/scala/weco/storage_service/bags_api/fixtures/BagsApiFixture.scala
common/src/main/scala/weco/storage_service/storage/services/DestinationBuilder.scala
common/src/test/scala/weco/storage_service/generators/StorageManifestGenerators.scala
common/src/test/scala/weco/storage_service/storage/services/DestinationBuilderTest.scala
indexer/bag_indexer/src/test/scala/weco/storage_service/indexer/bags/fixtures/BagIndexerFixtures.scala
indexer/bag_indexer/src/test/scala/weco/storage_service/indexer/bags/models/IndexedStorageManifestTest.scala
ingests/ingests_tracker/docker-compose.yml

Some tidying I spotted while working on https://github.com/wellcomecollection/platform/issues/5287. These should be no-op changes.

Minor refactoring and code tidies in the storage service tests

---

builds/publish_image_with_weco_deploy.sh
builds/run_sbt_task_in_docker.sh

Fixing one of the side-effects of wellcomecollection/platform#5364

Fix the path to DOCKER_CONFIG for CI

---

docs/README.md
docs/wellcome/replica-configuration.md

Because among other things, _I_ didn't know where to find our Azure replicas in the Azure portal, and I helped put them there!
I've also clarified a bit about our policy for getting access to those containers (i.e. not unless you have a v good reason).

Add some explanation and links to our replica config

---

bag_register/Dockerfile
bag_replicator/Dockerfile
bag_root_finder/Dockerfile
bag_tagger/Dockerfile
bag_tracker/Dockerfile
bag_tracker/docker-compose.yml
bag_unpacker/Dockerfile
bag_verifier/Dockerfile
bag_verifier/docker-compose.yml
bag_versioner/Dockerfile
bag_versioner/docker-compose.yml
bags_api/Dockerfile
indexer/bag_indexer/Dockerfile
indexer/file_finder/Dockerfile
indexer/file_indexer/Dockerfile
indexer/ingests_indexer/Dockerfile
ingests/ingests_api/Dockerfile
ingests/ingests_tracker/Dockerfile
ingests/ingests_tracker/docker-compose.yml
ingests/ingests_worker/Dockerfile
notifier/Dockerfile
replica_aggregator/Dockerfile
replica_aggregator/docker-compose.yml

For https://github.com/wellcomecollection/platform/issues/5545, which includes a discussion of the benefits.

Use Docker images from ECR Public, not our vendored repos

---

terraform/modules/service/bags/main.tf
terraform/modules/service/base/main.tf
terraform/modules/service/ingest/main.tf
terraform/modules/service/worker/main.tf

Fixes logging, already applied

Bump ECS tf module versions

---

docs/developers/ecr-publishing.md

For https://github.com/wellcomecollection/platform/issues/5631

Remove the remaining references to weco-deploy

---

terraform/modules/service/bags/main.tf
terraform/modules/service/base/main.tf
terraform/modules/service/ingest/main.tf
terraform/modules/service/worker/main.tf

Bump ECS module versions to access updated firelens container

---

.buildkite/pipeline.deploy-prod.yml
.buildkite/pipeline.deploy-stage.yml

The task definitions are expecting images tagged with `env.$ENV` but the images were just tagged with `$ENV`

deploy images with env.prod & env.stage

---

build.sbt
project/Dependencies.scala

For https://github.com/wellcomecollection/storage-service/issues/1066

Add an explicit dependency on io.netty to fix a ClassNotFoundError

---

docs/wellcome/awkward-files-and-bags.md

Closes https://github.com/wellcomecollection/platform/issues/5708

Make a note of the two bags that had files removed

---

builds/run_formatting.sh
indexer/reindex_bags_backlog.py
python_client/tests/test_downloader.py
scripts/helpers/azure.py
scripts/helpers/iam.py
scripts/migrations/2020-08-create_azure_replicas.py
scripts/migrations/2020-10-archivematica_bags_migration.py

For https://github.com/wellcomecollection/platform/issues/5724

Switch to using the official Black Docker image for Python formatting

---

terraform/monitoring/.terraform.lock.hcl
terraform/monitoring/end_to_end_test_lambda/main.tf
terraform/monitoring/lambda_daily_reporter.tf
terraform/monitoring/lambda_digital_production_reports.tf

https://github.com/wellcomecollection/platform/issues/5732
Already applied ✅

upgrade lambdas to python3.10 + provider fix
